### ISSUE TITLE
Shiny Reactivity Fails with data.tables

### ISSUE THREAD

**Issue by codoremifa** [rstudio/shiny#1017]
I suspect modifying values by reference causes Shiny's reactivity to fail as I asked in this SO question - 
http://stackoverflow.com/questions/32536940/shiny-reactivity-fails-with-data-tables

In the example on the link, I have a reactive data.table. upon modification of the data.table, the downstream reactive chunks aren't triggered.

**Comment by jcheng5** [comment]
The contract of the reactiveValues object is that reactivity is triggered when `$<-` or `[[` is used to reassign one of its values. This is what R is actually doing when you do something like `rv$dataframe[row,col] <- ...`. The reactiveValues object has no visibility into what's happening with reference classes, R6 classes, environment objects, external pointers, and yes, data.tables, that happen to be values inside of it.

How about using a wrapper as a work around, like this:

```r
byref_handle <- function(obj) {
  rv <- reactiveValues(trigger = 0)
  list(
    get = function() {
      rv$trigger
      return(obj)
    },
    mutate = function(func) {
      on.exit(rv$trigger <- isolate(rv$trigger) + 1)
      func(obj)
    }
}
```

```r
shinyServer(function(input, output, session) {
  dt <- byref_handle(data.table(...))

  output$plot <- renderPlot({
    data <- dt$get()
    # do read-only stuff with data
  })

  observeEvent(input$button, {
    dt$mutate(function(dataTable) {
      dataTable[...]
      # do mutations here
    })
  })  
})
```

You might also consider using dplyr. Its by-value approach is a more natural fit for Shiny, and its memory behavior should be hugely improved since R 3.1.0. If you don't already have a lot of code investment in data.table, it might be worth at least measuring the memory consumption and performance impact of switching to dplyr.

I'm going to close this because I don't believe there's anything actionable on our side here, but if there are concrete changes you can imagine us making to Shiny to work better with data.table, please feel free to suggest them!

**Comment by codoremifa** [comment]
Thanks. Two other workarounds I've been using involve updating a numeric variable with a random value every time I modify the data.table, and keeping the data.table inside a list and updating the list at the end of all my data.table operations.

Unfortunately, I do have a lot of investment in `data.table`. In the past data.table used to outperform dplyr. I'd be most interested in seeing any new benchmarks that you are publishing.

Thanks for the great libraries!

**Comment by DavZim** [comment]
I ran into the same issue, and found that using `:=` within data.table does not trigger reactivity, but using `<-` works.

Eg a nice comparison is this:
```
library(shiny)

ui <- fluidPage(
  verbatimTextOutput("text_fails"),
  actionButton("go_fails", "This does not work!"),

  verbatimTextOutput("text_works"),
  actionButton("go_works", "This works")
)

server <- function(input, output, session) {
  
  state <- reactiveValues(
    dd_fails = data.table::data.table(x = 1),
    dd_works = data.table::data.table(x = 1)
  )
  output$text_fails <- renderPrint(print(state$dd_fails))
  output$text_works <- renderPrint(print(state$dd_works))
  
  observeEvent(input$go_fails, {
    # also fails:
    # dd_fails <- state$dd_fails
    # dd_fails[, x := rnorm(1)]
    # state$dd_fails <- dd_fails
    state$dd_fails[, x := rnorm(1)]
  })
  observeEvent(input$go_works, {
    # dd_works <- state$dd_works
    # dd_works$x <- rnorm(1)
    # state$dd_works <- dd_works
    # alternatively
    state$dd_works$x <- rnorm(1)
  })
}

shinyApp(ui, server)
```
