### ISSUE TITLE
symlinks in www are not being followed

### ISSUE THREAD

**Issue by fmichonneau** [rstudio/shiny#1064]
Symlinks placed in the the `www` directory of a shiny app are not made available to the server.

Would it be possible to change this behavior?

**Comment by wch** [comment]
Shiny will follow symlinks in `www`, but only if the symlink points to somewhere within `www`.

This is where it is set:
https://github.com/rstudio/shiny/blob/ac95dcb/R/middleware.R#L202
https://github.com/rstudio/shiny/blob/ac95dcb/R/utils.R#L214-L240

Perhaps it would be a good idea to allow symlinks outside of the www directory, at least as an option.

**Comment by jcheng5** [comment]
I didn't realize `normalizePath` turned symlinks into their real paths--that wasn't my intention. I just wanted `.` and `..` to be eradicated.

However, there's what I hope is an easy workaround, that's to put `addResourcePath` calls into global.R; you can use this to map any URL prefix to any directory.

**Comment by wch** [comment]
Maybe we should have our own version of `normalizePath` that doesn't follow symlinks. But we'd also want it to be an option whether to follow symlinks out of www, for security reasons.

**Comment by heroxbd** [comment]
See also https://github.com/rstudio/shiny-server/issues/119

**Comment by heroxbd** [comment]
Debian's hack to circumvent this bug.  References are:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867963
https://sources.debian.org/src/r-cran-shiny/1.0.5+dfsg-4/debian/patches/fix_utils_resolve_for_debian.patch/

**Comment by jcheng5** [comment]
@heroxbd, if I'm reading this right, it's pointing to the wrong version of Bootstrap (2.x)--our bundled version is 3.x, which goes under `/usr/share/javascript/bootstrap` (according to https://packages.debian.org/sid/all/libjs-bootstrap/filelist).

**Comment by heroxbd** [comment]
Hi Joe, I have checked the changlog. It is version 3.

http://metadata.ftp-master.debian.org/changelogs/main/t/twitter-bootstrap3/twitter-bootstrap3_3.3.7+dfsg-2_changelog

On Jan 23, 2018 3:27 PM, "Joe Cheng" <notifications@github.com> wrote:

@heroxbd <https://github.com/heroxbd>, if I'm reading this right, it's
pointing to the wrong version of Bootstrap (2.x)--our bundled version is
3.x, which goes under /usr/share/javascript/bootstrap (according to
https://packages.debian.org/sid/all/libjs-bootstrap/filelist).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rstudio/shiny/issues/1064#issuecomment-359989816>, or mute
the thread

**Comment by alandipert** [comment]
Closing because the original problem appears to have been addressed: use `addResourcePath` to map URLs to directories outside of `www/` as Shiny will not follow symlinks out of `www/`.

Please don't hesitate to comment further or open a new issue if you believe this issue remains unresolved.
