### ISSUE TITLE
Potential problem with usage of new `req` function

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1076]
I just looked at what's new in 0.13 and I'm really excited about the new features. The new `req` function is definitely a huge improvement from a usability point of view over the previous system for validating inputs!

But the fact that only "truthy" values are accepted, and a `FALSE` causes the code to stop, made me wonder if that's not a bit weird for anybody who uses an input that returns `TRUE`/`FALSE`, such as a `checkboxInput`.  The issue is that whenever the checkbox is unchecked, the function that requires the checkbox to just exist will stop execution. 

Example: Suppose I render a checkbox using `uiOutput`. Another output depends on this checkbox. Here is a basic shiny app like that

```
library(shiny)

ui <- fluidPage(
  uiOutput("foo"),
  textOutput("bar")
)

server <- function(input, output, session) {
  output$foo <- renderUI({
    checkboxInput("checkbox", "checkbox", FALSE)
  })
  
  output$bar <- renderText({
    if(input$checkbox) {
      "true"
    }
    else {
      "false"
    }
  })
}

shinyApp(ui = ui, server = server)
```

This app works but when it first loads it throws an error. To fix that, prior to 0.13, I would include a check `if (is.null(input$checkbox)) return()` as the first line inside the `renderText`.  That will get rid of the initial error message. But now with the `req` function, I would like to be able to replace that check with a simple `req(input$checkbox)`. When I do this, the text output is simply not rendered when the checkbox is unchecked (aka `FALSE`).

Is this intended behaviour?  My most common usecase for validating inputs is just checking that they merely exist because they are rendered on the server side. Perhaps `req` was designed more to handle other cases, like validating *values* instead of *existence*?  I hope my question makes sense.

Great feature nonetheless.

**Edit:** Also, the section about "Truthy and falsy values" in the function documentation seems to not be formatted correctly. I think it's meant to be a subheader/section header, but it just appears as bold text

**Comment by jcheng5** [comment]
Thanks for the feedback.

The truthy/falsy distinction is meant to address not only the presence or absence of input controls, but whether the user has "provided" a value or not. So an empty textInput returns "" and fails; an empty numericInput returns NA and fails. The checkbox is an unfortunate innocent bystander, you can work around it like this: `req(!is.null(input$checkbox))`

Or if you like you can write your own req wrapper. The reason we also fail on FALSE is exactly for these scenarios--if our heuristics don't fit your need, you can simply put an arbitrary boolean expression in there.

**Comment by daattali** [comment]
@bborgesr 
 I think this is important to try to fix if you want people to use req() because this is a silent bug (tge worst kind of bug!), people would just not have their reactives run without knowing. Just wanted to bring it up again in case there's a simple fix

**Comment by bborgesr** [comment]
Oh man, @daattali, I used to really like `req` before reading this! I can't think of any elegant solution. The problem here is that if you know how `req` works, it's unlikely you'll even make this mistake. And if you don't really know how it works, it's likely you'll make this mistake without even noticing... It's hard to call it a bug though, because at the end of the day it *is* the expected behavior.

The best "solution" I could come up with now would be adding a new arg to `req` called something like `failIf`with options: `falsy` (default), `FALSE`, `NULL`. Of course you can already do this (respectively, `req(x)`, `req(x != FALSE)` and `req(!is.null(x))`. The hope would be that by making it an explicit argument, it would be more obvious to an user that the default does not always work for all use cases... I'm afraid, however, that this would just clutter things up, and not really help anyone...

So, I don't think I have a good answer for this. Perhaps this will just be a necessary evil that we need to tolerate when we use `req`.

The one thing we can certainly do is document this edge case in the function documentation. Do you think that makes sense, @jcheng5?

**Comment by earnaud** [comment]
Hi ! 
I do have some issue about `req` using it with an empty data.frame. In simple, my code is as follow: 
```r
library(shiny)

ui <- fluidPage(
  fileInput("id","File"),
  tableOutput("out")
)

server <- function(input, output, session) {
  outvar <- reactiveValues(
    tmp = data.frame()
  )
    
  observeEvent(input$id,{
    outvar$tmp <- input$id
  })
    
  output$out <- renderTable({
    browser()
    req(outvar$tmp)
    print("passed")
    outvar$tmp$name
  })
}

shinyApp(ui, server)
```
Even if this code actually works, the "passed" is printed with a NULL data.frame. Also, if you wonder why I use such a crappy design, it is a minimal example of my app, and the `reactiveValues` is actually used to store values across modules.

Practically, this is not blocking but `req` considers empty data frame as a truthy value, which is false in my sense.

**Comment by cpsievert** [comment]
@earnaud note that you can pass an expression to `req()`, so you can do: `req(nrow(outvar$tmp) > 0)`
