### ISSUE TITLE
ShinyAce does not work with shiny module?

### ISSUE THREAD

**Issue by happyshows** [rstudio/shiny#1081]
Hi,

I was using shinyBS together with shinyAce Editor.

It seems that when I wrap the ace editor id with ns() in ui.R, shiny won't be able to render the editor correctly. But even go without ns(), server.R won't be able to find the id in input$ list.

Not sure why this happened.

**Comment by VermillionAzure** [comment]
I have a similar issue.

**Comment by Yang-Tang** [comment]
It is due to ShinyAce's own bug. The aceEditor function in ShinyAce dosen't accecp an outputId that contains "-" because it uses this outputId as a bare object name in javascript which consider the "-" as subtraction. 
In shiny module, the function ns() is just a simple wrap of `paste(c(namespace, id), collapse = ns.sep)`, where the `id` in your case is the outputId of aceEditor and the `ns.sep` is currently set as "-" internally. This setting makes every shiny module id contains a "-" which may trigger the potential bug of some javascript wrapper package like ShinyAce.
Since the ShinyAce hasn't been updated for a long time, I don't know whether the auther @trestletech  have time to fix it for shiny module. Another way is to ask shiny's develompers @jcheng5 to change the `ns.sep` to some other javascript-friendly characters.

**Comment by daattali** [comment]
It's probably a good idea to file an issue in the shinyAce repository rather than here if you want to increase the chances of this being fixed

**Comment by Yang-Tang** [comment]
You are right. I'll post an issue there.

**Comment by happyshows** [comment]
or there's another potential solution, change ns() to allow user to input a separator which by default is '-'.

**Comment by daattali** [comment]
@happyshows I still think the issue should be fixed in shinyAce, because by just allowing users to use a different separator, users will have to know that they need to do this. I personally think the burden to accommodate modules should be on the package author, not on the user

**Comment by VermillionAzure** [comment]
@daattali I agree. However, I'd also like to highlight the issue with trying to embed other generic code into the modules--executing a `ns("id")` in a module and having the namespace propagate through the various namespace specializations is important.

**Comment by trestletech** [comment]
Agreed that this should be fixed in ShinyAce.
