### ISSUE TITLE
Better DPI calibration

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#1090]
``` R
library(miniUI)
library(ggplot2)
library(grid)

iphone <- function(data, xvar, yvar) {
  ui <- miniPage(
    gadgetTitleBar("Put your iphone next to this line"),
    miniContentPanel(
      plotOutput("plot", height = "100%", brush = "brush")
    )
  )

  server <- function(input, output, session) {
    output$plot <- renderPlot({
      grid.newpage()
      grid.segments(0.5, 0, 0.5, unit(5.44, "inches"))
    })
  }

  runGadget(ui, server)
}
iphone()
```

**Comment by wch** [comment]
I think that what's needed is to use a default of 96 ppi (instead of the current 72). We currently multiply that value with the pixelratio reported by the browser, which is the right thing to do.

The size of a "reference pixel", which corresponds to 1px in CSS, is defined as 1/96 of an inch:
http://stackoverflow.com/questions/27382331/how-a-css-pixel-size-is-calculated

**Comment by hadley** [comment]
Duplicate of #1832
