### ISSUE TITLE
downloadHandler error not seen by client

### ISSUE THREAD

**Issue by aronatkins** [rstudio/shiny#1122]
The following test case produces a Shiny application which never responds to download requests.

This case intentionally errs within the `downloadHandler`; the bug is that the browser is not sent an error response. Instead, the browser sits endlessly waiting.

```r
library(shiny)

server <- function(input, output) {
  plots <- reactiveValues(scatter=NULL, histres=NULL, resx=NULL, reshyat=NULL);
  output$save <- downloadHandler(
      filename = paste("Scatterplot.png"),
      content = function(file) {
        png(file, height=400, width=600)
        print(isolate(plots$scatter))
        dev.off()
      },
      contentType = "image/png"
  );
};

ui <- fluidPage(
    titlePanel("bogus download"),
    downloadButton("save", "Download")
);

shiny::shinyApp(server = server, ui = ui);
```

When running locally, the following output is produced:

```
Listening on http://127.0.0.1:5801
NULL
Error opening file: 2
Error reading: 9
```

**Comment by jcheng5** [comment]
Thanks @aronatkins. It looks like this problem happens when control returns normally from the content function but the file isn't actually created (an empty content function will do the same).

We fix this by having Shiny check for the condition, and/or have httpuv respond better to this behavior by return status 500 or something to the client.
