### ISSUE TITLE
Cannot update multiple select inputs in shiny at the same time in the first time

### ISSUE THREAD

**Issue by byzheng** [rstudio/shiny#1128]
I posted a question in stackoverflow, but think it could be a bug in Shiny, and more suitable to post in github.

I have a shiny app which has multiple `selectInput` and need to be dynamically updated. The R codes below show a minimum example to reproduce my question.

There are two selectInput and one button. The default value is `A1` for `A` and `B1` for `B`. I will update `A` into `A2`, `B` into `B4` when I click the button. However, the `B` becomes `B3` in the first click (wrong result), but `B4` at the second click (correct result).

It is really strange behavior. How could I fix this problem? Thanks for any suggestions. 

PS: I installed the latest version of shiny in github.

See here for screenshot and example codes: http://stackoverflow.com/questions/35843364

**Comment by daattali** [comment]
I just took a very quick look at your code and it doesn't look like you're seeing a bug in shiny.  You're trying to update the selectInput to a specific value before that value even becomes an option.  When input B gets an updated value of B4, it still only has B1,B2 as options, so nothing happens. Then, **after that**, it gets B3,B4 as options, so it default to B3, and nothing else happens because the call to update it to B4 already happened earlier.  Hopefully that makes sense.  But definitely not a shiny bug

**Comment by byzheng** [comment]
Agree this is my own problem. Get answer from stackoverflow.
