### ISSUE TITLE
Multiple Reactives for Single Output Don't Work

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1139]
Only the second `renderText` function is ever triggered in the following example.

    library(shiny)
    library(DT)

    shinyApp(
      ui = fluidPage(
        actionButton("deselectButton", "Deselect All"),
        actionButton("chooseBest", "Find Best"),
        textOutput("bestText")
      ),
      server = function(input, output, session) {

        # Never run.
        output[["bestText"]] <- renderText({
          input[["deselectButton"]]
          print("Change to No Best")  
          "No best flower."
        })
        
        # Works.
        output[["bestText"]] <- renderText({
              input[["chooseBest"]]
              print("Change to Setosa")
              "The best flower is Setosa."
        })
      }
    )

**Comment by bborgesr** [comment]
It runs for me... It's just that it is immediately replaced by the other one... Here's my console log immediately after opening the app:
```{r}
Listening on http://127.0.0.1:3387
[1] "Change to No Best"
[1] "Change to Setosa"
```
In any case, the way you're going about updating `output$bestText` is not ideal. Was that for this example only? In general, you should only have one `renderText` for that object and use instead some "if else" logic to produce the desired result...

**Comment by DarioS** [comment]
It only executes both functions upon initialisation of the Shiny application, not if the Deselect All button is clicked by the end-user. I'd like to have one reactive function for each input button trigger, because it results in shorter functions and modular code.

**Comment by bborgesr** [comment]
The problem with doing it that way is that that's not how Shiny is meant to be used, so under the hood, what is actually happening is that two `output$bestText` objects are being created and the reference to the first one is immediately lost after the initialization. You can visualize what is happening if you restart your R session and run `options(shiny.reactlog=TRUE)`. Then run your app and click the buttons a few times. Exit the app and run `showReactLog()`.

In any case, I realize this example is a bit contrived for the purposes of illustrating your problem. But another issue is that action buttons are really not the kind of input you want to have for a scenario like this one, which is much more amenable to something like radio buttons. But you can still keep a very similar visual style if you want to (although I think that in this case, the typical radio buttons make a lot more sense than the typical regular buttons).

Here's an example if you want to keep the same look:
```{r}
library(shiny)
library(DT)

shinyApp(
  ui = fluidPage(
    tags$head(
      tags$style(HTML('#choice div label { color: #fff;
                                background-color: #337ab7;
                                border-color: #2e6da4;
                                margin-bottom: 6px;
                                padding: 8px}
                       #choice div label:hover {
                                background-color: #2b618e; 
                                border-color: #224e73; }
                       #choice div label input {
                                display: none;
                       }'))),
    radioButtons("choice", "", 
                 c("Deselect All", "Find Best"),
                 inline = TRUE),
    textOutput("bestText")
  ),
  server = function(input, output, session) {
    
    output$bestText <- renderText({
      choice = input$choice
      if (choice == "Deselect All") noBest()
      else if (choice == "Find Best") setosa()
    })
    
    noBest <- function() {
      print("Change to No Best")  
      "No best flower."
    }
    
    setosa <- function() {
      print("Change to Setosa")
      "The best flower is Setosa."
    }
  }
)
```

As you can see you still have one function for each outcome (although they don't need to be reactives in this case), so your goal of having short functions and modular code is still achieved. It's also good to minimize the number of reactives you have because that results in neater and faster code (compare the `showReactLog()` visualization to the previous one and you'll see this one is a whole lot simpler).

**Comment by jcheng5** [comment]
Barbara is right but if you would like to keep the action buttons, then
Pattern 3 in this article is how you should model it:
http://shiny.rstudio.com/articles/action-buttons.html

**Comment by DarioS** [comment]
Thank you for the example and the design patterns.
