### ISSUE TITLE
Plot is rendered constantly when using invalidateLater() with ggplot2::facet_wrap()

### ISSUE THREAD

**Issue by ottlngr** [rstudio/shiny#1169]
@calligross and I ran into some strange behavior:

When using `ggplot2::facet_wrap()` within Shiny in combination with `shiny::invalidateLater()` the plot is constantly rendered.

A small working example:
```
library(shiny)
library(ggplot2)
data(mtcars)

ui <- shinyUI(
  fluidPage(
      mainPanel(
        plotOutput("Plot")
      )
  )
)

server <- shinyServer(function(input, output) {
   output$Plot <- renderPlot({
     invalidateLater(1000)
     ggplot(mtcars, aes(x = hp, y = mpg, colour = cyl)) + geom_point() + facet_wrap(~hp)
   })
})

shinyApp(ui = ui, server = server)
```

When excluding either `facet_wrap()` or `invalidateLater()` this behaviour disappears.

**Comment by wch** [comment]
That's the expected behavior when you use `invalidateLater`. When you don't use `facet_wrap`, it's not obvious that the plot is redrawing every second, but it is. If you add a line like `print("Rendering plot")` somewhere in the `renderPlot()` call, you'll see that it gets called every second.

The reason that it looks a little different with `facet_wrap` is because the plot takes longer to re-render, and Shiny will grey-out plots that are re-rendering after a little delay.

**Comment by ottlngr** [comment]
Seems quite obvious now... Thanks for clarifying!
