### ISSUE TITLE
observeEvent Instantly Triggered If Widget ID Reused

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1223]
The code example below demonstrate the problem. At first, the event listener of the Process button is only triggered when the button is clicked on. But, when the button is removed (click on Remove It) and reinstated (then click Replace It), the `observeEvent` listener for `doButton` is fired without it ever being clicked on.

So, there is a problem when `removeUI` is used on a widget and `insertUI` is used some time later with a recycled widget ID. Using a new widget ID which is has not previously been present and removed avoids the problem occurring. Aren't fired events 'consumed' once all of their handlers have completed executing ? Should the current behaviour be changed ?

The reason why the observer is destroyed rather than suspended is because the listener's code is different for the restored Process button.

    library(shiny)
    observerList <- list()    
    
    ui = fluidPage(
      actionButton("doButton", "Process"),
      actionButton("removeButton", "Remove It"),
      actionButton("restoreButton", "Replace It")
    )
    
    server = function(input, output)
    {
      observerList <<- c(observerList, observeEvent(input[["doButton"]], {
        print("Processing ...")
      }))
    
      observeEvent(input[["removeButton"]], {
        observerList[[1]][["destroy"]]()
        observerList <<- list()
        removeUI("#doButton")
      })
      
      observeEvent(input[["restoreButton"]], {
        # Restore button.
        insertUI("#removeButton", where = "beforeBegin", ui = actionButton("doButton", "Process"))
        
        # Add new event.
        observerList <<- c(observerList, observeEvent(input[["doButton"]], {
        print("Oops!")
        # Doesn't wait for user mouse click.
      }))
      })      
    }
    
    shinyApp(ui = ui, server = server)

**Comment by wch** [comment]
The reason it behaves this way is because of the ordering of events. The `insertUI` and "oops" observer happen in the same reactive flush cycle, so there's not time between them for the client to get the new doButton and send the reset (0) value to the server before the new "oops" observer is created.

We recently added a new function, `invalidateReactiveValue`, which prevents a reactive value from triggering reactivity until the next flush cycle. For example:

```R
library(shiny)
observerList <- list()    

ui = fluidPage(
  actionButton("doButton", "Process"),
  actionButton("removeButton", "Remove It"),
  actionButton("restoreButton", "Replace It")
)

server = function(input, output)
{
  observerList <<- c(observerList, observeEvent(input[["doButton"]], {
    print("Processing ...")
  }))

  observeEvent(input[["removeButton"]], {
    observerList[[1]][["destroy"]]()
    observerList <<- list()
    removeUI("#doButton")
  })

  observeEvent(input[["restoreButton"]], {
    # Restore button.
    insertUI("#removeButton", where = "beforeBegin", ui = actionButton("doButton", "Process"))

    # Don't have doButton trigger reactivity until next reactive flush cycle
    invalidateReactiveValue(input, "doButton")

    # Add new event.
    observerList <<- c(observerList, observeEvent(input[["doButton"]], {
    print("Oops!")
    # Doesn't wait for user mouse click.
  }))
  })      
}

shinyApp(ui = ui, server = server)
```

Also, there are two other issues with the code that you'd probably want to fix (though they don't affect this specific problem):

* You're only destroying `observerList[[1]]`, but then clearing the entire list. So if there's more than one observer in the list, the others don't get destroyed.
* You probably shouldn't be creating `observerList` outside of the server function, because doing so will mean that all connected sessions will share the same list. It's better to create it inside the server function, so that each session gets its own list.

**Comment by DarioS** [comment]
Thank you, I'll definitely be using `invalidateReactiveValue` in future. The list destruction was simplified from a more complicated example, which was destroying all observers before removing them. Having `observerList` created inside the `server` function is a handy tip.

**Comment by parkerac** [comment]
I am trying to use the invalidateReactiveValue function, but I am getting this error:
"Error in invalidateReactiveValue: could not find function 'invalidateReactiveValue'"
Is it part of a library other than shiny?

**Comment by mangupedia** [comment]
A long standing bug in my app! Fixed it by providing unique IDs for each actionButton, appending a random number as suffix each time the button was re-rendered. `invalidateReactiveValue` wasn't found anywhere.
