### ISSUE TITLE
Dots in IDs

### ISSUE THREAD

**Issue by pascalschulthess** [rstudio/shiny#1250]
Maybe this is a beginner mistake but I just spend 3 days to figure out what was wrong with my app.

I used dots (on occasion even multiple) in IDs to make them more readable. This resulted in conditionalPanels depending on that ID not being executed.

Maybe you could update your help files to tell users what IDs are working and what not.

**Comment by bborgesr** [comment]
If you read the [documentation for `conditionalPanel`](http://shiny.rstudio.com/reference/shiny/latest/conditionalPanel.html), you will notice a **Note** section that addresses this issue specifically, as well as a way around it. Using the same example as the documentation --  if instead of `input$plotType`, you had `input$plot.type`, you could use the following code:

```r

library(shiny)

ui <- fluidPage(
  sidebarPanel(
    selectInput(
      "plot.type", "Plot Type",
      c(Scatter = "scatter",
        Histogram = "hist")),
    
    # Only show this panel if the plot type is a histogram
    conditionalPanel(
      condition = "input['plot.type'] == 'hist'",
      selectInput(
        "breaks", "Breaks",
        c("Sturges",
          "Scott",
          "Freedman-Diaconis",
          "[Custom]" = "custom")),
      
      # Only show this panel if Custom is selected
      conditionalPanel(
        condition = "input.breaks == 'custom'",
        sliderInput("breakCount", "Break Count", min=1, max=1000, value=10)
      )
    )
  )
)


server <- function(input, output, session) {}

shinyApp(ui, server)
```

**Comment by pascalschulthess** [comment]
thanks a lot!
