### ISSUE TITLE
brushedPoints/nearPoints not working with ggplot2 with non-cartesian coordinates

### ISSUE THREAD

**Issue by Raposela** [rstudio/shiny#1280]
Shiny does not seem to cope with non-cartesian coordinates systems in ggplot2 plots.
Below, I provide an example very similar to the plot interaction in [this](http://shiny.rstudio.com/gallery/plot-interaction-selecting-points.html) shiny gallery app where the brush and click events seem to be getting the wrong coordinates when using `map_coord()` instead of `coord_cartesian()`.

This doesn't seem to a be a problem when using base graphics for mapping as someone pointed out to me in this [question](http://stackoverflow.com/questions/38806503/shiny-click-brush-not-working-with-non-cartesian-coordinates) on StackOverflow. If possible, I would prefer to continue using ggplot2 with `coord_map` (and avoid the distorted maps obtained with `coord_cartesian`).
Is this something you would be looking into in the future?

Thanks!

```
library(shiny)
library(ggplot2)
library(dplyr)

map_world <- function(world, mapPoints, xlim, ylim){
  # function to generate ggplot world map
  ggplot() + 
    geom_polygon(data=world, aes(x=long, y=lat, group=group)) +
    geom_point(data=mapPoints, aes(x=Longitude, y=Latitude), color="red") +
    # coord_map messes up the brush select
     coord_map(xlim=xlim, ylim=ylim)
    # coord_cartesian would work but distort the map
    # coord_cartesian(xlim=xlim, ylim=ylim)
}

mapPoints <- data.frame(Longitude=c(-103, -108, -130, -120),
                      Latitude=c(52, 40, 45, 54))
world <- map_data("world")

ui <- fluidPage(
  fluidRow(
    column(width = 6, 
           plotOutput("plot1", height = 300, 
                      click = "plot1_click", brush = "plot1_brush") )
  ),
  fluidRow(
    column(width = 6, 
           h4("Near points"), verbatimTextOutput("click_info") ),
    column(width = 6, 
           h4("Brushed points"), verbatimTextOutput("brush_info") )
  )
)

server <- function(input, output) {
  # output world map
  output$plot1 <- renderPlot({
    map_world(world = world, mapPoints = mapPoints, 
              xlim=c(-180,180), ylim=c(-90,90))
  })
  # output clicked points 
  output$click_info <- renderPrint({
    nearPoints(mapPoints, xvar="Longitude", 
                  yvar="Latitude", input$plot1_click)
  })
  # output brushed points 
  output$brush_info <- renderPrint({
    brushedPoints(mapPoints, xvar="Longitude", 
                  yvar="Latitude", input$plot1_brush)
  })
}

shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
You're right that brushing in Shiny is not adequately supported for non-cartesian coordinate systems in ggplot2. We might, in the future, support this for very few (but commonly used) systems/projections, like polar coordinates and the mercator projection. However, that probably won't happen anytime soon.

In any case, you do have the exact same problem with ggplot2 *and* with base graphics. As [@wch mentioned in the SO post](http://stackoverflow.com/questions/38806503/shiny-click-brush-not-working-with-non-cartesian-coordinates#comment65121445_38876621), the answer given there "is essentially the same as doing the original ggplot version without coord_map, so you might as well use your original code."

So I think if you want brushing, for now, you'll have to tolerate the distortion caused by `coord_cartesian`.

**Comment by Raposela** [comment]
Thanks. The mercator projection was the one I was trying to use.

I'm probably going to stick with base, since it seems to me like base graphics and ggplot2 with cartesian coordinates actually work differently.

In my app, I'm using two plots where the second one is a zoomed-in region of the first one. Base (as suggested in the SO post) seems to be able to properly scale the axes to prevent serious distortion (although the images don't fill out the space as well):
![base](https://cloud.githubusercontent.com/assets/14842133/17569676/3b4500d8-5f41-11e6-9358-20d888f6b99c.png)

While ggplot2 with coord_cartesian will produce something like this:
![ggplot2](https://cloud.githubusercontent.com/assets/14842133/17569677/3b690bfe-5f41-11e6-900b-f63c6addb410.png)

I'm guessing it has something to do with how each of them store the coordinates internally.

**Comment by wch** [comment]
It's stretched in the ggplot2 case is because the available data is scaled to fit the plotting region. I believe that adding `coord_fixed()` should fix it. But note that brushing currently doesn't work on a plot with `coord_fixed()` (see #1121). So if you want to brush the second plot, base graphics is still probably the way to go.

**Comment by Raposela** [comment]
I figured it would be best to use base for my application. Thanks!
