### ISSUE TITLE
Issues with `renderPlot(execOnResize)`

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1331]
1. Behavior seems to be backwards--`execOnResize=FALSE` (the default) re-executes `renderPlot` logic every time
2. When the default is flipped, resizing the plot causes the plot to disappear

**Comment by wch** [comment]
Thanks for catching this! The logic was indeed backward, but I've fixed it in c4cc5b6.

For 2:
* One issue is that the `mclust::.mclust2Dplot` function's `identity` argument got named to `main` in version 5.0: https://github.com/cran/mclust/commit/e2a92beeb9d550f96f815a6a1dc6619449ca3965#diff-1fabbe35cb656d331599a41675c1f3c2L17 . I'll fix that in the example.
* I don't get the plot to disappear. For me, I can increase the width of the plot, but when I make the window narrower, it's as though it doesn't register the change.

**Comment by wch** [comment]
A little more info for future reference:

* In order to work, the `replayPlot()` needs `dev.control(displaylist="enable")` when used with non-interactive devices like `png()`. See https://stat.ethz.ch/pipermail/r-devel/2013-September/067585.html
* If the Cairo package is installed, Shiny uses `CairoPNG()` by default, which does *not* need the call to `dev.control`. This is why I didn't see the problem: I had Cairo installed.
