### ISSUE TITLE
Let modules get at top-level session inputs

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1343]
@cpsievert is working on module support for Plotly's event handling, i.e. hover, click, etc. See https://github.com/ropensci/plotly/pull/700 for his previous attempt.

Plotly events are not raised on individual plots, but on groups of plots (using the "source" argument to bind plots into groups; by default all plots belong to the `"A"` group, but you can set this to whatever). These events are then sent to the server via (basically):

`Shiny.onInputChange("<eventName>-<groupName>", eventValue)`

and accessed on the server via the R function `event_data(eventName, groupName)`, which then calls `getDefaultReactiveDomain()$input[["<eventName>-<groupName>"]]`.

The group names are, rightly, not module-namespaced; it's desirable to allow plotly plots in different modules to be assigned to the same group. However, `getDefaultReactiveDomain()$input` from within a module only gives you access to namespaced input values.

It would be great if we could introduce a way (that is not too tempting for the less module-savvy, who should be sticking to arguments and return values to communicate with the outside world) to get at inputs that are at the global namespace level.

**Comment by wch** [comment]
This was closed by #1344.

**Comment by daattali** [comment]
I also need to use this - I'm creating a package that creates an input that should be tied to the entire session, not to any module. My first thought was to use `session$userData` actually, but because that's not reactive, I looked for a way to make an input accessible by all modules and found this issue.

I saw @jcheng5 's comment in #1344 expressing his concern about people abusing `session$rootScope()`. It seems that it's not documented anywhere except for this issue/PR, but seeing as plotly is using it I hope that means it's stable enough and won't be removed and that I can safely use it as well.

**Comment by jcheng5** [comment]
Can you put a reactive expression in userData?

**Comment by daattali** [comment]
I could, but that leads to some awkward end-user code.

If I use `session$userData$foo <- reactiveVal(TRUE)` in my package and then want the end user to access it, they would need to access `session$userData$foo()`. But that would result in an error until foo is initialized because "attempt to apply non-function" since it'll be NULL.

If you're very uncomfortable with having `session$rootScope()` out in the wild I could tr yto find a workaround

**Comment by jcheng5** [comment]
Oh, I would assume you’d have a user access whatever it is via a friendly function from your package, so that userData is just an implementation detail.

**Comment by daattali** [comment]
I've implemented the desired behaviour with an input, but I'm not able to find the right way to implement it with a **reactive** session$userData. I'll try a little longer.

I think I've hijacked this issue enough though, should this be continued elsewhere? Or even if you don't want to continue this discussion yourself at the moment, is it worthy of its own issue/Community discussion, or should this `rootScope()` be put to rest?

**Comment by jcheng5** [comment]
I just looked at shinybrowser, assuming that's what you're talking about. rootScope does seem like a better solution for this situation, because you don't currently have any module server function to be invoked at the top level.

It's up to @wch et al but I would think rootScope will be around, if you want to make sure of it then test for it in a unit test and publish your package on CRAN 😃

**Comment by daattali** [comment]
Yep, shinybrowser was the reason I was asking - it's a single input that exists for the entire app and I want the user to be able to retrieve it regardless of whether they're in a module or not. It's reassuring to have your blessings to move forward with the current approach, thanks!

I can't tell if that was meant as a joke or not, but it's a very good idea...
