### ISSUE TITLE
Feature request: ability to stop an executing function

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1398]
When your shiny app has some actions that can take a long time, it can often be useful to have a way to stop the function that's running. For example, clicking a "analyze" button that takes 5 minutes, and after a few seconds you realize you wanted to change some parameter, your only solution is to refresh the app.

This question has been asked many times (and got the most attention [here](http://stackoverflow.com/questions/37664197/stop-a-time-consuming-function-on-button-click-shiny) and [here](http://stackoverflow.com/questions/30587883/is-it-possible-to-stop-executing-of-r-code-inside-shiny-without-stopping-the-sh) and [here](http://stackoverflow.com/questions/26600271/r-shiny-how-to-allow-users-to-stop-the-process-and-how-to-stop-the-app-from-ba)). In one of those, there was one suggested answer that offered a workaround of spawning a child process using mcparallel, and the main shiny app has control over killing that process when it wants.

The issue was also discussed on shiny-discuss a few times, and earlier this year @jcheng5 mentioned [there may be a solution to this](https://groups.google.com/forum/#!topic/shiny-discuss/j9-NeG9v5ds) in the future.

I'm not asking for this to happen now, but I wanted there to be an official issue for this so we can track it and know when/if it gets implemented

**Comment by bborgesr** [comment]
@wch, I think this would be a neat feature of the progress indicators. Of course, it could be a standalone button as well...

**Comment by daattali** [comment]
Does anyone have a temporary workaround for achieving this functionality?

**Comment by jcheng5** [comment]
Break the work into multiple steps (like a pipeline or work queue); have each step work on a different "tick"; in between each step, check for cancellation. This sounds complicated but once you figure it out, it can be abstracted into a function. If that doesn't make sense let me know and I can sketch out the code for you. Otherwise, I think this would make a great blog post, hint hint. :)

**Comment by daattali** [comment]
I'm not sure how you mean "different ticks". I imagine this is not what you have in mind: (doesn't work)

```
ui <- fluidPage(
  actionButton("analyze", "Analyze"),
  actionButton("stop", "Stop")
)

server <- function(input, output, session) {
  values <- reactiveValues(STOPIT = FALSE)
  
  observeEvent(input$analyze, {
    lapply(1:5, function(x) {
      if (values$STOPIT) {
        return()
      }
      cat(x)
      Sys.sleep(0.5)
    })
    values$STOPIT <- FALSE
  })
  observeEvent(input$stop, {
    values$STOPIT <- TRUE
  })
}

shinyApp(ui, server)
```

But I trust that what you're suggesting will probably make this code work?

Would you also have a solution for the harder case - where there's a single long-running function that you want to kill while it's still running?

**Comment by jcheng5** [comment]
Sorry, a "tick" is the time between an event being received, (usually an input changing, but could also be an invalidateLater expiring or something) and all the reactive stuff that was going to react to that, finishing. So when I say "do work in a different tick" I mean moving the work outside of the current set of work being done. By spreading out the work across many ticks, you introduce lots of opportunities for things like button clicks to be handled in between the ticks (which is why your code sample doesn't work; the observeEvent that sets `values$STOPIT` will never get a chance to run until your slow task is over, because that slow task is handled entirely inside the same tick).

It's similar to how we often do `setTimeout(..., 0);` or `process.nextTick` in JavaScript to do something "soon but later". Here's more theory about it. https://howtonode.org/understanding-process-next-tick

Here's a sketch of how I would do it in Shiny. It defines a `workQueue` function, into which you pass multiple functions, each one of which is like a stage of a pipeline; the output of each stage is used as the input to the next stage, until we finally reach the end and the final function's output is the output of the overall work queue. Between each stage, the workQueue will check if it should stop executing. When you define a workQueue, you immediately get back a reactive expression; if you call it before the queue has finished, you get essentially `req(FALSE)`, and when the queue finishes it invalidates and starts giving the final answer.
https://gist.github.com/jcheng5/1659aff15904a0c4ffcd4d0c7788f789

This does about 60% of what I'd want such a feature to do; I'd ideally also want it to let you add new stages from within a stage (i.e. performing a search over an unknown amount of data), have an easy way to report progress, let you break early if you find the solution in a middle stage, handle errors properly (report them through the reactive that's returned). But if you need a solution today this should certainly work.

(Credit: Paweł Rucki at Deloitte Poland developed these ideas independently and described them to me at EARL London 2016)

**Comment by jcheng5** [comment]
BTW this does not solve your harder case of killing a single long-running function. I don't know of a way to do that safely (that doesn't involve performing that long-running function call in a forked process--something we will hopefully start looking into next year).

**Comment by daattali** [comment]
My specific use case is for stopping a single long-running function, but this code is very interesting! It's really fun seeing your gists and learning from them...

I also see the timestamp says you wrote that code this morning already, so you didn't actually wait for my answer before sketching out the code :)

**Comment by saralinker** [comment]
Hi, it's been a few years since this post and I've been looking around, but this doesn't seem to be implemented yet. Sorry if I missed it, but are you working on this? It would be extremely useful.

**Comment by sjmgarnier** [comment]
Hi, any progress on or workaround for this issue?

**Comment by jcheng5** [comment]
Yes, this new package by @fellstat should be just the ticket: https://github.com/fellstat/ipc

**Comment by sjmgarnier** [comment]
Thanks @jcheng5, I will check it out.

**Comment by sjmgarnier** [comment]
@jcheng5 The ipc package is interesting, but cancelling a running task won't work on Windows apparently because it requires the multicore package (not available on Windows).

**Comment by vnijs** [comment]
ipc looks great and seems to work on windows as well (with the "future" package)

**Comment by alandipert** [comment]
I'm closing this because `ipc` and `future` packages are now available and they address the original problem.
