### ISSUE TITLE
Willing to help with Tutorial / Web Translation to Portuguese, Spanish, Italian, Dutch...

### ISSUE THREAD

**Issue by pedrokarneiro** [rstudio/shiny#1479]
Dear friends:

Please tell me the best way I may help with the translation to Portuguese (maybe also Italian, Spanish and Dutch) of the Shiny Tutorial available on http://shiny.rstudio.com/

Is there any translation project going on? Is Github the best place to accomplish that?

All the best!

**Comment by bborgesr** [comment]
cc @garrettgman

**Comment by pedrokarneiro** [comment]
Thanks Bárbara!

**Comment by alandipert** [comment]
Hi, thank you for your gracious offer. I'm not aware of any translation projects, but [Community](http://community.rstudio.com/) would be a better place to ask, unless you've since found one.

I'm closing this, but please don't hesitate to comment further or create a new issue if you have another question.
