### ISSUE TITLE
updateSelectInput is Sometimes Immediate But Delayed

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1485]
The inconsistency makes building input forms problematic. The first of the three rule drop-down lists updates immediately, so the second observer has information about the correct table. However, the update in the second observer is delayed, and the third observer tries to access a column name that the table doesn't have. Could all of the `updateSelectInput`s behave consistently (all delayed or all immediate)?

    library(shiny)
    CDs <- data.frame(artist = 1:5, album = 6:10)
    movies <- data.frame(director = LETTERS[1:5], movie = LETTERS[6:10])
    
    ui = shinyUI(
      fluidPage(
        selectInput("tablesLoad", "Choose Table", c("CDs", "movies"),
                    multiple = TRUE, selectize = FALSE, size = 2),
        br(),
        br(),
        selectInput("tableChoice", "From Table", "CDs"),   
        selectInput("columnChoice", "Select Column", "artist"),
        selectInput("valueChoice", "Select Item", 1:5)
      )
    )

    server = shinyServer(function(session, input, output) {
      
      observe({
        input[["tablesLoad"]]
        print("In: Main Table List Observer.")
        updateSelectInput(session, "tableChoice", choices = input[["tablesLoad"]])
      })
      
      observe({
        input[["tableChoice"]]
        print("In: Single Table List Observer.")
        updateSelectInput(session, "columnChoice", choices = colnames(get(input[["tableChoice"]])))
      })
      
      observe({
        input[["columnChoice"]]
        print("In: Column Observer.")
        updateSelectInput(session, "valueChoice", choices = get(input[["tableChoice"]])[, input[["columnChoice"]]])
      })
    })

**Comment by bborgesr** [comment]
Hmm, I don't think there is any inconsistency... This is the expected behavior. In your case, simply, you're "end of the line" observer (the last one in the code) takes a dependency on both `input$tableChoice` *and* `input$columnChoice`. So, when `input$tableChoice` changes, you want only the second observer to be triggered, but the way your code is written, both the second and the third observers are triggered. Since the order in which these execute is arbitrary (when they're triggered at the same time), you end up with the third observer updating so that it, as you said, "tries to access a column name that the table doesn't have". This can be easily fixed with either `isolate()` or, better IMO, using `observeEvent()` instead of `observe()`, since that seems more appropriate for your use case.

Here' the modified code that works as you'd expect:

```r
library(shiny)
CDs <- data.frame(artist = 1:5, album = 6:10)
movies <- data.frame(director = LETTERS[1:5], movie = LETTERS[6:10])

ui = shinyUI(
  fluidPage(
    selectInput("tablesLoad", "Choose Table", c("CDs", "movies"),
                multiple = TRUE, selectize = FALSE, size = 2),
    br(),
    br(),
    selectInput("tableChoice", "From Table", "CDs"),   
    selectInput("columnChoice", "Select Column", "artist"),
    selectInput("valueChoice", "Select Item", 1:5)
  )
)

server = shinyServer(function(session, input, output) {
  
  observeEvent(input[["tablesLoad"]], {
    print("In: Main Table List Observer.")
    updateSelectInput(session, "tableChoice", 
                      choices = input[["tablesLoad"]])
  })
  
  observeEvent(input[["tableChoice"]], {
    print("In: Single Table List Observer.")
    updateSelectInput(session, "columnChoice", 
                      choices = colnames(get(input[["tableChoice"]])))
  })
  
  observeEvent(input[["columnChoice"]], {
    print("In: Column Observer.")
    updateSelectInput(session, "valueChoice", 
                      choices = get(input[["tableChoice"]])[, input[["columnChoice"]]])
  })
})

shinyApp(ui, server)
```

Let me know if there's is something else I'm missing here.

**Comment by DarioS** [comment]
Thanks. I overlooked that dependency which caused the execution order to be arbitrary.
