### ISSUE TITLE
App disconnect when computer sleeps

### ISSUE THREAD

**Issue by jtaveras** [rstudio/shiny#1491]
On shinyapps and presumably shiny server as well, the app disconnects when computer goes to sleep.  The app requires file upload and user input, so requiring the user to reload/re-upload is impractical.  

This happens on Chrome and Safari. Haven't tried others.

I've been told this is outside shiny team's control ... but I'm filing this issue anyway because it's been highly problematic for all the apps I've ever built.  And since corporate laptops usually go to sleep in a matter of minutes, this is not good.  Or we go to meetings, close the laptop and re-open to find the gray screen.

Possibly related (??) -- a few months ago this started showing in my console.  I'm wondering is at all related and might lead to a solution:
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by alandipert** [comment]
Hi, thank you for sharing this report, and sorry it took us so long to respond. Unfortunately, it's a fundamental limitation of Shiny and there is no "easy fix".

If you're using Shiny Server or Shiny Server Pro, one mitigation that comes to mind is that you may modify the [timeout](https://docs.rstudio.com/shiny-server/#application-timeouts) configuration parameters to keep R processes around longer.

I would bet there's a similar configuration option available on Connect, if that's what you're using.

I'm closing this because it's not something we can address in Shiny, but I encourage you to comment further if you have other questions. Alternatively, if you are an RStudio customer, I recommend contacting support@rstudio.com with your concerns. They will certainly be able to help you with your configuration.
