### ISSUE TITLE
`shiny:inputchanged` event not fired for `fileInput`

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1511]
Not sure what the event's value should be, though.

**Comment by wch** [comment]
If we fix this, I'd like it to be in the same release as the testing stuff. I think I added a workaround for this, and if we change it so it does trigger the event, it could change the behavior of the testing code.

**Comment by jcheng5** [comment]
@wch Given that you've been on the other side of this event, is there a value you think would make sense?

**Comment by wch** [comment]
I think we might be able to use the FileList object, and create from it an array of objects, each with `name`, `size`, and `type`.

The FileList object comes is here (I think):
https://github.com/rstudio/shiny/blob/907b9a9862fbcd596b602276b497052d06844a4e/srcjs/input_binding_fileinput.js#L182

Here's info about the FileList and File objects. I think we'd want to create an array of objects, instead of passing the FileList directly:
https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Getting_information_about_selected_file(s)

We'll have to be careful of browser compatibility:
http://caniuse.com/#feat=fileapi
