### ISSUE TITLE
example of reactivePoll implementation with API query

### ISSUE THREAD

**Issue by PhillRob** [rstudio/shiny#1520]
Using updated data in Shiny apps  from a API source is something that most ppl will trying to achieve when visualising socian media trends or survey results. A full example -preferably integrated in an existing app- of how this can be achived using the redactivePoll function.

**Comment by alandipert** [comment]
Thank you for this suggestion, and sorry to take so long to respond to it. Since you posted this, much has been written about [async in Shiny](https://blog.rstudio.com/2018/06/26/shiny-1-1-0/). Joe's CRAN whales case study app demonstrates continuously ingesting data from an external API.

I'm closing because it seems like CRAN whales is the kind of example you were looking for, but if I'm wrong please don't hesitate to elaborate further here or on a new issue.
