### ISSUE TITLE
Some Shiny Inputs don't appear in right place

### ISSUE THREAD

**Issue by carlganz** [rstudio/shiny#1571]
This is somewhat difficult to explain, but I have found that `sliderInput` and `selectInput` have strange behavior that is related to carlganz/rintrojs#16

```{R}
library(shiny)

ui <- fluidPage(
  textInput("one","Test"),
  sliderInput("two","Test",0,1,0),
  selectInput("three","Test",1:3,1),
  radioButtons("four","Test", 1:3)
)
  
server <- function(input, output) { }

shinyApp(ui=ui, server=server)
```

When I open the javascript console and enter:

```{javascript}
document.getElementById("one")
```
It returns the element and when I hover over it text in the console it correctly highlights the element in the page.

![one](http://i.imgur.com/jewZTT3.png)

When I do the same for the `sliderInput` "two", and the `selectInput` "three" it does not highlight the correct area. 

![two](http://i.imgur.com/tO8s8jp.jpg)

![three](http://i.imgur.com/WWSBLl9.jpg)

I do not know what is the cause of this behaviour, but I would greatly appreciate if it could be fixed. 

Kind Regards,
Carl

**Comment by wch** [comment]
You need to use different selectors. Because of the way that some of these inputs are implemented, the DOM element with the specified ID isn't necessarily the thing that's displayed.

If you open the app in a browser like Chrome or Firefox, you should be able to right-click and go to "Inspect Element" to see the DOM structure. For example:
![image](https://cloud.githubusercontent.com/assets/86978/22555767/71ebc3f6-e92a-11e6-8250-0b53b502efdc.png)
