### ISSUE TITLE
validateIcon in actionLink

### ISSUE THREAD

**Issue by haozhu233** [rstudio/shiny#1581]
In the current version of shiny, `actionLink` is defined in the following way
```
actionLink <- function(inputId, label, icon = NULL, ...) {
...codes...
  list(validateIcon(icon), label)
...codes...
}
```

That basically means that everything putting as the third item after `inputId` and `label` will be treated as an `icon` and will need to pass the `validateIcon` check. As a result, when users don't want an icon but forgot to define `icon = NULL`, the `...` gets his chance to be checked by `validateIcon` and in most cases, it will return an error message saying `Error in validateIcon: Invalid icon. Use Shiny's 'icon()' function to generate a valid icon`.

One example is the first issue in giphyr
 https://github.com/haozhu233/giphyr/issues/1
I fixed it by defining `icon = NULL` https://github.com/haozhu233/giphyr/commit/62662d137b1fad390391a5129ca02e5ab377ab83

**Comment by wch** [comment]
That's the correct behavior. Are you expecting something different?

**Comment by haozhu233** [comment]
Hmm, maybe check the icon only when it has been defined?

At least, right now the error message is too confusing. It's kind of difficult to realize that the problem is actually in `actionLink` when you have never thought about putting an icon in the action link but the error message only tells you "Error in validateIcon: Invalid icon. Use Shiny's 'icon()' function to generate a valid icon".

**Comment by daattali** [comment]
@haozhu233 I very often ask the shiny team to improve some documentation that I think is confusing or incomplete (you can search for all my issues as proof!), but I think in this case there's no problem with the doc. I think it's juts a matter reading the docs correctly and understanding the subtleties in how R functions are called. 

`?actionLink` is very clear that the third argument is `icon` and afterwards comes `...`. That means that the third argument is expected to be an icon. By providing something other than an icon, shiny (or R in general) can't know what you mean. That's just how R works and it's correct.

If the function would have been defined as

```
actionLink <- function(inputId, label, ..., icon = NULL) {}
```

then what you tried to do would have worked. For example, the `tabPanel()` function follows that design - it has a first mandatory argument, then `...`, and then more optional arguments. This is a design decision, and there's no objective truth to which one is more correct, but I agree with the shiny team because more often than not you want to use an icon rather than add attributes to the link.

**Comment by haozhu233** [comment]
@daattali thanks for your comment! I guess the reason why I felt it was an issue is that the code I wrote used to work before (yeah I should have paid more attention to the documentation but I guess `validatIcon` wasn't that powerful back in that time?). Also, while I was trying to fix it, since the error message isn't mentioning `actionLink`, it was kind tricky to debug. I guess I should have closed this issue as well. It's not a big deal. :P 

I actually submitted a PR with the same approach by switching the order of `...` and `icon` but @wch convinced me that if we do it now it will break people's code. 

Anyway, thank you both @wch and @daattali for looking into this issue. ;)
