### ISSUE TITLE
Prevent removeModal from resetting actionButton value

### ISSUE THREAD

**Issue by bogdanrau** [rstudio/shiny#1588]
I'm trying to use shiny's default modals (as opposed to shinyBS) to provide users with additional filtering options. The modalDialog includes a few selectInputs that are created using renderUI. The problem I'm encountering is that whenever removeModal() is triggered, all values of the selectInputs and the actionButton are reset. Is there a way to prevent removeModal from resetting things?

Specifically, I need input$actionButton2 to not reset.

```
# Modal Code
observeEvent(input$actionButton1, { # actionButton1 is outside of the modal in the main window
    showModal(modalDialog(
      title = "MODAL TITLE",
      size = "l",
      easyClose = FALSE,
      fluidRow(
        column(width = 12,
               uiOutput("selectInput1"),
               uiOutput("selectInput2"))
       ),
      footer = tagList(
        modalButton("Cancel"),
        actionButton("actionButton2", "ACTION BUTTON 2") # I need this to not reset.
      )
    ))
  })
```

**Comment by bborgesr** [comment]
There isn't currently a way to do this using Shiny modals. However, you can probably get what you want using a reactive value to keep track of the number of times the button has been clicked:

```r
library(shiny)

ui <- fluidPage(actionButton("go", "Go"))

server <- function(input, output, session) {
  rv <- reactiveValues(clicks = 0)
  
  observeEvent(input$count, {
    rv$clicks <- rv$clicks + 1
  })
  
  output$info <- renderText({
    paste("You clicked this button", rv$clicks, "times")
  })
  
  observeEvent(input$go, {
    showModal(modalDialog(
      tagList(
        actionButton("count", "Click me"),
        textOutput("info")
      ),
      footer = modalButton("Cancel", hideOnly = TRUE)
    ))
  })
}

shinyApp(ui, server)
```

Does that accomplish what you want?

We're not sure we're ever going to support what you wanted, since it adds complexity to the mental model of how modals work and we're not sure it's a common enough scenario. But we're not sure at this point.

**Comment by bborgesr** [comment]
To be clear the problem you describe is a little bit off. The values are not reset when you remove the modal. The values are reset when you reopen the modal. Use this app to see what I mean:

```r
library(shiny)

ui <- fluidPage(
  actionButton("go", "Go"),
  textOutput("info")
)

server <- function(input, output, session) {
  output$info <- renderText({
    input$radio
  })
  
  observeEvent(input$go, {
    showModal(modalDialog(
      radioButtons("radio", "Some choices", c(1,2,3)),
      footer = modalButton("Cancel")
      )
    )
  })
}

shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
@jcheng5, Winston and I spoke about this today and whether or not it justifies merging something like [the PR I started](https://github.com/rstudio/shiny/pull/1589). (That PR would need some more work before it was ready to merge). Our consensus for the time being is that this is not a common enough pattern that justifies complicating the mental model. Feel free to share your thoughts, if you think otherwise...

**Comment by bogdanrau** [comment]
Thanks for the comprehensive answer @bborgesr! I did end up using reactive values to keep track of the clicks, so that seems to work just fine. It took a while to sift through all of the different reactive values and event reactives that change around, but I got it to work. Simplifying that process would be beneficial if others have this problem. Otherwise, your suggestion is a great workaround.

**Comment by bborgesr** [comment]
Closing for now. See https://github.com/rstudio/shiny/pull/1589#issuecomment-288122469 for details.
