### ISSUE TITLE
FR: add "once" argument to eventReactive(), similar to the argument in observeEvent().

### ISSUE THREAD

**Issue by johnpauls** [rstudio/shiny#1597]
I would like to request a `once` argument be added to eventReactive, similar to the one used for `observeEvent`. 

My use case is that I have a shiny app where the user has the option to download some data through a web API and map and work with it, but this is optional - they can use other features in the app without doing this. The download and processing of the data is somewhat slow, so ideally there would be a button or checkbox that the user would use to do this. In the server there would be an `eventReactive` which would handle this. However, this download only need to occur once. Since this is supposed to return a `data.frame` this seem more like a reactive than an observer.

**Comment by bborgesr** [comment]
There are a few key differences between observers (which `observeEvent()` belongs to) and reactives (which `eventReactive` belongs to) in Shiny. You already pointed out one of these differences: we should use reactives when we're interested in the return value (in your case, a data.drame) and observers when we're interested in the side effects.

Another difference is that observers are eager and reactives are lazy and cached. So if your event (in `eventReactive`) does not change after the first time, it will only be executed that one time. Therefore, it doesn't make sense to add a `once` argument to `eventReactive`. Because, as long as the input doesn't change, `eventReactive` will also only also execute that one time (no matter how many times it's called, since it caches the return value).

Now, if you want to signal to the user that he shouldn't click the button more than once, you need a different mechanism, like removing the button, or disabling it. Otherwise, it seems misleading to me to allow the button to continue existing on the app and subsequent clicks not producing any change.

Does that make sense to you?

**Comment by johnpauls** [comment]
Yes, that makes sense. In this case the data was mapped and I was hoping to just have a check box that when checked would add the data to the map, but the first time it was checked it would download the data (thus avoiding the extra download control). I think I can achieve the same result by creatively toggling some  controls, but was hoping for other options.

Thanks for the quick reply.

**Comment by bborgesr** [comment]
You can also achieve the same thing by using a flag variable to keep track of whether or not there has been a download yet:

```r
rv <- reactiveValues(downloaded = FALSE)
...
data <- eventReactive({
  input$checkbox
  if (other_data_provided) {
    dat <- ...
  }
  else {
    if (!rv$downloaded) {
      dat <- downloadFunction()
      rv$downloaded <- TRUE
    }
  }
  dat
})
```

**Comment by johnpauls** [comment]
Oh, of course! That's perfect - thanks for replying!
