### ISSUE TITLE
DIV's tabbable class is no longer in use, but still in code

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1615]
Hi, 
last time when `tabbable` class was in use was in [bootstrap 2 ](http://getbootstrap.com/2.3.2/components.html#navs). Not since then. 

However, t[here is 1 occurance of this class in the code. ](https://github.com/rstudio/shiny/search?utf8=%E2%9C%93&q=tabbable&type=).

As can be seen in the documentation for the v3 (and v4 too), now `ul` [is being used.](http://getbootstrap.com/components/#nav-tabs)

A change might be considered.

**Comment by bborgesr** [comment]
There's quite a few people who still use Bootstrap 2 and this is one of the changes that is required in Shiny, so that [rstudio/shinybootstrap2](https://github.com/rstudio/shinybootstrap2) works well. Therefore, we need to keep it for backward compatibility (and it doesn't cause any issues in Bootstrap 3). We may completely stop supporting Bootstrap 2 at some point in the future, but it's not going to be anytime soon.
