### ISSUE TITLE
002-text/ in shinyapps.io and Edge

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1635]
![screen shot 2017-03-30 at 12 58 13 am](https://cloud.githubusercontent.com/assets/6527540/24481707/1cdb1480-14e4-11e7-9ae1-ab466995fe73.png)

The choices don't update until we've chosen a *different* dataset.

**Comment by wch** [comment]
I'm able to reproduce this by doing the following:

* Select the number input.
* Delete the number. It will then show "Error: missing value where TRUE/FALSE needed". (This is as expected.)
* Then if you enter a new number, the table doesn't display.

It turns out that the table is there, but it's not visible for some reason. When I right-click on the space where the table should be and select Inspect Element, it looks like this:

![image](https://cloud.githubusercontent.com/assets/86978/24483278/9808ba0e-14bc-11e7-86ce-36578a8c51f6.png)

Also, if I increase the number of rows, the showcase content moves down. So the table is there, it's just not visible. This is with Edge.

**Comment by wch** [comment]
This is a bug in Edge which happens inconsistently. Hopefully MS will fix it.
