### ISSUE TITLE
Why are last two "|" glyphs in a slider, between 46 and 50 numbers, not shown ?

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1646]
Hi, a question:
Whereas for 1 until 46 those small "|" (next to numbers) glyphs are shown, for 46-50 they are not. Why ? Is it a bug ?

![obrazek](https://cloud.githubusercontent.com/assets/1799661/24589369/68c72238-17d9-11e7-87a0-f34da4b80642.png)

Repro in any browser: https://gallery.shinyapps.io/001-hello/ (tested on Edge + FF)

![obrazek](https://cloud.githubusercontent.com/assets/1799661/24589428/5b1256ca-17da-11e7-8526-8895d1edc255.png)

**Comment by jcheng5** [comment]
Those two spans that you highlighted are actually the marks between 41 and 46--you can see this by deleting them. I haven't looked at the [Ion Range Slider](https://github.com/IonDen/ion.rangeSlider) code, but this looks intentional to me?

**Comment by dmpe** [comment]
Correct. Span that include "small" are intentional. Last few that do not include are bug for me.

But judging by looking at http://ionden.com/a/plugins/ion.rangeSlider/demo.html and http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html where there is only 1 such case where "small" is missing (the one with months/strings in basic) I think we should investigate more and change styling if necessary. 

Broadly speaking, there is no reason why it should be different for the last range not to include those glyphs.

**Comment by jcheng5** [comment]
> Broadly speaking, there is no reason why it should be different for the last range not to include those glyphs.

That's fair.

**Comment by bborgesr** [comment]
> Broadly speaking, there is no reason why it should be different for the last range not to include those glyphs.

Actually, there is a reason for this and I think it makes sense. @jcheng5, @wch, if you disagree, let me know. 

This only happens when the last range cannot be evenly divided into small chunks, which makes sense. If the last range looked like every other range (even though it's actually smaller in these cases), that would be misleading.

Let's go over this case by case.

1. If the stars align, and your slider always divides evenly by the same number, the last range looks, rightfully, like every other range in the slider:

    ```r
    sliderInput("sl1", "Slider 1", 0, 10, 5)
    ```

    <img width="273" alt="slider1" src="https://cloud.githubusercontent.com/assets/6527540/25592739/d0ca6298-2eb1-11e7-9441-e7977adcb6c2.png">

2. If the last range is smaller than the rest (i.e. it doesn't divide evenly by the same number as the other ranges), but it does divide evenly by least two of the smaller subsections, you get the following:

    ```r
    sliderInput("sl2", "Slider 2", 0, 11, 5)
    ```

    <img width="269" alt="slider2" src="https://cloud.githubusercontent.com/assets/6527540/25592880/54de70e2-2eb2-11e7-8715-c7c253b229a7.png">

3. However, there are still plenty of situations (like the slider in https://gallery.shinyapps.io/001-hello/) when the last range does not divide evenly. In these cases, there's nothing that the ion range slider library can do that won't be misleading. So, even though it looks aesthetically annoying (our brains crave symmetry), it's the best way to go in these situations:

    ```r
    sliderInput("sl3", "Slider 3", 0, 17, 5)
    ```

    <img width="273" alt="slider3" src="https://cloud.githubusercontent.com/assets/6527540/25592955/b20f376a-2eb2-11e7-8680-3889f38fd8a2.png">
