### ISSUE TITLE
reset value of actionButton?

### ISSUE THREAD

**Issue by stratosfmos** [rstudio/shiny#167]
can an actionbutton be reseted to 0 inside server.R?
let's say i have actionButton("b1","button1"). what could be the code for reseting the action button to 0?

**Comment by dhassouni** [comment]
I feel as though a simple case has been overlooked (and forgive me if I somehow missed this example in the above thread). It is very common to have a set of checkboxes with one button to check all, and another to uncheck all. For example, the desired code from server.R below. While I can conceive of a few ways to get around this, it doesn't mean that you should not be able to reset to 0. The reason the code below does not work is that after selecting and deselecting once, both input action button values are greater than 0. I am not deriving anything meaningful from the increment counter other than "the special value of 0" as stated above. Thoughts on this example?

  observe({
    if (input$uncheckAll > 0 ) {
      updateCheckboxGroupInput(session = session, inputId = "test", choices = c(1,2,3), selected = NULL)
    }
    
    if (input$checkAll > 0 ) {
      updateCheckboxGroupInput(session = session, inputId = "test", choices = c(1,2,3), selected = c(1,2,3))
    }
  })

**Comment by jcheng5** [comment]
These just need to be two separate observers.

```r
observe({
  if (input$uncheckAll > 0 ) {
    updateCheckboxGroupInput(session = session, inputId = "test", choices = c(1,2,3), selected = NULL)
  }
})
observe({
  if (input$checkAll > 0 ) {
    updateCheckboxGroupInput(session = session, inputId = "test", choices = c(1,2,3), selected = c(1,2,3))
  }
})
```

Actually with recent versions of Shiny it's nicer to use observeEvent, and also you don't need to provide the choices if they're not changing:

```r
observeEvent(input$uncheckAll, {
  updateCheckboxGroupInput(session, "test", selected = NULL)
})
observeEvent(input$checkAll, {
    updateCheckboxGroupInput(session, "test", selected = c(1,2,3))
})
```

**Comment by dhassouni** [comment]
Thanks much, this actually makes sense and I stand corrected. I still don't quite understand the resistance to not being able to reset to zero - it doesn't seem to inherently promote any bad coding practices, and just because something can be done one way doesn't mean there may not be a better or more intuitive way. Anyhow, you have come up with elegant solutions for most of the problems here, so for now this will definitely suffice. Also, thank you for the advice about observeEvent(). I wasn't even aware of this new construct (I'm relatively new to shiny, and few of the examples in the gallery seem to use some of the newer functionality I am coming across).

**Comment by dhassouni** [comment]
quick side note. It seems to require that I provide the choices even though they aren't changing. The code works fine with the choices there, but is unresponsive without the choices.

**Comment by jcheng5** [comment]
> I still don't quite understand the resistance to not being able to reset to zero - it doesn't seem to inherently promote any bad coding practices

It absolutely, positively does promote bad coding practices. Just look at all of the code examples in this thread (through no fault of the users, of course--we just haven't done a good enough job with education). The action button being clicked should be thought of as a discrete event, not a value. The special `0` value is just a workaround to prevent the code from thinking that the button is clicked at startup. It's _the fact that a number has changed_ that is the relevant signal here, not _the value that the number happens to be_.

Shiny's reactivity system wasn't designed for imperative programming--and pushing a button is, by nature, imperative. It was a stroke of pure luck that I came up with the observe/isolate idiom that allows actionButtons to work so nicely. It is a very narrow pattern that has very broad applications; if you stay within the pattern you can accomplish almost anything safely, if you stray outside the pattern your program is suddenly very difficult to reason about AND probably also doesn't accomplish what you originally wanted it to.

I think part of the reason is that the observe/isolate examples don't LOOK like anything particularly special relative to other reactive code. I'm hoping that observeEvent will help make the intent clearer, and make it less tempting to abuse.

**Comment by dhassouni** [comment]
I still disagree with this premise. There is a difference between promoting bad coding practices and people using code in the wrong way. Almost any code construct can be used inappropriately. I think the root of this disagreement may be the implementation of the counter for the actionButton, which I might argue is not intuitive based on many older examples I've found using observe. I will readily grant that that the interface for observeEvent is much cleaner and will naturally obfuscate the value associated with the actionButton. In any case, I do very much thank you for your help. If you want to continue the conversation about promotion of bad coding practices, feel free to email me as I don't want this thread to get too far off topic. Of course, if it relates to the examples and use cases, definitely post here. Thanks again.

**Comment by dhassouni** [comment]
quick side note. In my uncheckAll example, I used selected = NULL within updateCheckboxGroupInput. According to the documentation for this method, any arguments with a NULL value will be ignored. Hence, for those looking at this example, you must use selected = c('') or some such equivalent.

**Comment by MartinNowack** [comment]
Hi, i think there is currently one problem with the approach: if you deleting and adding the button with the same ID again, the `input$ID` might still exist and therefore is not null anymore, therefore the function gets executed immediately when added, I worked around that issue by extending the observeEvent function the following way (in a nutshell: I get the old value first and then compare with the new event):

```
observeEvent2 <- function (eventExpr, handlerExpr, event.env = parent.frame(),
          event.quoted = FALSE, handler.env = parent.frame(), handler.quoted = FALSE,
          label = NULL, suspended = FALSE, priority = 0, domain = getDefaultReactiveDomain(),
          autoDestroy = TRUE, ignoreNULL = TRUE)
{
  eventFunc <- exprToFunction(eventExpr, event.env, event.quoted)
  if (is.null(label))
    label <- sprintf("observeEvent(%s)", paste(deparse(body(eventFunc)),
                                               collapse = "\n"))
  handlerFunc <- exprToFunction(handlerExpr, handler.env,
                                handler.quoted)

  oldValue <- isolate(eventFunc())

  invisible(observe({
    e <- eventFunc()
    if (ignoreNULL && (isNullEvent(e) || (!is.null(oldValue) && e == oldValue))) {
      return()
    }
    isolate(handlerFunc())
  }, label = label, suspended = suspended, priority = priority,
  domain = domain, autoDestroy = TRUE))
}
```

It's still not perfect but works much better.

**Comment by nhpackard** [comment]
I, too, find myself wanting to reset an action button.  I don't find the following functionality in the thread so far, so I'll try it out for Joe...

It has to do with using a conditional panel that looks at an action button value for its condition (this is in ui.R, *not* server.R).

In a sidePanel I have something like:
```
sidePanel(
...
actionButton(doit,"Configure this variable")
...
)
```
then in a main panel I have something like
```
mainPanel(
   ...
   # for action button not pushed:
   conditionalPanel(condition="input.doit == 0 & input.tabs==...",
                                ...),
   ...
   # for action button pushed:
   conditionalPanel(condition="input.doit > 0 & input.tabs==...",
                                ...),
```
Now, at some point (maybe triggered by another action button, I would like to reset input.doit and re-display the first conditional panel, have the user re-specify inputs there, etc.  Seems like it would be quite natural to have something like ```updateActionButton()``` over in server.R to get me back to my first conditional panel.

I would be very happy to hear the 'right and proper' way to do this, given that ```updateActionButton()``` does not exist.

**Comment by irJoostvanVeen** [comment]
To get a 0 / 1 actionbutton without resetting:

    attr(input, "readonly") <- FALSE
    input$ActionButtonMemory <- 0
    observe({
      if(length(input$ActionButton)>0){
      if((input$ActionButton-input$ActionButtonMemory)>0){
        input$ActionButtonMemory<- input$ActionButton # Equalize
        # DO YOUR THING HERE
      }}
    })

**Comment by mikebirdgeneau** [comment]
I stumbled upon this issue, while looking for a way to write a single handler that can respond to a large number of individual action buttons. Here's an example of what I was trying to do:

```r
save_settings <- function()
  {
    xs <- seq(1,100,by=1)
    result<-lapply(xs,function(x){
      observeEvent(input[[paste0(x,"_save")]], {
            if(!(input[[paste0(x,"_save")]]==0)){
		# Save something for this value of x.
		#input[[paste0(x,"_save")]] <- 0 # Could be a nice place to be able to reset to 0.
            }
          }
        }
        message(paste0(x,"_save: ",input[[paste0(x,"_save")]]))
      })
      input[[paste0(x,"_save")]]
    })
    return(result)
  }
})
```

I could see the 'reset' to zero being useful in this case, but perhaps there's a better way of doing this.
Has anyone done something similar?

**Comment by jcheng5** [comment]
@mikebirdgeneau That's absolutely not necessary in this case. This is all you need to do:

```r
save_settings <- function()
  {
    xs <- seq(1,100,by=1)
    lapply(xs,function(x){
      observeEvent(input[[paste0(x,"_save")]], {
        # Save something for this value of x.
      })
    })
  }
})
```

**Comment by mikebirdgeneau** [comment]
@jcheng5 thanks - I'll give that a go! Appreciate the quick response. Cheers.

**Comment by dcenergy-reeve** [comment]
I can see one argument for resetting an actionButton that I haven't seen mentioned here (apologies if it has been mentioned, and I missed it). I'd like to be able to copy the URL from the browser in which my shiny app is running, send it to somebody else, and have them be able to load the same page with all of the inputs automatically populated from the URL. I do not, however, want the actions executed by an actionButton to run automatically.  (One example of this might be a page used to visualize data, with an actionButton that will trigger the writing of that data to a particular file.  I want to be able to send a visualization of that data to somebody by sending them the URL to my page, but they may not want to write it to file upon page load).  

By default shiny can save/load all of its input variables to/from the URL, which is great most of the time, but can cause issues when it loads actionButtons with values > 0.  In those cases, as in the example above, it will think that the user has clicked the actionButton when in reality he/she has not yet done so.  

This is a case in which the value of the actionButton does not matter, but the fact that it is not zero is important.  Thanks for your help!

**Comment by jcheng5** [comment]
> By default shiny can save/load all of its input variables to/from the URL

That's not a built-in feature of Shiny; is there a specific package you're using to give you that functionality?

**Comment by dcenergy-reeve** [comment]
You're right - this is part of a separate package (that is not yet publicly available).  Thank you for the quick response.

**Comment by Miguel-Arribas** [comment]
hello jcheng5.

I have a case of needing a button to be reset; I am writing an optimizer, that
1.- Load an external data file
2.- Does the optimization (which can be run several times, adjusting some parameters)
3.- Shows the results
4.- Allows downloading the results (when
5.- The user can upload a new data set and start again the process

I have a download link, which is hidden if the optimization has not been run; as soon as the optimization is executed, the download link is made visible, using conditionalPanel.
If the user loads a new data set, the download link should be invisible again, until the optimization is run (I don´t want the user to be able to do something that makes no sense, like trying to download non existing results!).
But conditionalPanel access the value of the button using javascript. So the first time the program is run, the download linj is hidden (the button value is 0), but if after doing one optimization with one data set, a new data set is loaded (invalidating the precious results),then  the conditional panel remains visible (since the button cannot be reset to 0) allowing the downloading of an empty solution, which is something that, as I said, I want to avoid.

Here is the line:

    conditionalPanel("input.optimiza > 0",
                     wellPanel(downloadLink(outputId="descarga", label="Descargar solución"))))

As you can guess, the button to run the optimization is named "optimiza".

So the problem I have is that I don´t know how to make the conditional panel to hide when a new data set is loaded, since its visibility depends on the button´s value and that is checked in javascript, not in R...

Am I missing something? Is there a way to make javascript aware of other values existing in the R code? Just checking that the data structure to be returned is NULL would do fine.

Thanks a lot,

Miguel

**Comment by ideamotor** [comment]
@nhpackard does [`shinyjs`](https://github.com/daattali/shinyjs) help you accomplish what you need? Here's a minimal example of `toggle`:

```r
library(shiny);library(shinyjs)

shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(
        actionButton("showPanel","Show Panel!")
      ),
      mainPanel(
        useShinyjs(),
        absolutePanel(id = "panel", class = "panel panel-default",
                      style = "z-index:100; display: none;",
                      
                      div(style="margin:10px;",
                          h3("Hello World")
                      )
        )
      )
    )
  ),
  server = function(input, output) {
    
    observeEvent(input$showPanel,{
      toggle("panel")
    }) 
    
  }
)
```

It's not using `conditionalPanel` but I think it's cleaner to keep the logic on the server-side. Upon a button press you could have it `updateX` for each of the inputs, and run the analysis, etc.

**Comment by abhijeetgosavi** [comment]
Hi Joe,

I stuck around the similar problem related to the resetting of action button. My problem is  

On UI : I have 1 drag down which contains 2 values "Suntrust Bank" and "Huntington Bank". And below which i have 3 action buttons for 3 task : process data, download processed data and upload processed data.

When i select Suntrust first time, below three action buttons are not executed unless i pressed them. However, whenever i select Huntington, below 3 buttons executed automatically (buttons were not pressed) . 

Could you please help me out how to resolve this ? Ideally i would like to have : when i change SunTrust to Huntington or and again Huntington to SunTrust, the below 3 buttons (process, download and upload) should not work unless and until i press them.

Thanks in advance !!

**Comment by jcheng5** [comment]
Like this:

observeEvent(input$process, {
    # processing code here
})
observeEvent(input$download, {
    # download code here
})
observeEvent(input$upload, {
    # upload code here
})

**Comment by abhijeetgosavi** [comment]
Yes, exactly. Let me paste my server.r code here
Server.r 

library(data.table)
library(shiny)
library(stats)

shinyServer(function(input, output, session) {
 
datasetInput <- reactive({
    switch(input$Select,
           "SunHE" = heloc.comp.rate, 
           "HunHE" = heloc.comp.rate1
          )
  })
  
 observeEvent(input$goButton, {
     output$MyData <- renderDataTable({
	   datasetInput()
})

})


observeEvent(input$Click, {
    output$fill <- renderUI({ 
	write.csv(datasetInput(), file.loc,row.names=FALSE)
		                    }) 

})


observeEvent(input$Submit, {
    output$fill <- renderUI({ 
	write.csv(datasetInput(), Up.file.loc,row.names=FALSE)
		                    }) 

})
 



	   

})


ui.r 

shinyUI(fluidPage(
  titlePanel("Generate Competitor rate GI file"),
  
  sidebarLayout(
  
  
    sidebarPanel(
	
	 selectInput("Select","Select Customer:", 
						list(SunHE = "SunHE", HunHE  = "HunHE")
						) ,
						
     actionButton("goButton", "Generate GI File")  ,
	 
	 actionButton("Click", "Download GI File")  ,
	 
	 actionButton("Submit", "Upload GI File"),
	 
	 
	uiOutput("fill") ,
	
	uiOutput("Upload")
	         )
       
        ,
		  
	mainPanel(
	  h3(textOutput("caption")),
      dataTableOutput("MyData")
             )
			 )

    

))

When i'm changing bank from Suntrust to Huntington from Drag n Down, below 3 actions buttons are executing automatically.

**Comment by jcheng5** [comment]
Can we take the discussion over to [shiny-discuss](https://groups.google.com/forum/#!forum/shiny-discuss)? Thanks.

**Comment by abhijeetgosavi** [comment]
I have created new discussion - Resetting action buttons. Kindly have a look and let me know if you have any inputs.

Thanks.

**Comment by gregorbj** [comment]
I'm interested in resetting the appearance of an actionButton. I'd like the button to have the appearance of the clicked state (i.e. grey) when the click event occurs and then return to the unclicked appearance (i.e. white) when the click event ends. In my case, I'm using the button for the user to save a file. The button can be used multiple times during a session to save files. The changed appearance of the button after the first time it is clicked suggests to the user that the functionality of the button has changed. Is there any way to do what I want to do?

**Comment by subhashjaini** [comment]
was this ever resolved or did they just keep insisting that nobody needed it? I need it! :)

**Comment by resurrexi** [comment]
I was wondering if there was a resolution to this as well. I need the actionButton reset because I have a conditionalPanel that depends on whether the button is clicked, but it has to be reset whenever the user switches options in my dropdown menu.

**Comment by subhashjaini** [comment]
I think you can use this code to determine if it's odd or even

 x %% 2 == 0

does that work?

**Comment by johnpauls** [comment]
In general what you need is `reactiveValue` that is tied to the button. Every the the button is clicked it adds one to the value, and that value is used to trigger observers etc. The, when the user does the stuff that resets things, just reset the `reactiveValue` to 0, the value tied to the button can stay as it is.

**Comment by resurrexi** [comment]
I ended up using shinyjs to create a hidden checkboxInput that would be toggled by several observers. Then, in my UI, I set up a conditionalPanel to check for the T/F value from the checkboxInput, and display the button if TRUE.

**Comment by RobertMyles** [comment]
https://groups.google.com/forum/#!topic/shiny-discuss/9gJR5aCBNfE

**Comment by thomaszwagerman** [comment]
I am experiencing a similar problem when using multiple embedded observeEvents, where a reset of the actionButton value would be useful.

For example:
---
observeEvent(input$button1, { 
      #a modal with button2 pops up, but should not trigger button2 until clicked
      actionButton("button2", "Button 2")

         observeEvent(input$button2, {
          #modal number 2 pops up
          #some action
          removeModal()
          })
})
---
This structure works perfectly in the first instance. However, when triggering button1 for the second time, it skips straight to observeEvent button2, without input$button2 having been provided. 

A bit more investigating with browser() showed that input$button2 retains its value despite closing the modal and triggering input$button1 again, UNLESS a modalButton is used to dismiss the modal instead of removeModal().

A hard reset of the button in this case would be useful in conjunction with removeModal(), to prevent the app user from having to click a "Dismiss"-style modalButton every time.

Previously I have used updateRadioButtons to reset inputs for a selection menu, but this doesn't work the same with actionButtons.

I haven't found a suitable solution above, but I very much hope to be corrected by someone!

Thanks a lot.

**Comment by sa-ccr** [comment]
that's an obviously useful feature - is there any piece of reasoning why this is not fixed???

**Comment by TjebsC** [comment]
> I am experiencing a similar problem when using multiple embedded observeEvents, where a reset of the actionButton value would be useful.
> 
> ## For example:
> ```
>      observeEvent(input$button1, { 
>      #a modal with button2 pops up, but should not trigger button2 until clicked
>      actionButton("button2", "Button 2")
> 
>      observeEvent(input$button2, {
>       #modal number 2 pops up
>       #some action
>       removeModal()
>       })
>  })
> ```
> 
> This structure works perfectly in the first instance. However, when triggering button1 for the second time, it skips straight to observeEvent button2, without input$button2 having been provided.
> 
> A bit more investigating with browser() showed that input$button2 retains its value despite closing the modal and triggering input$button1 again, UNLESS a modalButton is used to dismiss the modal instead of removeModal().
> 
> A hard reset of the button in this case would be useful in conjunction with removeModal(), to prevent the app user from having to click a "Dismiss"-style modalButton every time.
> 
> Previously I have used updateRadioButtons to reset inputs for a selection menu, but this doesn't work the same with actionButtons.
> 
> I haven't found a suitable solution above, but I very much hope to be corrected by someone!
> 
> Thanks a lot.

I'm having the same issue which is really annoying when having two modals back-to-back where the first one shows missing data for a selection. Could not find suitable workaround either

**Comment by TjebsC** [comment]
> I'm having the same issue which is really annoying when having two modals back-to-back where the first one shows missing data for a selection. Could not find suitable workaround either

Ok. For future reference to people having the same problem as me. The easy solution for me was to include `shinyjs::onclick()` instead of observeEvent. Then it works every time. A short snippet of my code:

`
observeEvent(input$change, {
showModal(modalDialog(title = "some_title",
                          renderTable({#my data}),
              easyClose = FALSE,
              footer = tagList(actionButton("ok", "Ok"), shinyjs::useShinyjs())))

    shinyjs::onclick("ok", {
      removeModal()

      # My other modal is in a module. Should work outside as well
      callModule(pop_up, "dato", dato_tabell = reactive({pop_up_data()}))
    })
}
)
`

Sorry for terrible formatting. Hope this helps somebody

**Comment by jcheng5** [comment]
@TjebsC For future reference, you can work around this by giving `observeEvent(input$button2, ...)` an additional argument `ignoreInit=TRUE`. What this tells `observeEvent` is, "no matter what the current value of `input$button2` is, don't execute this observer until the NEXT time `input$button2` is updated". Not very intuitive, but I think it should work.

**Comment by MartinY96** [comment]
ok, I am a same problem.

        #SAVE
        observeEvent(input$Guardar,{
        req(input$Guardar)
            
           input$Guardar
           isolate({
            
                    archivo <- paste0("D:/",
                                      input$Fundo, "-", input$Parcela, " ", 
                                      input$Lote, " ", input$Lado,".pdf")
                    
                    pdf(archivo, width = 18, height = 11 )
                    
                    Graph
                    
                    dev.off()
                    
                    shinyalert(title = "Descarga Correcta", type = "success")
                    

            })

I have this code inside an observeEvent to save every time I make changes to a map, the problem is that as soon as a parameter change is saved, I mean when I click on the save button, and it doesn't stop working; I would like it to only save when I click.

**Comment by philibe** [comment]
A method written after I've read this issue and the last message of @jcheng5 about  `observeEvent(,{},ignoreInit=TRUE)`:
```
react <- reactiveValues(
  LoginBtnSubmit=0,
  LoginAutorisation =FALSE 
)

observeEvent(input$LoginBtnSubmit,{
  # https://github.com/rstudio/shiny/issues/167 "reset value of actionButton?"
  react$LoginBtnSubmit=1
}, ignoreInit=TRUE)  

Login.verif.react <-  reactive({
  res_before<-isolate(react$LoginAutorisation)
  
  if (DescTools::Coalesce(react$LoginBtnSubmit,0)>0) {
    react$LoginBtnSubmit=0
    if (my_verification_else_where)
    {
      res<-TRUE
      react$LoginAutorisation<-res
    } else {
      res<-FALSE
      react$LoginAutorisation<-res
    }
  } else {
    res<-res_before
  }
  res
  
})



Table.react <- reactive ({
  validate(
    need(Login.verif.react()==TRUE , "Forbidden Access ! ")
  )
  data_frame_for_renderDataTable
})
```
