### ISSUE TITLE
Problem with observer and removeUI : last in line observes too late and is not updated

### ISSUE THREAD

**Issue by mkdatak** [rstudio/shiny#1679]
I am trying to build  a dynamic form where the user can add some criteria (via an actionButton) and select values for those criteria.  When he's done selecting he may lauch some computation.
Every criteria may be removed via a 'delete' button. 

It works quite fine for all except for the last component inserted that does not react to the related remove button.
The last component is removed only when the "Add criteria" button is clicked. 

I'm using  an observeEvent with an   renderUI  to build components : 

In server.R 

```r    
observeEvent(input$go, {

    output$ui <- renderUI({

        rows <- lapply(names(components),buildComponent)

        res = do.call(fluidRow, rows)

    })

    makeObservers()

  })


```
makeObservers  creates an observeEvent closure for every component : 

```r

makeObservers <- eventReactive(input$go, {

    IDs <- names(components) 

    new_ind <- !(IDs %in% vals$y)    

    res <- lapply(IDs[new_ind], function (x) {

      observeEvent(input[[paste0("rmv", x)]], {

        if(components[[x]] == "Main1") removeComponent(x)
      })
    })
  } , ignoreNULL = F, ignoreInit = F)
```

Please find attached a working example. 

<details>
  <summary>My code</summary>

  ```r
 library(shiny)
library(shinythemes)

criterias <- c("Criteria 1", "Criteria 2", "Criteria 3", "Criteria 4")
components <<- list()
counter <<- 0

buildComponent <- function(val) {
  idselect = paste0("select", val)
  idremove <- paste0("rmv", val)
  div(
    selectInput(idselect, "criteria :", criterias, criterias[0]),
    actionButton(idremove, paste0("X", val),icon = icon("remove"), size = "small")
  )
}

removeComponent <- function(x) {
  print(paste0("Removing" ,x))
  xpath1 = paste0("div:has(> #select", x ,")" )
  xpath2 = paste0("div:has(> #rmv", x ,")" )
  removeUI(
    selector = xpath1, multiple = T#, immediate=T
  )
  removeUI(
    selector = xpath2, multiple = T#, immediate=T
  )
  components[[as.character(x)]] <<- NULL
}

ui <- shinyUI(fluidPage(
                        sidebarPanel(
                          actionButton("go", "Criteria", icon = icon("plus-circle"), 
                                       size = "small"),
                          uiOutput("ui")
                        ),
                        mainPanel(
                          actionButton("activate", "show cpts"),
                          textOutput('show_components')
                        )
) )

server <- shinyServer(function(input, output, session) {
  # Keep track of which observer has been already created
  vals <- reactiveValues(y = NULL)
  
  makeObservers <- eventReactive(input$go, {
    IDs <- names(components) 
    new_ind <- !(IDs %in% vals$y)
    print("new_ind")
    print(IDs[new_ind])
    # update reactive values
    vals$y <- names(components) 
    res <- lapply(IDs[new_ind], function (x) {
      observeEvent(input[[paste0("rmv", x)]], {
        print(paste0("rmv", x))
        print(components[[x]])
        if(components[[x]] == "Main1") removeComponent(x)
      })
    })
  } , ignoreNULL = F, ignoreInit = F)
  
  observeEvent(input$go, {
    output$ui <- renderUI({
      print(counter)
      counter <<- counter + 1
        components[[as.character(counter)]] <<- "Main1"
        print("adding component : ")
        print(paste0(names(components),collapse = ";"))
        rows <- lapply(names(components),buildComponent)
        res = do.call(fluidRow, rows)
    })
    makeObservers()
  })
  
  observeEvent(input$activate, {
    output$show_components <- renderPrint({
      components
    })
  })
})

shinyApp(ui, server)
  ```

</details>

I'd be willing help to help if you can point me to the relevant sections of js ...

**Comment by bborgesr** [comment]
I didn't have time to go through your code in detail, but it seems to me like you're not going about this in the right way. You seem to be using `renderUI` inside an `observeEvent` to insert new elements. This is the wrong way to go about it, since the number of elements you want to add is unbounded (and it's also not in line with the general idea of reactive programming that `renderUI` follows). I'm a little confused why you are using `removeUI` but *not* `insertUI`, which seems to be  much better fit, when you have an unbounded number of elements to insert, all independent of one another.

Here's an example app that seems to be doing something more in the lines of what you want (you can modify it, so that you have a `selectInput` + an `actionButton`, as you seem to want, instead of simple text + an `actionButton`). This example arose from [a similar issue a few months ago](https://github.com/rstudio/shiny/issues/1486):

```r
library(shiny)

ui <- fluidPage(
  textInput("divID", "Enter an ID for the custom area:", ""),
  helpText("Leave the text input blank for automatically unique IDs."),
  actionButton("isrt", "Add a button"), 
  tags$div(id = "placeholder")
)

server <- function(input, output, session) {
  rv <- reactiveValues()
  
  # take a dependency on `isrt` button
  observeEvent(input$isrt, {
    
    # handle the case when user does not provide ID
    divID <- if (input$divID == "") gsub("\\.", "", format(Sys.time(), "%H%M%OS3")) 
    else input$divID
    btnID <- paste0(divID, "rmv")
    
    # only create button if there is none
    if (is.null(rv[[divID]])) {
      
      insertUI(
        selector = "#placeholder",
        ui = tags$div(id = divID, 
          paste0("Welcome, ", divID, "!"),
          actionButton(btnID, "Remove this area",  a
            class = "pull-right btn btn-danger"),
          style = "background-color: #e0cda7;
          height: 50px;
          margin: 10px;
          padding: 5px;
          display: block;
          border-radius: 5px;
          border: 2px solid #2a334f;"
        )
      )
      
      # make a note of the ID of this section, so that it is not repeated accidentally
      rv[[divID]] <- TRUE
      print("created")
      
      # create a listener on the newly-created button that will
      # remove it from the app when clicked
      observeEvent(input[[btnID]], {
        removeUI(selector = paste0("#", divID))
        
        rv[[divID]] <- NULL
        print("destroyed")
        
      }, ignoreInit = TRUE, once = TRUE)
      
      # otherwise, print a message to the console
    } else {
      message("The button has already been created!")
    }
  })
}

shinyApp(ui = ui, server = server)
```

**Let me know if this is applicable to your use case, so we can close this issue.**

----

P.S: We prefer if you just copy-paste your minimal reproducible exmaple directly (instead of zipping it up). If you're worried it's too big (though it shouldn't be bigger than the above, I think), you can use this directly in your post:

````
<details>
  <summary>My reprex</summary>

  ```r
  library(shiny)
  ui <- fluidPage()
  server <- function(input, output, session) {}
  shinyApp(ui, server)
  ```

</details>
````

which results in this:

<details>
  <summary>My reprex</summary>

  ```r
  library(shiny)
  ui <- fluidPage()
  server <- function(input, output, session) {}
  shinyApp(ui, server)
  ```

</details>

**Comment by mkdatak** [comment]
Many thanks  you for your help : 

* i've edited my post to get it a little more readable.

* your suggestion does help and : using insertUI, I'm getting the expected behaviour. 

Initially I've started from an example and did not think about using insertUI : I haven't digged out  enough and did't get that insertUI is incremental. 

* Nevertheless, I would think my question is still valid : the code behaviour is not the expected one the last inserted component/widget is not removed until the  "Add criteria" button is clicked.
We should be able to point out the error. 

* Could you give me  (or point me to)  more information regarding you remark ? :  it's also not in line with the general idea of reactive programming that renderUI follows

Thanks again

**Comment by bborgesr** [comment]
Great, glad you got the behavior you were looking for!

I didn't look at your app long enough to understand exactly how it was supposed to work. Since it seemed to me that you were using an anti-pattern, I thought the best way to help was to show you the right pattern. By anti-pattern, I mean something that may even work, but it's the wrong way to go about something in a Shiny app, and it may definitely cause problems (especially if you're mixing up reactivity with things like `insertUI` and `removeUI`, which follow a different programming paradigm).

I'll try to come back to this:

> the code behaviour is not the expected one the last inserted component/widget is not removed until the "Add criteria" button is clicked. We should be able to point out the error.

when I have some time, but I'd recommend that you stick with `insertUI` for this use case, if it gives you all you were looking for.

As for what I meant by "not in line with the general idea of reactive programming that `renderUI` follows," there were a couple of red flags in your code that alerted me and that are usually considered anti-patterns in Shiny:

- you are using `renderUI` inside an `observeEvent`: that's the right pattern for `insertUI` and `removeUI`, but not for `renderUI`.

- you want to create an unbounded number of things: the right pattern for this is always `insertUI` (caveat: it's usually a good idea to avoid saying "always" and "never" in software development because there are often edge cases, but as of today, I don't think I've found any for this particular pattern).

If this sounds confusing (and even if it doesn't), **I'd really recommend that you [watch my 20min talk at rstudio::conf](https://www.rstudio.com/resources/videos/dynamic-shiny-interfaces/) earlier this year, since it's exactly the answer to this question (when to use `renderUI` and `insertUI` and how these are different).**

Finally, in order to have a better idea of what is reactivity in Shiny, what are patterns and anti-patterns and, in general, a high level view of these concepts, I'd also strongly recommend that you watch [Joe's talk on Effective Reactive Programming](https://www.rstudio.com/resources/videos/effective-reactive-programming/) -- it's divided in two parts, roughly 1h each, but I think it's well worth the time if you want to master Shiny.

**Comment by mkdatak** [comment]
Thank you for your comments and efforts
