### ISSUE TITLE
Expose a shiny:invalidated JS event (as shiny:recalculating can fire much later than invalidation)

### ISSUE THREAD

**Issue by andrewsali** [rstudio/shiny#1688]
Hi,

It appears that there is a mismatch between when the `shiny:recalculating` event is triggered vs when the `.recalculating` class is added to a shiny output. In particular the `.recalculating` class is added as soon as the output is invalidated, whereas the JS event is only triggered when the actual observer corresponding to the output starts running. If there are multiple outputs depending on a long-running reactive, this can cause a large gap between when the corresponding JS event is fired.

I am not sure if this deliberate, however the JS event behaviour seems not very intuitive and would expect `shiny:recalculating` to be triggered as soon as the output is invalidated.

The below example shows that there is 5s difference between the two outputs receiving the `shiny:recalculating` event as shown in the JS console, even though they depend on the same reactive. The `.recalculating` class is applied at the same time however.

```
library(shiny)

ui <- function() {
  fluidPage(
    shiny::singleton(
      tags$head(
        tags$script(
          shiny::HTML("
$(document).on('shiny:recalculating', function(event) {
  console.log('Recalc for %s running at %s',event.target.id,(new Date));
});
           "))
      )
    ),
    actionButton("recalc","recalc"),
    plotOutput("plot_1"),
    plotOutput("plot_2")
  )
}

server <- function(input, output,session) {
  plot_r <- reactive({
    input$recalc
    Sys.sleep(5) 
  })
  output$plot_1 <- renderPlot({
    plot_r()
    plot(
      x = runif(1e4), y = runif(1e4)
    )
  })
  output$plot_2 <- renderPlot({
    plot_r()
    plot(
      x = runif(1e4), y = runif(1e4)
    )
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by andrewsali** [comment]
Maybe a user-friendly solution would be to expose the [showProgress](https://github.com/rstudio/shiny/blob/ed77982330d0091338179a1d91ab374b78729ca5/R/shiny.R#L1150) message as a `shiny:invalidated` event, if possible? Then one would have a nice symmetry of `[shiny:invalidated; shiny:value]` bracketing when the client value is out-of-date whilst `[shiny:recalculating; shiny:recalculated]` would bracket the times the output observer is running (the latter being maybe slightly less important for the client, given that other observers might be doing part of the work as in my example).

**Comment by wch** [comment]
With `options(shiny.trace=TRUE)`, it can be seen that the `recalculating` and `recalculated` messages are sent before the actual data. I think this is because they get sent immediately, when the calculation happens, but the data gets batched up and is sent only after the reactive flush is completed. 

```
RECV {"method":"update","data":{"recalc:shiny.action":1}}
SEND {"progress":{"type":"binding","message":{"id":"plot_1"}}}
SEND {"busy":"busy"}
SEND {"progress":{"type":"binding","message":{"id":"plot_2"}}}
SEND {"recalculating":{"name":"plot_1","status":"recalculating"}}
SEND {"recalculating":{"name":"plot_1","status":"recalculated"}}
SEND {"recalculating":{"name":"plot_2","status":"recalculating"}}
SEND {"recalculating":{"name":"plot_2","status":"recalculated"}}
SEND {"busy":"idle"}
SEND {"errors":[],"values":{"plot_1":{"src":"data:image/png;[base64 data]","width":930,"height":400,"coordmap":[{"domain":{"left":-0.0399470047280192,"right":1.03999679486267,"bottom":-0.039645840106532,"top":1.03996611029841},"range":{"left":59.04,"right":899.76,"bottom":325.56,"top":58.04},"log":{"x":null,"y":null},"mapping":{}}]},"plot_2":{"src":"data:image/png;[base64 data]","width":930,"height":400,"coordmap":[{"domain":{"left":-0.039981318116188,"right":1.03996935178526,"bottom":-0.0399467549286783,"top":1.03992731007747},"range":{"left":59.04,"right":899.76,"bottom":325.56,"top":58.04},"log":{"x":null,"y":null},"mapping":{}}]}},"inputMessages":[]}
```

**Comment by bborgesr** [comment]
@wch I think that is expected or at least, reasonable, given our documentation of this event in the [JS events article](http://shiny.rstudio.com/articles/js-events.html):

> The shiny:recalculating and shiny:recalculated events are triggered before and after an output value is recalculated, respectively. Please note shiny:recalculated is triggered after the output value has been recalculated in R, but that does not imply the output value has been displayed on the page. Use shiny:value instead if you want to do something when the output value is rendered.

If I understand correctly, I think the issue here is unrelated. In Winston's trace above, the problematic bit is not the fact that `recalculating` and `recalculated` are sent before the actual data. Rather, the problem is that there is a 5s delay between the first plot firing its `recalculating` event and the second one doing the same:

```r
RECV {"method":"update","data":{"recalc:shiny.action":1}}
SEND {"progress":{"type":"binding","message":{"id":"plot_1"}}}
SEND {"busy":"busy"}
SEND {"progress":{"type":"binding","message":{"id":"plot_2"}}}
SEND {"recalculating":{"name":"plot_1","status":"recalculating"}}
# *********************************************************
# 5 second delay due to long-running reactive
# *********************************************************
SEND {"recalculating":{"name":"plot_1","status":"recalculated"}}
SEND {"recalculating":{"name":"plot_2","status":"recalculating"}}
SEND {"recalculating":{"name":"plot_2","status":"recalculated"}}
SEND {"busy":"idle"}
SEND {"errors":[],"values":{"plot_1":{"src":"data:image/png;[base64 data]","width":930,"height":400,"coordmap":[{"domain":{"left":-0.0399470047280192,"right":1.03999679486267,"bottom":-0.039645840106532,"top":1.03996611029841},"range":{"left":59.04,"right":899.76,"bottom":325.56,"top":58.04},"log":{"x":null,"y":null},"mapping":{}}]},"plot_2":{"src":"data:image/png;[base64 data]","width":930,"height":400,"coordmap":[{"domain":{"left":-0.039981318116188,"right":1.03996935178526,"bottom":-0.0399467549286783,"top":1.03992731007747},"range":{"left":59.04,"right":899.76,"bottom":325.56,"top":58.04},"log":{"x":null,"y":null},"mapping":{}}]}},"inputMessages":[]}
```

The main thing here is that when the first `renderPlot()` starts executing, it fires its `recalculating` event and then this takes 5 seconds; after the first `renderPlot()` finishes executing, it fires its `recalculated` event. When the second `renderPlot()` starts executing, it fires its `recalculating` event, and finishes much faster (because the reactive is cached). So, really, the JS events are accurate.

So if the question is "how can we make both `recalculated` events be fired at the same time", I actually think that the only real way around this is to turn the long-running reactive (in this case, `plot_r()`) into an async reactive, once that functionality becomes available. In this scenario, the first `renderPlot()` would return much faster, so both `recalculating` events would be fired one right after the other. (I think this is right, but not 100% sure, @jcheng5)

Back to the issue at hand, I do agree that it is a little weird that the `recalculating` CSS class and the `recalculating` JS event are out of sync. However, there's two reasons why we shouldn't move the `recalculating` JS event to earlier:

1. It is accurate (it reflects when the output actually starts recalculating)

2. There may be code depending on this (we could search github for the `shiny:recalculating` string) and a change could break this code (although I think that's unlikely...)

Now, we could create another event (like the suggested `shiny:invalidated`) that is fired when we add the `recalculating` CSS class. Most of the value derived from this is really making it so that the JS and CSS are synched. But I wonder if that's a good enough reason..? Especially because it may obscure the fact that the output has not really started recalculating yet. However, it did already invalidate (since, as soon as `plot_r()` is being re-run, all its reactive dependencies are invalidated). And this does seem like is "missing," given that we fire events for almost everything else... (right?) I also like the symmetry argument: 

- `shiny:value` : "The shiny:value event is triggered when an output receives a value from the server. The event object has three properties: name (output id), value (output value), and binding (output binding)."

- `shiny:invalidated` : The shiny:invalidated event is triggered when an output's value is invalidated on the server. The event object has three properties: name (output id), value (output value -- the one that has just been invalidated), and binding (output binding)."

For synchronous reactives, `shiny:invalidated` and `shiny:recalculating` can potentially be very far apart as is demonstrated in the app above. For asynchronous reactives, these will be essentially simultaneous.

If we want to go this way, @andrewsali's PR (#1743) looks good to me, though maybe it may be better to trigger this event in the same place where we add the css class ([output_binding.js#L42](https://github.com/rstudio/shiny/blob/master/srcjs/output_binding.js#L42))

**Comment by andrewsali** [comment]
@bborgesr you describe perfectly the issue! 

In many cases I think it's useful and important for the client to be aware asap that an output value is out-of-date / invalid and not have to wait for a potentially long time until the observer code for the output actually starts running (as in my example, other outputs can delay this significantly). Given that the `recalculating`/`recalculated` events are accurately named, introducing the `invalidated` event seems a logical solution. 

Regarding the location of this small code addition: I was also thinking of having the event trigger in the same place where the css class is added, but I thought it might be better to keep the event trigger codes as close together as possible.

**Comment by bborgesr** [comment]
Yeah, I think you make a good point @andrewsali. @wch, @jcheng5, what do you say? Let's add the `shiny:invalidated` event? As for the location of the code, I can be persuaded either way. I think it'd be easier to understand the code in the future (that the CSS and JS are in sync), if they're literally in the same place. But it's not a big deal.

**Comment by timelyportfolio** [comment]
Very much appreciate these changes and will incorporate soon.  One question I have is why are the `recalculating`, `recalculated`, and new `invalidated` not provide on the R side?  I could easily be missing something, so feel free to tell me I am ignorant :)

Let's say an output takes a while to transmit or appear on the HTML, and we would like to know when `recalculated` is complete on the R side besides sending a custom JS message.  Is there a way to accomplish this?

Thanks again for all your fine work!
