### ISSUE TITLE
Shiny Modules bug

### ISSUE THREAD

**Issue by aciobanusebi** [rstudio/shiny#1711]
Here is a simple shiny app.

```
library(shiny)
fUI <- function(id) {
  ns <- NS(id)
  actionButton(ns("go"),"Go")
}


f <- function(input, output, session, parameter) {
  # parameter
  observeEvent(input$go,{
    print(parameter)
  })
  return()
}


ui <- fluidPage(
  fUI("1"),
  fUI("2")
)

server <- function(input,output) {
  for(i in 1:2) {
    callModule(f, as.character(i),
                  parameter = i)
  }
}

shinyApp(ui=ui,server=server)
```

The expected behaviour: 
click button 1 => "1" is printed on console
click button 2 => "2" is printed on console.
**But it prints only 2.**

Solution 1:
If I uncomment the first line in function "f" then the real behaviour is the expected one.

Solution 2:
Also, if the server function is:
```
server <- function(input,output) {
  callModule(f, "1", parameter = 1)
  callModule(f, "2", parameter = 2)
}
```
then everything works fine.

Solution 3:
```
server <- function(input,output) {
  lapply(1:2,function(i) {
    callModule(f, as.character(i),
                  parameter = i)
  })
}
```

What's going on? It seems like all the callModule functions think of the same "i".

**Comment by stla** [comment]
Wow I didn't know "shiny modules", very good !

This is not a bug, you have to use `local`:
```
  for(i in 1:2) {
    local({
      j <- i
      callModule(f, as.character(j),
                 parameter = j)
    })
  }
```

**Comment by wch** [comment]
You're encountering R's lazy evaluation, where an expression isn't evaluated until it's needed. Here's an example that uses just regular functions:

```R
# This function returns a function which returns the value passed in to the original
create_f <- function(n) {
  function() {
    n
  }
}

# Works as expected
f1 <- create_f(1)
f1()  # 1
f2 <- create_f(2)
f2()  # 2


# Now we'll invoke create_f() in a loop
funs <- list()
for (i in 1:2) {
  funs[[i]] <- create_f(i)
}

# Both of them return 2
funs[[1]]()  # 2 
funs[[2]]()  # 2
```


The reason it happens is because the `n` in both of the `funs[[1]]` and `funs[[2]]` doesn't get evaluated until those functions are called. Until `n` is evaluated, it is a *promise*, that is, an expression and an environment in which to evaluate the expression. So in a very real sense, they both refer to the same `i`, until the functions are called.

@stla's workaround should fix the issue, although it would be better if you modify your module to by uncommenting the `parameter` line. The common convention in R is to wrap it with `force()`, as in `force(parameter)`. The `force` function doesn't do anything more than evaluate the expression. See `?force` for more information.

The corresponding code in my example would be:

```R
create_f_v2 <- function(n) {
  force(n)
  function() {
    n
  }
}

funs <- list()
for (i in 1:2) {
  funs[[i]] <- create_f_v2(i)
}

# Now they return the expected values
funs[[1]]()  # 1
funs[[2]]()  # 2


```

If you want to learn more, see the "Lazy Evaluation" section here: http://adv-r.had.co.nz/Functions.html

**Comment by aciobanusebi** [comment]
Thank you very much!
