### ISSUE TITLE
dateInput Request. Restrict to specific dates within min and max

### ISSUE THREAD

**Issue by pssguy** [rstudio/shiny#174]
I would like to have, say, only the Fridays clickable. So if one of the parameters could be a vector of allowable dates that would be v useful

**Comment by pssguy** [comment]
Almost annual update :)

**Comment by reidjax** [comment]
This would be a great features.  Items like quarter/month end options would be great as well

**Comment by pssguy** [comment]
Two years on! I have another app where setting allowable dates to a vector of dates would be extremely useful

**Comment by trestletech** [comment]
Pull requests welcome! :)

**Comment by kadrach** [comment]
I needed this for a project, so added a way to pass this option into the bootstrap datepicker. A more thought-out solution would be to allow passing arbitrary bootstrap datepicker options.

Unfortunately the datepicker version used in Shiny appears to be somewhat outdated, and does not support passing in arbitrary `datesDisabled` (https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#datesdisabled)

**Comment by daattali** [comment]
@kadrach I do believe shiny recently upgraded to datepicker 1.6.4, is that good enough to support this feautre? I'm sure that if you submit a PR, someone on the shiny team will take a look.

@jcheng5 or @wch - should @kadrach submit PR for this? (I'm nudging because I also ran into this issue...)

**Comment by raffscallion** [comment]
I am also very interested in this feature.  I'd like to prepopulate the datepicker with only the dates that have data to plot.

**Comment by detomas83** [comment]
Any update on this issue? I´m interested in using this functionality. Thanks

**Comment by jcheng5** [comment]
@daattali @kadrach Either of you feel free to submit a PR. We will need a CLA from @kadrach before we can merge though (once the PR comes in we can send the paperwork). Thanks and sorry for the lack of responsiveness.

**Comment by daattali** [comment]
Sounds like @kadrach already implemented some extra options. @kadrach could you see if the current shiny datepicker version supports your fix?

In order to add all the arbitrary options that the JS library provides, a design decision needs to be made, ideally from the Shiny team, regarding how the new `dateInput()` signature should look like:

1. Have a `...` argument, or
2. Use a `options = list()` argument (similar to `selectizeInput()` or `DT::datatable()`), or
3. Explicitly list all the supported arguments
