### ISSUE TITLE
Update method unnecessary insertUI/onRestore?

### ISSUE THREAD

**Issue by KZARCA** [rstudio/shiny#1777]
Hi,
When I run this code:

```r
library(shiny)

ui <- function(request) {
  shinyUI(fluidPage(
    div(id = "addModule"),
    bookmarkButton()
  ))
}

server <- shinyServer(function(input, output, session) {
  values <- reactiveValues(nM = 0)
  onBookmark(function(state) {
      state$values$nM <- values$nM
  })
  
  onRestore(function(state) {
      values$nM <- state$values$nM
    for (i in seq_len(values$nM)){
      insertUI("#addModule",
               ui = fluidRow(
                 column(2, textInput(paste0("name", i), NULL, NA)),
                 column(2, selectInput(paste0("type", i), NULL, choices = c("Constant", "Non-constant"), selectize = FALSE)),
                 column(8, div(id = paste0("emptydiv", i)))
               ),
               immediate = TRUE
      )
    }
  })
})
  
options(shiny.trace = TRUE)
shinyApp(ui, server, enableBookmarking = "url", options=list(port=5678))
```
and go to: 
```
http://127.0.0.1:5678/?_inputs_&name1=%22a%22&name2=%22b%22&name3=%22c%22&type1=%22Non-constant%22&type2=%22Constant%22&type3=%22Non-constant%22&_values_&nM=3`
```
the shiny trace is:

```json
SEND {"busy":"busy"}
SEND {"config":{"workerId":"","sessionId":"b425d6d44ffd3023679e2d768457ae3b","user":null}}
RECV {"method":"init","data":{"._bookmark_:shiny.action":0,".clientdata_pixelratio":1,".clientdata_url_protocol":"http:",".clientdata_url_hostname":"127.0.0.1",".clientdata_url_port":"5678",".clientdata_url_pathname":"/",".clientdata_url_search":"?_inputs_&name1=%22a%22&name2=%22b%22&name3=%22c%22&type1=%22Non-constant%22&type2=%22Constant%22&type3=%22Non-constant%22&_values_&nM=3",".clientdata_url_hash_initial":"",".clientdata_url_hash":"",".clientdata_singletons":"",".clientdata_allowDataUriScheme":true}}
SEND {"shiny-insert-ui":{"selector":"#addModule","multiple":false,"where":"beforeEnd","content":{"html":"<div class=\"row\">\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <input id=\"name1\" type=\"text\" class=\"form-control\" value=\"a\"/>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <div>\n        <select id=\"type1\" class=\"form-control\"><option value=\"Constant\">Constant<\/option>\n<option value=\"Non-constant\" selected>Non-constant<\/option><\/select>\n      <\/div>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-8\">\n    <div id=\"emptydiv1\"><\/div>\n  <\/div>\n<\/div>","deps":[]}}}
SEND {"shiny-insert-ui":{"selector":"#addModule","multiple":false,"where":"beforeEnd","content":{"html":"<div class=\"row\">\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <input id=\"name2\" type=\"text\" class=\"form-control\" value=\"b\"/>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <div>\n        <select id=\"type2\" class=\"form-control\"><option value=\"Constant\" selected>Constant<\/option>\n<option value=\"Non-constant\">Non-constant<\/option><\/select>\n      <\/div>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-8\">\n    <div id=\"emptydiv2\"><\/div>\n  <\/div>\n<\/div>","deps":[]}}}
SEND {"shiny-insert-ui":{"selector":"#addModule","multiple":false,"where":"beforeEnd","content":{"html":"<div class=\"row\">\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <input id=\"name3\" type=\"text\" class=\"form-control\" value=\"c\"/>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <div>\n        <select id=\"type3\" class=\"form-control\"><option value=\"Constant\">Constant<\/option>\n<option value=\"Non-constant\" selected>Non-constant<\/option><\/select>\n      <\/div>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-8\">\n    <div id=\"emptydiv3\"><\/div>\n  <\/div>\n<\/div>","deps":[]}}}
SEND {"busy":"idle"}
SEND {"errors":[],"values":[],"inputMessages":[]}
RECV {"method":"update","data":{"type1":"Non-constant","name1":"a","type2":"Constant","name2":"b","type3":"Non-constant","name3":"c"}}
```
I was wondering whether the last step of the restoring was necessary (RECV {"method":"update"...), as the values of the input fields are already set when using insertUI inside onRestore.

I'm asking because my app has an observer on one of these input fields, which means that it gets invalidated immediately after onRestore, which is a non-wanted behaviour.

**Comment by wch** [comment]
That's the client sending the values to the server. That's the only way that the server knows the values of inputs; it doesn't set input values directly when you call `insertUI`.

**Comment by KZARCA** [comment]
I thought that because if you look closely to lines beginning with SEND `{"shiny-insert-ui":`, you can see the values of the fields.

**Comment by bborgesr** [comment]
@KZARCA, here is the documentation for the `shiny.trace` option:

> `shiny.trace`
> Print messages sent between the R server and the web browser client to the R console. This is useful for debugging. Possible values are "`send`" (only print messages sent to the client), "`recv`" (only print messages received by the server), `TRUE` (print all messages), or `FALSE` (default; don't print any of these messages).

So in your trace above, each of the following lines corresponds to an event that is sent to the client (the web browser), as a result, in this case, of user interaction:

```
SEND {"shiny-insert-ui":{"selector":"#addModule","multiple":false,"where":"beforeEnd","content":{"html":"<div class=\"row\">\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <input id=\"name1\" type=\"text\" class=\"form-control\" value=\"a\"/>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <div>\n        <select id=\"type1\" class=\"form-control\"><option value=\"Constant\">Constant<\/option>\n<option value=\"Non-constant\" selected>Non-constant<\/option><\/select>\n      <\/div>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-8\">\n    <div id=\"emptydiv1\"><\/div>\n  <\/div>\n<\/div>","deps":[]}}}
SEND {"shiny-insert-ui":{"selector":"#addModule","multiple":false,"where":"beforeEnd","content":{"html":"<div class=\"row\">\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <input id=\"name2\" type=\"text\" class=\"form-control\" value=\"b\"/>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <div>\n        <select id=\"type2\" class=\"form-control\"><option value=\"Constant\" selected>Constant<\/option>\n<option value=\"Non-constant\">Non-constant<\/option><\/select>\n      <\/div>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-8\">\n    <div id=\"emptydiv2\"><\/div>\n  <\/div>\n<\/div>","deps":[]}}}
SEND {"shiny-insert-ui":{"selector":"#addModule","multiple":false,"where":"beforeEnd","content":{"html":"<div class=\"row\">\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <input id=\"name3\" type=\"text\" class=\"form-control\" value=\"c\"/>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-2\">\n    <div class=\"form-group shiny-input-container\">\n      <div>\n        <select id=\"type3\" class=\"form-control\"><option value=\"Constant\">Constant<\/option>\n<option value=\"Non-constant\" selected>Non-constant<\/option><\/select>\n      <\/div>\n    <\/div>\n  <\/div>\n  <div class=\"col-sm-8\">\n    <div id=\"emptydiv3\"><\/div>\n  <\/div>\n<\/div>","deps":[]}}}
SEND {"busy":"idle"}
SEND {"errors":[],"values":[],"inputMessages":[]}
```

So, the client now has received some data. In this case, this causes the DOM to change because the user added elements using `insertUI`. This is all done on the client (i.e. [inst/www/shared/shiny.js](https://github.com/rstudio/shiny/blob/master/inst/www/shared/shiny.js) knows how to deal with [receiving a `shiny-insert-ui` message](https://github.com/rstudio/shiny/blob/master/inst/www/shared/shiny.js#L1308-L1322)). However, in addition to doing this, the stuff that was inserted wasn't just static HTML. There were shiny inputs in there. Therefore, the client (web browser) has to send a message to the server (the R process) saying: "stuff has changed over on my end, and here's the info you need to update your end." This is how the R process knows that, in your case, there is (among others) a new input called `name1` whose value is `"a"`. I.e. this last line:

```
RECV {"method":"update","data":{"type1":"Non-constant","name1":"a","type2":"Constant","name2":"b","type3":"Non-constant","name3":"c"}}
```

is what is responsible for you, over in your R code after calling `insertUI()`, being able to type `input$name1` and get back the value `"a"`.

Here's a small example that illustrates that data is only sent back to server (i.e. `RECV ...`) after a call to `insertUI()` if that call generates or mutates shiny inputs or artifacts:

```r
options(shiny.trace = TRUE)

library(shiny)

ui <- fluidPage(
  actionButton("go", "Go")
)

server <- function(input, output, session) {
  observeEvent(input$go, {
    id <- paste0("n", input$go)
    insertUI("#go", "afterEnd", 
      #div(id)
      numericInput(id, id, input$go)
    )
  })
}

shinyApp(ui, server)
```

If you run the app as is, each button press will cause a chain of messages that end with a message sent to the server, like so (showing last two messages):

```
SEND {"shiny-insert-ui":{"selector":"#go","multiple":false,"where":"afterEnd","content":{"html":"<div class=\"form-group shiny-input-container\">\n  <label for=\"n1\">n1<\/label>\n  <input id=\"n1\" type=\"number\" class=\"form-control\" value=\"1\"/>\n<\/div>","deps":[]}}}
RECV {"method":"update","data":{"n1:shiny.number":1}}
```

That's because, in process of inserting new UI, we have also just created a new Shiny input -- in particular, a numeric input (`shiny.number`), whose input id is `n1` and whose value is `1` -- that the R process needs to knows about.

However, if you comment out that line and uncomment the currently commented one, the call to `insertUI()` is no longer changing Shiny inputs in any way. It just adds some static HTML content (a div with text) to the page. So, you see that each button press will cause a chain of messages that end with a similar `SEND` message as above, but no `RECV` message (since nothing that the R process cares about has changed):

```
SEND {"shiny-insert-ui":{"selector":"#go","multiple":false,"where":"afterEnd","content":{"html":"<div>n1<\/div>","deps":[]}}}
```

**Comment by bborgesr** [comment]
Also, for other people that may read this thread, this statement is incorrect:

> I'm asking because my app has an observer on one of these input fields, which means that it gets invalidated immediately after onRestore, which is a non-wanted behaviour.

What would be correct would be to say:

> My app has an observer on one of these input fields, which means that the observer is first triggered immediately after `onRestore`, as soon as the server registers this new input and its value.

This is the correct behavior. Observers should be triggered when a previously non-existing element "comes to life". If you don't want this behavior (which is a completely valid use case), I suggest that you use an `observeEvent()` whose event guarantees that the code inside the `handlerExpr` will not run when the input is first registered. A good approach to this could be making the input start as `NULL` or some other known value and using that to stop the observer from running. Notice that whatever value you choose, the observer won't run even if it's the user that enters that value (that's why I would recommend choosing a value like `NULL` for this scenario). 



Compare and contrast:

**Option 1: regular `observeEvent`**
In this option the observer is triggered at the same time the input is created:

```r
library(shiny)

ui <- fluidPage(
  actionButton("go", "Go")
)

server <- function(input, output, session) {
  observeEvent(input$go, {
    print(paste("Button pressed at", Sys.time()))
    id <- paste0("n", input$go)
    insertUI("#go", "afterEnd", 
      numericInput(id, id, NULL)
    )
  })
  
  observeEvent(input$n1, {
    print(paste("Observer for n1 ran", Sys.time()))
  })
}

shinyApp(ui, server)
```

**Option 2: `observeEvent` using `req` to stop execution for `NULL` value**
In this option the observer is triggered only when the value of `n1` is changed (typically, when the user first interacts with the input):

```r
library(shiny)

ui <- fluidPage(
  actionButton("go", "Go")
)

server <- function(input, output, session) {
  observeEvent(input$go, {
    print(paste("Button pressed at", Sys.time()))
    id <- paste0("n", input$go)
    insertUI("#go", "afterEnd", 
      numericInput(id, id, NULL)
    )
  })
  
  observeEvent(req(input$n1), {
    print(paste("Observer for n1 ran", Sys.time()))
  })
}

shinyApp(ui, server)

```

**Comment by KZARCA** [comment]
Thank you so much Barbara for making time to write this comprehensive reply. It will be very helpful!
