### ISSUE TITLE
the descendants of reactive() react while the value does not change

### ISSUE THREAD

**Issue by stla** [rstudio/shiny#1868]
Hello, 

 I was sure that the outputs depending on a reactive conductor do not react when the output of the reactive conductor does not change. But this is not the case. Maybe more clearly, what I mean is illustrated by the following example:

```
ui <-shinyUI(
  fluidPage(
    actionButton("go", "Simulate")
  )
)

server <- shinyServer(function(input,output, session){
  
  simulation <- eventReactive(input$go, rpois(n=1, lambda=10))
  
  lowerThan10 <- reactive(simulation() < 10)
  
  observe({
    print(lowerThan10())
  })
})
```

When the output of `simulation()` is, for example, 12 and the next one is 13, then the two successive outputs of `lowerThan10()` are `FALSE` and `FALSE`. And in this case the observer prints `FALSE` and `FALSE`. I was sure that it would print `FALSE` only one time. Then:

  - I was wrong ?
  - I was correct and this is abnormal ?
  - I was correct and something has changed in shiny ? 

This behavior does not occur with a reactive value instead of a reactive conductor; the observer below never prints the same value two consecutive times:

```
server <- shinyServer(function(input,output, session){
  
  rv <- reactiveValues()
  
  observeEvent(input$go, {
    simulation <- rpois(n=1, lambda=10)
    rv$lowerThan10 <- simulation < 10
  })

  observe({
    print(rv$lowerThan10)
  })
})
```
And I was sure to get the same behavior with a reactive conductor...

**Comment by wch** [comment]
The answer is the first one: You were wrong. :)

This post talks about it a bit:
  https://stackoverflow.com/a/39441145/412655

When you change a reactive value (like `input$go`), it immediately invalidates all downstream reactives and observers. When the reactive flush cycle happens, it executes all invalidated observers, which then "pull" their values from any upstream reactives by executing them as needed. It's possible for an observer to not need a particular reactive on subsequent runs. If that happens, the reactive in question won't get executed at all. Since the reactive expression doesn't get executed right away (or possibly even at all), it can't know that its value is the same as in the previous run.

In short: Invalidation starts with reactive values, and it "pushes" invalidation downstream immediately to all descendants. But executing reactives starts from the other end. During the flush cycle, observers "pull" their input values, executing upstream reactives only when necessary.


The reason that your second example behaves differently is because `reactiveValues` are different and have deduplication built-in. The reactive value doesn't execute code -- it just gets set with a value -- so unlike a reactive expression, it can know if the value is the same as the previous time with no need to execute anything.

There have been requests to allow changing the behavior of a reactive value so that it behaves like a reactive expression: #928.

**Comment by jcheng5** [comment]
+1 to everything @wch said. And if you want to change reactive expression to behave more like reactive value, here's a little helper function:

```r
dedupe <- function(rexpr, domain = getDefaultReactiveDomain()) {
  force(rexpr)
  x <- reactiveVal()
  observe({
    x(tryCatch(
      {
        list(success = rexpr())
      },
      error = function(e) {
        list(error = e)
      }
    ))
  }, domain = domain)
  
  reactive({
    result <- x()
    if (!is.null(result$success))
      result$success
    else
      stop(result$error)
  })
}
```

Use it like this (you'll need `library(magrittr)` too):

```r
lowerThan10 <- reactive(simulation() < 10) %>% dedupe()
```

**Comment by stla** [comment]
Thank you very much for the detailed answer !

**Comment by andrewsali** [comment]
Nnnn

**Comment by stla** [comment]
[Blog post](https://laustep.github.io/stlahblog/posts/shinyReactivity.html).

I think Joe's `dedupe` function would be useful in the package.
