### ISSUE TITLE
[inputFile] Upload a set of files with same name but different extensions at once (shapefiles)

### ISSUE THREAD

**Issue by geolauf** [rstudio/shiny#1873]
Hello everybody,

I am working with ESRI Shapefiles, the files work as a set of connexe files (.shp, .dbf, .shx and .prj) that have the same name.
 eg.: [mi_xxs.zip](https://github.com/rstudio/shiny/files/1401177/mi_xxs.zip)
Is there a way to select (and view in the browser) only the .shp file and automatically upload all the other files using `inputFile`?

Thanks in advance

Lau

**Comment by wch** [comment]
If I understand correctly, you want to select just one file in the browser's file selection dialog, like `file.shp`, and then have it automatically upload all the other files with the same extension?

This isn't possible, since web browser security policies wouldn't allow that. If you use `multiple=TRUE`, you can select and upload all the files at once, though.

**Comment by geolauf** [comment]
Thank you for this information!
Should have guessed the web browser is what is making it impossible..
I am already using `multiple=TRUE` and was looking for a way to make the users' experience nicer, not having to select all the files.. guess they will have to do with it!

best regards
