### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by jluttine** [rstudio/shiny#1894]
Does Shiny support other languages (similar to how Jupyter notebook supports kernels for different languages)? In particular, Python support would be great. Is this on the roadmap or do you know would it be relatively easy to add such support?

**Comment by daattali** [comment]
Shiny itself i simply an R package that allows you to create a web app using R code and is implemented in R.

That said, you can incorporate other languages if you'd like, but I think that's out of scope for shiny specifically, it can be done just because R has bindings to other languages. For example, Shiny makes it easy to create a UI using R code, but because it's UI you can also use straight up HTML, and of course you can use css/javascript as well. On the server side, shiny requires you to define the structure of the `server` function and makes a few decisions about how to create outputs and how to refer to inputs, but I suppose there's nothing stopping you from using R packages that provide bindings to other languages inside the server code. There are R packages let you run c++, java, python, etc and you're free to use them, but shiny itself does not inherently support a different language syntax. Hope that helps
