### ISSUE TITLE
Calling `runApp("app.R")` ignores options passed into `shinyApp()`

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1942]
When developing locally, I sometimes specify a port in the `options` argument of `shinyApp()` so that I can make sure I get a consistent URL every time I restart my session.

```
library(shiny)

ui <- fluidPage(
  "hello"
)

server <- function(input, output, session) {

}

shinyApp(ui, server, options = list(port = 5900))
```

Running this code manually works fine. But clicking on the green "Run App" button in RStudio seems to ignore the options list, and it runs on a different port each time. The same is true for using other options: for example, setting the display.mode will also be ignored with the "Run App" button.

I'm not sure if this is a feature or a bug, and it's very possible that it's been reported before but I couldn't find any traces of it

**Comment by jcheng5** [comment]
This has bothered me forever and I finally absolutely needed it for an app I'm writing. This is actually a problem anytime the `shinyApp()` object is not directly printed (or passed directly to `runApp()`, which is rare).

For example, when you press the Run App button in RStudio, it does NOT source the current file and print the resulting app object; instead, it calls `runApp()` if your file is named `./app.R`, and if not, then `runApp("path-to-your-file.R")`. (BTW, this is the right behavior for RStudio to do, because if you modify the .R file you can just reload the browser and see your changes.)

The bug is that `runApp()` goes through a level of indirection in these cases; it takes a path string and turns that into an object that can source your R file on demand. But that layer of indirection simply ignores the inner options.

Hope to have a PR up soon.
