### ISSUE TITLE
[Styling Recommendation] dateRangeInput dates within min/max not easily distinguishable from the rest

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/shiny#2042]
When using the date picker, it's difficult to visually distinguish between dates within `min` and `max` (the allowed dates) and all other dates. This may result in some confusion for users thinking they can select a date outside the allowed range.

The color values are different but perhaps not enough (two shades of dark gray, where disallowed dates are slightly lighter). Bolding may be an acceptable option for the allowed dates. The other design question is whether there should be two sets of styling for when either `min` and `max` have a date value, or, they are both `NULL` (i.e., styling for allowed/disallowed dates in the first case and a single default style for the second case).

Here is a screenshot of the rendered page from RStudio/Mac/Desktop: 

<img width="556" alt="dateinput" src="https://user-images.githubusercontent.com/5612024/39325571-6e78db5e-4947-11e8-9f4f-56dcd409c80a.png">

Here is the app itself:

```
# dateRangeInput with min/max dates
ui <- fluidPage(

  # Copy the line below to make a date range selector
  dateRangeInput(
    inputId = "dates",
    label = h3("Date range"),
    start = "2018-04-15",
    end = "2018-04-16",
    min = "2018-04-10",
    max = "2018-04-20"),

  hr(),
  fluidRow(column(4, verbatimTextOutput("value")))
)


server <- function(input, output) {

  # You can access the values of the widget (as a vector of Dates)
  # with input$dates, e.g.
  output$value <- renderPrint({ input$dates })
}

shinyApp(ui = ui, server = server)
```

**Comment by wch** [comment]
Reopening this issue because it turns out that the fix we had was too specific -- it didn't pick up all possible kinds of disabled cells.

With the test app above, the disabled days are colored correctly:

![image](https://user-images.githubusercontent.com/86978/47588383-a4698500-d92b-11e8-82a4-6e4a07b7e753.png)


But when you zoom out, disabled months are not:

![image](https://user-images.githubusercontent.com/86978/47588428-c236ea00-d92b-11e8-8057-8f7e48fb6bde.png)


This is because the CSS class hierarchy is different for months (and years, decades, etc).
