### ISSUE TITLE
infinite recursion when performing rbind on a reactive data frame

### ISSUE THREAD

**Issue by melissakey** [rstudio/shiny#2083]
I wrote this up on stackoverflow, but I'm wondering if it is a bug (or limitation).  I've documented my larger problem at https://stackoverflow.com/questions/50651618/dynamically-add-rows-to-rhandsontable-in-shiny-and-r, where I describe what I'm actually trying to do, but I've developed an even simpler example here which highlights what I believe to be the bug,

The idea is that the user specifies how many rows they wish to display in the rhandsontable.  If they update the table, they get that many additional rows added on.  Creating a new table does not pose any problem.  The problem occurs when I try to perform rbind on the reactive data frame (or on a dataframe generated from the reactive data frame, or on a data frame created from scratch and where I've inserted the reactive data - it doesn't seem to matter).  I get a "infinite recursion" error.  

If there is another/better way to approach this that avoids the error, I'd love to hear it - I'm new to shiny and I could easily have overlooked something.   

```
library(shiny)
library(rhandsontable)
library(tidyverse)

make_DF <- function(n) {
  DF <- data_frame(
    entry = 1:n,
    protein = NA_character_,
    MW = NA_real_,
    n = NA_integer_,
    mean = NA_real_,
    sd = NA_real_,
    units = factor("ng/mL", levels  = c("pg/mL", "ng/mL", 'mcg/mL', 'mg/mL', 'g/mL'))
  )
  DF[-1]
}

ui <- fluidPage(
  tabPanel("Input", 
  column(4,
    wellPanel(
      numericInput("n_entries",
        "Number of Concentrations to estimate:",
        value = 1,
        min = 1),
      actionButton("update_table", "Update Table")
    )
  ),
  column(8,
    rHandsontableOutput("input_data") )
),
  tabPanel("Output",
    column(12,
      tableOutput("test_output")
    )
  )
)

server <- function(input, output) {
  # create or update the data frame by adding some rows
  DF <- eventReactive(input$update_table, {
    DF_new <- make_DF(input$n_entries)
    
    # if a table does not already exist, this is our DF
    if (input$update_table == 1) {
      return(DF_new)
    } else { # otherwise, we will append the new data frame to the old.
      return(rbind(DF(), DF_new))
      # DF_old
    }
  })
  
  # determine which variables to show based on user input
 
  # # finally, set up table for data entry
  observeEvent(input$update_table, {
    output$test_output <- renderTable(DF())
    output$input_data <- renderRHandsontable({rhandsontable(DF())})
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by MohoWu** [comment]
I think the problem is you have the reactive expression `DF()` inside the creation of reactive expression `DF()`, which sort of makes it constantly invalidated. 

To do this type of additive operation, we have to use the `reactiveValues` function to store the current value which we want to add on something to. Here's an example of how to make it work for your application.

  ```
  # create a reactive value to store the current df
  values <- reactiveValues()
  
  observe({
    
    if (input$update_table == 1) {
      # isolate is to make sure df is not updated when input changes
      isolate(values$df <- make_DF(input$n_entries))
      
    }
    
    if (input$update_table > 1) {
      isolate({
        
        DF_new <- make_DF(input$n_entries)
        values$df <- rbind(values$df, DF_new)
        
      })
      
    }
    
  })
```

**Comment by jcheng5** [comment]
@MohoWu's reasoning is close. The problem is the `DF()` being defined inside `DF`; but it's not that it's being constantly invalidated, it's that it never finishes calculating. Though rare, you're technically allowed to have recursive reactives, but just like recursion in regular functions, you need to have a condition that makes the recursion terminate, and there isn't one here. The error message is exactly right, you have infinite recursion.

I'd make a slight tweak to @MohoWu's code: there's no need to define `output$test_output` and `output$input_data` repeatedly (i.e. inside an observer). The "Part 1" video on this page tells you why, starting about 17:00 or so.

```r
# create a reactive value to store the current df
values <- reactiveValues()

observeEvent(input$update_table, {
  if (input$update_table == 1) {
    # isolate is to make sure df is not updated when input changes
    values$df <- make_DF(input$n_entries)    
  } else {  
    DF_new <- make_DF(input$n_entries)
    values$df <- rbind(values$df, DF_new)
  }    
})

output$test_output <- renderTable(values$df)
output$input_data <- renderRHandsontable({rhandsontable(values$df)})
```

**Comment by melissakey** [comment]
thanks to both of you for explaining the issue and helping me find a solution.  Would you (or can I) post this on stackoverflow so that it's clear to others in the future?

**Comment by jcheng5** [comment]
@melissakey Can't speak for @MohoWu but you can post anything I write on Stack Overflow. Thanks for asking.

**Comment by MohoWu** [comment]
@melissakey Your SO question seems more complicated. Answer yourself on there. I don't mind.
