### ISSUE TITLE
Shiny Bookmarking issues Version 1.1.0 Vs 1.0.5

### ISSUE THREAD

**Issue by davidlyon3** [rstudio/shiny#2128]
This bookmarking used to work with Shiny version 1.0.5 but now fails with shiny version 1.1.0

Any ideas how to fix the code so it works with shiny version 1.1.0 ?

Thanks so much in advance

```R
library(shiny)

ui <- function(request) {
  fluidPage(
    bookmarkButton(),
    sidebarLayout(
      actionButton("add", "Add Element"),
      mainPanel(id = "content")
    )
  )
}

server <- function(input, output, session) {

  addItem <- function(id, textId, numberId, textVal = "", numberVal = NULL) {
    insertUI(
      selector = "#content",
      where = "beforeEnd",
      ui = tagList(
        wellPanel(style = "display:-webkit-inline-box;width:100%",
          id = id,
          column(3, textInput(textId, "Element name", textVal)),
          column(3, numericInput(numberId, "Element value", numberVal))
        )
      )
    )
  }

  observeEvent(input$add, {
    id <- paste0("var", input$add)
    textId <- paste0(id, "text")
    numberId <- paste0(id, "number")
    addItem(id, textId, numberId)
  }, ignoreInit = TRUE)

  onRestore(function(state) {
    for (i in seq_len(input$add))  {
      id <- paste0("var", i)
      textId <- paste0(id, "text")
      numberId <- paste0(id, "number")
      addItem(id, textId, numberId, input[[textId]], input[[numberId]])
    }
  })
}

enableBookmarking("url")
shinyApp(ui, server)
```

**Comment by wch** [comment]
The reason that the behavior changed is because we implemented async reactives in Shiny, so the order of startup events is slightly different.

In your case, you can fix it by using `state$input` instead of `input` in your `onRestore`.

```R
  onRestore(function(state) {
    for (i in seq_len(state$input$add))  {
      id <- paste0("var", i)
      textId <- paste0(id, "text")
      numberId <- paste0(id, "number")
      addItem(id, textId, numberId, state$input[[textId]], state$input[[numberId]])
    }
  })
```


More technical details about the issue:

Previously, the `onRestore` callback was apparently executed inside a restoreContext, so that if you call `textInput("txt", "Text", "foo")` in there, the value `"foo"` would be automatically replaced with the bookmarked value.

However, now the `onRestore` callback is not executed inside a restoreContext, and so the the value from the `textInput()` does not automatically get replaced. We'll need to think about which is the correct behavior for this case.

At any rate, I think that using `state$input` is more explicit about where it's getting the value from, and therefore a better way to go in general.

**Comment by jcheng5** [comment]
@davidlyon3 Should be fixed now on master. `devtools::install_github("rstudio/shiny")`

Sorry for the inconvenience, and thanks for the detailed bug report!

**Comment by davidlyon3** [comment]
Thank you so much for making those changes and thanks for developing all the wonderful tools.


Best
