### ISSUE TITLE
Bookmarking not working in with shinymaterial package

### ISSUE THREAD

**Issue by nwstephens** [rstudio/shiny#2130]
I am unable to see the bookmark dialog when I click on the bookmark button in a shinymaterial app. Here is an example:

http://colorado.rstudio.com:3939/content/1120/

When I click on the bookmark button, nothing happens. I would expect it to return a dialog box with my bookmark state.

**Comment by wch** [comment]
This is because the default bookmarking dialog uses Bootstrap. With shinymaterial, you'll have to do whatever it provides for a modal dialog.

The `onBookmarked` function can be used to change the behavior. See here for more info:
https://shiny.rstudio.com/articles/advanced-bookmarking.html#onbookmarked-and-onrestored

The default callback used is `showBookmarkUrlModal` -- in other words, the default behavior is equivalent to:

```R
onBookmarked(showBookmarkUrlModal)
```

You can look at the content of [`showBookmarkUrlModal`](https://github.com/rstudio/shiny/blob/81cc7c591e263c6539b534d43a9cc8691d7160ee/R/bookmark-state.R#L724-L735) and write a custom function using shinymaterial that does something similar.
