### ISSUE TITLE
Caching ETA

### ISSUE THREAD

**Issue by tantrev** [rstudio/shiny#2132]
[This](https://www.rstudio.com/resources/videos/scaling-shiny/?wvideo=mx214xmcqw) great video with the 10k user benchmark mentions around 15:40 about new caching functions being implemented in Shiny.  I am just curious if the functions are currently available or if there is an ETA when they will be?

**Comment by mschilli87** [comment]
There are currently two [pull requests](https://github.com/rstudio/shiny/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+cache) working towards this end.

**Comment by wch** [comment]
The should be merged in the next week or two. The next Shiny release will probably be a few weeks after that.

**Comment by tantrev** [comment]
That's great news, thank you.  Will any of these functions work with ShinyApps.io and/or require paid Shiny Server licenses?

**Comment by wch** [comment]
All of this stuff will work with shinyapps.io and will not require paid products like Shiny Server or RStudio Connect. With our paid products, we may make it easy to use database backends that can allow doing things like sharing a cache among multiple R processes, and scaling larger than is feasible with the memory and disk caches that we've implemented. We haven't yet made decisions about that, though.

(Side note: the disk cache that we've implemented already allows sharing a cache among multiple processes, but due to the inherent limitations of using a file system as a cache, it will not scale as well as a database.)

**Comment by tantrev** [comment]
Thanks for the great explanation @wch !  I just saw the renderCachedPlot function got merged into the main branch and includes functions for sharing a disk cache among processes.  On shinyapps.io, will any of the subscription types be able to utilize this shared disk cache?

**Comment by wch** [comment]
@tantrev Here's my understanding of how it currently works: on shinyapps.io, when the same app runs in multiple R processes, they share /tmp and the app directory itself. Neither of these are persisted after the app goes to sleep.

So that means for plot caching, it should work today if you use a disk cache and either point it to a subdirectory of an app, or to a fixed directory inside of /tmp. For example, if you put this at the top of your app.R, it will use /tmp/my-shiny-cache for all instances of the app:

```R
shinyOptions(cache = diskCache("/tmp/my-shiny-cache"))
```

If you test this out, please let us know how it goes.

I'm currently working on documentation explaining how cache scoping works.

**Comment by jcheng5** [comment]
To add to @wch's comment, shinyapps.io doesn't currently have persistent storage; the current app directory and /tmp will work during the lifetime of an instance, but when that instance is shut down after a period of idleness, the filesystem is essentially reset. We're working on a persistent storage feature for shinyapps.io but there's nothing to announce at this time, sorry.
