### ISSUE TITLE
Fontawesome

### ISSUE THREAD

**Issue by zuzuzuzz** [rstudio/shiny#2156]
Can you release the latest version of Fontawesome into dev?

**Comment by rich-iannone** [comment]
@zuzuzuzz There are some official alternatives to try until Shiny proper gets a Fontawesome update. One option is to use the *fontawesome* package. It works well in Shiny, and it's updated to the latest free icons. The README (with a Shiny example) is at: https://github.com/rstudio/fontawesome.

**Comment by nohlsen** [comment]
If you need icons in your valuebox you can do this:
```
infoBox(
  "title", 
  "value", 
  icon = tags$i(fa(name = "box", fill = "white")),
  color = "teal", fill =TRUE, width = 3
)
```

**Comment by CalaoJuanPablo** [comment]
duplicate #1966

**Comment by AveugleVisionnaire** [comment]
Thanks @rich-iannone. This save my day. Hovewer, it doesn't work on Microsft IE11. 
I'm using your suggeted alternative to display icon in my shinydashboard sidebar. It works fine with Chrome, Firefox and Edge. But on IE11 it only shows the icon instead of icon + menu item title.
Do you have any idea to fix this issue?
At least, can we have  menu item title displayed?

**Comment by hlendway** [comment]
This isn't a great solution for icons in the menu bar because it doesn't pick up the proper styling. i.e. the icon is set at one color and not highlighted properly when selected or not selected.  Also the spacing between the icon and the menu item name is off.
![image](https://user-images.githubusercontent.com/25120859/45432295-239e4480-b66f-11e8-8aa5-a8c371f7938c.png)

**Comment by jcheng5** [comment]
We've upgraded FA in Shiny on master, since the separate Font Awesome package raised more questions than we expected.

**Comment by alandipert** [comment]
I'm closing this because the FA upgrade went out with Shiny 1.2, but feel free to re-open or make another issue if your needs remain unmet.
