### ISSUE TITLE
Encoding problem between ui (selectInput) and server

### ISSUE THREAD

**Issue by daniel21nov** [rstudio/shiny#2175]
Hi,
I have a problem to print Swedish letters that has to do with selectInput in ui and interaction with server. I provide an example:

```r
library(shiny)
ui<-fluidPage( 
  sidebarLayout(
    sidebarPanel(
      helpText(),
      selectInput("data", h5("Select Letters:"), choices = c("Select Ä",
        "Select A","Select Ö"))
    ),
    mainPanel(
      tabsetPanel(type = "tabs",
        
        tabPanel("Letters",
          htmlOutput("print", inline = T)
        )
      )
    )
  )
)

server<-function(input, output) {
  Select <- reactive({
    switch(input$data,
      "Select Ä" = "Ä",
      "Select A"="A",
      "Select Ö"="O"
    )
  })
  
  output$print <- renderPrint({#Print
    Select() 
  })
}

shinyApp(ui, server)
```

Hope  you can run it. I can print the "A" but not the "Ä" or the "O". Here is session information:

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.1.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  magrittr_1.5    R6_2.2.2        rsconnect_0.8.8 promises_1.0.1  later_0.7.3     htmltools_0.3.6
 [8] tools_3.5.0     yaml_2.1.19     Rcpp_0.12.17    jsonlite_1.5    digest_0.6.15   xtable_1.8-2    httpuv_1.4.3   
[15] mime_0.5        rlang_0.2.1 
```

**Comment by jcheng5** [comment]
The problem appears to be with this chunk:

```r
    switch(input$data,
      "Select Ä" = "Ä",
      "Select A"="A",
      "Select Ö"="O"
    )
```

If you were to print `input$data`, you'd see it correctly says `"Select Ä"`, and if you even compared it using `input$data == "Select Ä"` you'd see it's `TRUE`.

The problem is that `Encoding(input$data)` is `"UTF-8 "` while (on my Windows at least) the `switch` conditions are effectively encoded with `"latin1"`. If you convert `input$data` to latin1 as well, it works:

```r
    switch(iconv(input$data, from = "UTF-8", to = "latin1"),
           "Select Ä" = "Ä",
           "Select A"="A",
           "Select Ö"="O"
    )
```

But this will then (I'm guessing) fail to work on Mac or Linux (and the latter is where you'll be running if you use Shiny Server, Connect, or shinyapps.io).

It could conceivably be considered a bug in R, that `switch` doesn't do this conversion for you. Certainly there's nothing we can do about it in Shiny itself.

There are several ways to accomplish what you want without using a switch statement at all, though. First of all, the `selectInput` can take a named list. With the following code, `input$data` will directly contain the letters you're looking for.

```r
      selectInput("data", h5("Select Letters:"), choices = c("Select Ä" = "Ä",
        "Select A" = "A", "Select Ö" = "Ö"))
```

If there's some other reason you need to map from non-ASCII characters to other data on the server side, another way to do it is by looking up a list:

```r
lst <- list(
  "Select Ä" = "Ä",
  "Select A" = "A",
  "Select Ö" = "Ö"
)
lst[[input$data]]
```

And of course, you can always do `if`/`else if`/`else` statements that check for each possible value.
