### ISSUE TITLE
Input brush isn't properly cleared when new brush is drawn

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2197]
Observed in RStudio viewer 1.1.456 with v1.2-rc in https://github.com/rstudio/shiny-examples/tree/master/108-module-output

![module](https://user-images.githubusercontent.com/1365941/46086339-7d256980-c16d-11e8-95a9-60c1cae9aa37.gif)

Interestingly, the issue doesn't occur in Chrome (with v1.2-rc), nor does it appear in the viewer with shiny v1.1

**Comment by jcheng5** [comment]
@schloerke, @cpsievert and I did some investigation and learned some things.

### Some code that imports and removes the previous brush is not being called

This is an issue that was introduced in #2198 (merged this morning). This block of code waits for the image to load, then imports the old brush (and removes the old brush's `<div>` when complete):

https://github.com/rstudio/shiny/blob/1d0edd2ad015ff6c45914ee17a8d65577d5dbeed/srcjs/output_binding_image.js#L1032-L1035

#2198 moved the caller of this code into `$img.on("load")`, so the `brush.importOldBrush()` etc. will never be called. The fix is simple, just run these lines immediately instead of using the `load` event.

### Each time a brush occurs, the plot is redrawn _twice_.

With `options(shiny.trace=TRUE)`, we can see some differences in the JSON. The first plot's input/output looks like this (this is from the server's perspective, so RECV is stuff the client sends to the server, and SEND is the opposite):

```
RECV {"method":"update","data":{"scatters-brush":{"xmin":13.055710626153,"xmax":20.25859409253,"ymin":18.528245419468,"ymax":31.066840387247,"coords_css":{"xmin":130,"xmax":260,"ymin":155,"ymax":284},"coords_img":{"xmin":260,"xmax":520,"ymin":310,"ymax":568},"img_css_ratio":{"x":2,"y":2},"mapping":{"colour":"selected_","x":"cty","y":"hwy"},"domain":{"left":7.7,"right":36.3,"bottom":10.4,"top":45.6},"range":{"left":66.6767608694834,"right":1099.04109589041,"bottom":735.250582988923,"top":10.958904109589},"log":{"x":null,"y":null},"direction":"xy","brushId":"scatters-brush","outputId":"scatters-plot1"}}}
SEND {"errors":[],"values":{"summary":"120 observation(s) selected","scatters-plot1":{"src":"data:image/png;[base64 data]","width":555,"height":400,"coordmap":{"panels":[{"panel":1,"row":1,"col":1,"panel_vars":{},"log":{"x":null,"y":null},"domain":{"left":7.7,"right":36.3,"bottom":10.4,"top":45.6},"mapping":{"colour":"selected_","x":"cty","y":"hwy"},"range":{"left":66.6767608694834,"right":1099.04109589041,"bottom":735.250582988923,"top":10.958904109589}}],"dims":{"width":1110,"height":800}}},"scatters-plot2":{"src":"data:image/png;[base64 data]","width":555,"height":400,"coordmap":{"panels":[{"panel":1,"row":1,"col":1,"panel_vars":{},"log":{"x":null,"y":null},"domain":{"left":0.4,"right":3.6,"bottom":10.4,"top":45.6},"mapping":{"colour":"selected_","x":"drv","y":"hwy"},"range":{"left":66.6767608694834,"right":1099.04109589041,"bottom":735.250582988923,"top":10.958904109589}}],"dims":{"width":1110,"height":800}}}},"inputMessages":[]}
```

The second looks like this:

```
RECV {"method":"update","data":{"scatters-brush":{"xmin":13.055710626153,"xmax":20.25859409253,"ymin":18.528245419468,"ymax":31.066840387247,"coords_css":{"xmin":130.00000000000307,"xmax":259.99999999999466,"ymin":154.99999999999622,"ymax":284.00000000000506},"coords_img":{"xmin":260.00000000000614,"xmax":519.9999999999893,"ymin":309.99999999999244,"ymax":568.0000000000101},"img_css_ratio":{"x":2,"y":2},"mapping":{"colour":"selected_","x":"cty","y":"hwy"},"domain":{"left":7.7,"right":36.3,"bottom":10.4,"top":45.6},"range":{"left":66.6767608694834,"right":1099.04109589041,"bottom":735.250582988923,"top":10.958904109589},"log":{"x":null,"y":null},"direction":"xy","brushId":"scatters-brush","outputId":"scatters-plot1"}}}
SEND {"errors":[],"values":{"summary":"120 observation(s) selected","scatters-plot1":{"src":"data:image/png;[base64 data]","width":555,"height":400,"coordmap":{"panels":[{"panel":1,"row":1,"col":1,"panel_vars":{},"log":{"x":null,"y":null},"domain":{"left":7.7,"right":36.3,"bottom":10.4,"top":45.6},"mapping":{"colour":"selected_","x":"cty","y":"hwy"},"range":{"left":66.6767608694834,"right":1099.04109589041,"bottom":735.250582988923,"top":10.958904109589}}],"dims":{"width":1110,"height":800}}},"scatters-plot2":{"src":"data:image/png;[base64 data]","width":555,"height":400,"coordmap":{"panels":[{"panel":1,"row":1,"col":1,"panel_vars":{},"log":{"x":null,"y":null},"domain":{"left":0.4,"right":3.6,"bottom":10.4,"top":45.6},"mapping":{"colour":"selected_","x":"drv","y":"hwy"},"range":{"left":66.6767608694834,"right":1099.04109589041,"bottom":735.250582988923,"top":10.958904109589}}],"dims":{"width":1110,"height":800}}}},"inputMessages":[]}
```

The diff:
![image](https://user-images.githubusercontent.com/129551/46111021-4fa2e500-c19a-11e8-971f-7c8626942abe.png)

So, that's one thing. This causes the server to generate the same exact plot twice. (This probably deserves its own issue.)

### On WebKit (only), an image's `load` event doesn't fire when you try to load the same image that's already displaying

https://stackoverflow.com/questions/5024111/javascript-image-onload-doesnt-fire-in-webkit-if-loading-same-image

And "try to load the same image that's already displaying" is exactly what the previous heading causes to happen.

This is causing all of the logic that's directly in `renderValue` to be executed, but the rest of the initialization code that waits for `$img.on("load")` never gets called.

**Comment by jcheng5** [comment]
@schloerke Temporarily setting `.src` to a dummy value seems to work around the load event not firing:

![image](https://user-images.githubusercontent.com/129551/46112409-74e62200-c19f-11e8-9e2d-091ff0a571e7.png)

**Comment by jcheng5** [comment]
Actually, better than `img.src = "about:blank";`, is `img.removeAttribute("src")`.

**Comment by jcheng5** [comment]
Relevant for the second issue, of the plot being drawn twice because `coords_css` and `coords_img` are slightly off:
https://github.com/rstudio/shiny/issues/1634

**Comment by cpsievert** [comment]
Subtly different issue, but probably related, using 093-plot-interaction-basic on both mac+chrome and ide+windows:

![brush](https://user-images.githubusercontent.com/1365941/46151409-51b98200-c234-11e8-916e-1599e6c69c95.gif)

Happy to put in a different issue, just let me know

**Comment by schloerke** [comment]
I never applied the rounding to 14 digits code to coords_imag and coords_css. So that makes sense.  

https://github.com/rstudio/shiny/blob/3cea5fb2d04632d6339e033fd517dca1f600f0dc/srcjs/output_binding_image.js#L1259-L1261
