### ISSUE TITLE
href prepended by # in actionLink

### ISSUE THREAD

**Issue by dchiu911** [rstudio/shiny#2207]
If I use the shiny `actionLink`, a `#` is prepended to `href` when I hover over the link.
```r
actionLink(
  inputId = "github",
  label = "Source Code",
  icon = icon("github"),
  href = "https://github.com",
  onclick = "window.open('https://github.com', '_blank')"
)
```
Here is the HTML:
```html
<a class="action-button" href="# https://github.com" id="github" onclick="window.open(&#39;https://github.com&#39;, &#39;_blank&#39;)">
  <i class="fa fa-github"></i>
  Source Code
</a>
```

I get the correct `href` when hovering if I use HTML tags:
```r
a(
  icon("github"),
  " Source Code",
  href = "https://github.com",
  target = "_blank"
)
```
Here is the HTML:
```html
<a href="https://github.com" target="_blank">
  <i class="fa fa-github"></i>
   Source Code
</a>
```

**Comment by jcheng5** [comment]
This is actually by design. `actionLink` is intended to be used to trigger reactive observers, not as regular anchor tags, so you should never pass `href` nor `onclick` to it; it already has its own built-in behavior. If you're looking to create an anchor that actually navigates the page, then your "if I use HTML tags" snippet is correct.
