### ISSUE TITLE
shiny not getting installed on R version 3.5.1

### ISSUE THREAD

**Issue by komalsrathi** [rstudio/shiny#2217]
Hi,

I am trying to install shiny using R version 3.5.1 and getting an error:

```
* installing *source* package ‘later’ ...
** package ‘later’ successfully unpacked and MD5 sums checked
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
* removing ‘/usr/lib64/R/library/later’
ERROR: dependency ‘later’ is not available for package ‘promises’
* removing ‘/usr/lib64/R/library/promises’
ERROR: dependencies ‘promises’, ‘later’ are not available for package ‘httpuv’
* removing ‘/usr/lib64/R/library/httpuv’
ERROR: dependencies ‘httpuv’, ‘later’, ‘promises’ are not available for package ‘shiny’
* removing ‘/usr/lib64/R/library/shiny’

The downloaded source packages are in
	‘/tmp/RtmpLMVBSC/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("shiny") :
  installation of package ‘later’ had non-zero exit status
2: In install.packages("shiny") :
  installation of package ‘promises’ had non-zero exit status
3: In install.packages("shiny") :
  installation of package ‘httpuv’ had non-zero exit status
4: In install.packages("shiny") :
  installation of package ‘shiny’ had non-zero exit status
```

Please advise.

**Comment by mschilli87** [comment]
Did you check the [R Installation and Administration Manual](https://cran.r-project.org/doc/manuals/R-admin.html) as advised?

I suspect the following part is relevant here:
> Ensure that the environment variable `TMPDIR` is either unset (and `/tmp` exists and can be written in and scripts can be executed from) or points to the absolute path to a valid temporary directory (one from which execution of scripts is allowed) which does not contain spaces.

My guess is you are on a Linux system with the default `TMPDIR` being `/tmp` and `/tmp` (probably a ramdisk) is [mounted without execution permissions for safety reasons](https://serverfault.com/questions/72356/how-useful-is-mounting-tmp-noexec) (`mount | grep tmp` could confirm this - I'd expect to see `tmpfs` and `noexec` in the output). So by default `R` will download the package source to `/tmp` and during build attempt to *execute* the `configure` script which
> exists but is not executable

due to the `noexec` flag.

As pointed out in the initial quote from the manual the error message is pointing you to, there are two ways to fix this:

1. mount `/tmp` without `noexec` - This will require administrator rights and is maybe not the best idea (see the link above).
2. set `TMPDIR` *temporarily* (no pun intended) to `.` or any other place where you have space and read/write/execute permissions, run `R`, install the packages, un-/reset `TMPDIR`, and cleanup the temporary files created by `R`.

**Comment by alandipert** [comment]
Closing because this appears to be a more general R problem and @mschilli87 helpfully provided some suggestions. 

If this remains unresolved for you please don't hesitate to comment further here or open a new topic on [Community](http://community.rstudio.com/).
