### ISSUE TITLE
Shiny does not import some package dependencies

### ISSUE THREAD

**Issue by JamesSciberras** [rstudio/shiny#2283]
`library("shiny")` does not import `rlang` or `jsonlite` as described in the documentation [here](https://cran.r-project.org/web/packages/shiny/index.html).

It does not matter hugely that I need to call them separately, but might be worth updating the documentation for this. Also, this was found by a different team member and I have confirmed it on multiple different computers.

Further information if required:

- R version 3.5.1 (2018-07-02)
- Platform: x86_64-apple-darwin15.6.0 (64-bit)
- Running under: macOS  10.14.1

Package information:
`other attached packages:`
`[1] shiny_1.2.0`

`loaded via a namespace (and not attached):`
 `[1] compiler_3.5.1  magrittr_1.5    R6_2.3.0        promises_1.0.1  later_0.7.5 `
 `[6] htmltools_0.3.6 tools_3.5.1     yaml_2.2.0      Rcpp_0.12.19    digest_0.6.18 `
`[11] xtable_1.8-3    httpuv_1.4.5    mime_0.6`

**Comment by JamesSciberras** [comment]
Thanks for the response. I think I understand now - the import is for installing rather than loading. Apologies for the confusion, and thanks for the clarification.

**Comment by wch** [comment]
It's not that the Imports are used for installation rather than loading. It's just that functions from rlang and jsonlite are called like this: `jsonlite::toJSON`, and so they are loaded when they're used, instead of being loaded immediately when shiny is loaded. If you run a shiny app and then quit it, you'll see that jsonlite and rlang are loaded.

**Comment by JamesSciberras** [comment]
I see. So if I omit the `jsonlite::` or the `rlang::` when writing my functions they will not work then. I think I get it! Thanks all.
