### ISSUE TITLE
Complaint when running built-in example

### ISSUE THREAD

**Issue by gvwilson** [rstudio/shiny#2287]
1. Started working through https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/
2. Made sure Shiny was installed.
3. Ran `library(shiny)` followed by `runExample("01_hello")`.
4. Application appears in Viewer window as expected.
5. Click 'Stop' button in Viewer window.
6. Get repeated error message in text editing window where I'm editing the `.Rmd` file that contains commands (see screenshot).

![screen shot 2018-12-18 at 10 27 58 am](https://user-images.githubusercontent.com/911566/50164144-e79eff00-02af-11e9-99aa-3341da35c3c8.png)

Possibly important: `output` type in `.Rmd`'s YAML header is set to `md_document`.

**Comment by alandipert** [comment]
@gvwilson Thank you for the report, however Shiny apps are not intended to be embeddable in RMarkdown in that way.

However, it is possible to make a interactive RMarkdown documents with `runtime: shiny`. For more information, please see [the R Markdown guide](https://bookdown.org/yihui/rmarkdown/shiny-documents.html).

Since this isn't a bug we can fix, I'm closing the issue. However, if you feel your question remains unresolved, feel free to re-open or ask questions on [Community](http://community.rstudio.com).
