### ISSUE TITLE
File upload is throwing 400 error.

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/shiny#2325]
Run app 066-upload-file or 081-widgets-gallery and try uploading a file. It throws 400 error . 

Per Winston this could be related to httpuv static file serving code. 
<img width="1085" alt="screen shot 2019-02-07 at 2 16 47 pm" src="https://user-images.githubusercontent.com/32690638/52502711-1008f280-2ba9-11e9-82ae-c3b4dbb10c1f.png">

**Comment by wch** [comment]
For a minimal example, the app must be saved as a file (as opposed to run from the console), and there must be a `www/` subdirectory.

```R
shinyApp(
  fluidPage(
    fileInput("file", label = "File input"),
    verbatimTextOutput("fileOut")
  ),
  function(input, output) {
    output$fileOut <- renderPrint({ input$file })
  }
)
```

The problem is that the `www` directory is added as a static path mapped to `/`, and the file upload is a POST to a path like `session/4524b80e7cb6b518d84a5bd5215efc83/upload/7ea9ad8781d16c64ad481cbf`, which is treated as a subdirectory of the `/` static path.

The code in httpuv checks if it is a GET or HEAD and gives a 400 because it is a POST:
https://github.com/rstudio/httpuv/blob/8c48fea6/src/webapplication.cpp#L478-L480
