### ISSUE TITLE
Minor bug in dateRange: when max is set to today, initial value is empty

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#2335]
When creating a dateInput and not setting any initial value, today's date gets set by default.

```
dateInput("date", "Date")
```

![image](https://user-images.githubusercontent.com/952340/53283921-fd4efb80-371a-11e9-8c4d-5addce520768.png)

But if I set the max to be today's date, then the input initializes with an empty value.

```
dateInput("date", "Date", max = Sys.Date())
```

![image](https://user-images.githubusercontent.com/952340/53283917-ef00df80-371a-11e9-9ce8-fa19f7ac5bdd.png)

Even though today's date **is** selectable from the dropdown, and it's also possible to set today's date using the `value` argument.

**Comment by alandipert** [comment]
Thanks @daattali, can confirm.

**Comment by ColinFay** [comment]
Seems to happen only with `SysDate()`

``` r
# No bug
ui <- fluidPage(
  dateInput("date", "Date", max = "2019-10-10"),
  verbatimTextOutput("res")
)
server <- function(input, output, session) {
  output$res <- renderPrint({
    input$date
  })
}
shinyApp(ui, server)

# Bug
ui <- fluidPage(
  dateInput("date", "Date", max = Sys.Date()),
  verbatimTextOutput("res")
)
server <- function(input, output, session) {
  output$res <- renderPrint({
    input$date
  })
}
shinyApp(ui, server)


```

**Comment by cpsievert** [comment]
It appears this has been a problem ever since upgrading bootstrap-picker in #

Also, this issue appears whenever `max` is less than or equal to the current date.

**Comment by cpsievert** [comment]
The underlying issue here seems to derive from this code:

https://github.com/rstudio/shiny/blob/386078d4415da7bbb05b8d63874758d5f6b1672f/srcjs/input_binding_date.js#L167-L170

Looks like we get/set the current value in this manner to avoid a known `bootstrap-datepicker` issues with using `getUTCDate` after `setStartDate`/`setEndDate` https://github.com/uxsolutions/bootstrap-datepicker/issues/2010

Unfortunately, there is another known issue where you can't programmatically set a date equal the end date https://github.com/uxsolutions/bootstrap-datepicker/issues/2292

All that considered, I'm not sure if it's sensible for us to undergo a bugfix for this corner-case, especially considering that shiny users have the ability to workaround the issue by setting a sensible `value`, for example:

```r
dateInput("date", "Date", max = Sys.Date(), value = Sys.Date())
```

**Comment by cpsievert** [comment]
Perhaps we can use this workaround https://github.com/uxsolutions/bootstrap-datepicker/issues/2292#issuecomment-341496634
