### ISSUE TITLE
disable_protocols not disabling websocket.

### ISSUE THREAD

**Issue by RobinYC** [rstudio/shiny#2347]
### Summary
Adding the following options to `/etc/shiny-server/shiny-server.conf`:
```
sanitize_errors off;
disable_protocols websocket xdr-polling;
```
Does not disable websocket.

### Detail
I have a Shiny application in a Docker container hosted on Microsoft Azure WebApp. The application doesn't work anymore when log in with Azure Active Directory is activated. The application page is accessible but a error 500 is returned on websocket content as shown on the [Firefox network trace](https://i.stack.imgur.com/QvmgI.png) This error is not present without log in with AAD.

I've thus tried to disable websockets but changing `shiny-server.conf` does not have any effect.

**Comment by alandipert** [comment]
Hi @RobinYC thanks for the report, but this is the place for posting issues with the Shiny package itself, not for Shiny Server (a separate piece of software).

Because you've configured AAD, It sounds like you're using Shiny Server Pro, which means you have access to our dedicated support team. I suggest reaching out to them at support@rstudio.com, they are extremely helpful.
