### ISSUE TITLE
whitelist_headers does not work

### ISSUE THREAD

**Issue by cyrusd87** [rstudio/shiny#2366]
Hi,
I would like to manage my Shiny Server Pro with SSO and I want to check inside my shiny app if the request contains some other returned by my reverse proxy. I am using for this aim the whitelist_headers function but seems does not work.

 My reverse proxy forwards two headers to the Shiny Server Pro and I want to share these with the Shiny app in order to check if the user is already logged, but whitelist_headers does not work.

In shiny-server.conf I have added this line:
whitelist_headers HTTP_X_FORWARDED_SERVER HTTP_OSSO_USER_IN;

under server level.
But in the request session$request$HTTP_X_FORWARDED_SERVER I don't have nothing.

Any advice?
Thanks

**Comment by alandipert** [comment]
@cyrusd87 thanks for the report, although since you're using Shiny Server Pro you should consider contacting support@rstudio.com in the future if you run into problems. Our support team is excellent 😄 

Are you absolutely positive your reverse proxy is sending the headers you expect? I ask because I tested with [the latest Shiny Server Pro](https://www.rstudio.com/products/shiny/download-commercial/) and I was unable to reproduce your issue.

I tested by adding a `whitelist_headers` line to my own config: `whitelist_headers dnt;` inside the `server` block. `DNT` is a header I know Chrome always sends.

Then I used this app to display the headers, and saw that `HTTP_DNT` was listed as I expected:
```R
library(shiny)

ui <- fluidPage(
  tableOutput("headers")
)

http_headers <- function(request) {
  Reduce(function(df, k) {
    if (grepl("^HTTP_", k)) {
      rbind(df, list(name = k, value = request[[k]]), stringsAsFactors = FALSE)
    } else df
  }, ls(request), init = data.frame())
}

server <- function(input, output, session) {
  output$headers <- renderTable({
    http_headers(session$request)
  })
}

shinyApp(ui, server)
```

If you have access to the machine running Shiny Server, you may consider stopping it temporarily and running a simple `netcat`-based server temporarily that simply dumps the request data to the console. You would just need to make sure you're running `netcat` on the same port that Shiny Server was configured to listen on, otherwise you'd need to reconfigure your reverse proxy. Instructions on how to do this can be found here: https://shapeshed.com/examine-headers-with-netcat/

That experiment would tell you whether or not Shiny Server Pro was contributing to the problem. Thanks in advance for sharing your results, I hope this is helpful.

**Comment by jcheng5** [comment]
I think you just need this:

```
whitelist_headers X-Forwarded-Server Osso-User-In;
```
