### ISSUE TITLE
selectInput coerces its output to character even if the input to choices is a named numeric

### ISSUE THREAD

**Issue by nzxwang** [rstudio/shiny#2367]
Reprex:
```
library(shiny)
library(tidyverse)

shinyApp(
  
  ui = fluidPage(
    selectInput("variable", label=NULL,
                choices = setNames(seq_along(colnames(mtcars)),
                                   colnames(mtcars))),
    textOutput("variable"),
    tableOutput("data")
  ),
  
  server = function(input, output) {
    
    output$variable <- renderPrint({
      input$variable %>% str
    })
    
    output$data <- renderTable({
      mtcars %>% as_tibble() %>% .[, input$variable]
    })
  }
)
```

Currently, the way around this is to create a reactive conductor to coerce the output of the selectInput back to an integer. I believe this is due to calling `shiny:::choicesWithNames` under the hood. Would you be open to a pull request that allows the user to optionally set coercing to character off?

**Comment by alandipert** [comment]
I discussed this with @jcheng5 and I don't think we'll consider changing the behavior of `selectInput` at this point because it would break too many apps. So, no PR please.

What you suggest *is* more sensible behavior, and your suggestion and your offer to implement is much appreciated. It's just not something we can do anything about at this point, so I'm closing the issue.
