### ISSUE TITLE
Using iconv code map in shinyapps.io

### ISSUE THREAD

**Issue by shamigupta** [rstudio/shiny#2425]
Hello

I am trying to deploy a shiny app to shinyapps.io where I am facing challenge. Inn the app I am using mainframe data in EBCDIC format - which I have converted using iconv as
xyz <- iconv(mydata,from="IBM037")
This is working fine on my local windows 10 machine but is unable to covert the code in shinyapps.io
Is this because code IBM037 is not installed on shinyapps.io - is there a solution ?

Thanks
Shami

**Comment by alandipert** [comment]
Is it possible for you to perform the conversion on your Windows 10 machine, and then to deploy the converted data to shinyapps.io along with your app? Then you wouldn't need to perform the conversion on shinyapps.io and could avoid this problem.

**Comment by shamigupta** [comment]
No.. I would need multiple users to upload similar data and see results.. thats why had to deploy the app

**Comment by alandipert** [comment]
Ah, I see what you mean. Unfortunately I'm not aware of a workaround, but there are better places to ask.

If you have a paid account (Starter, Basic, Standard, or Pro), please file a support ticket via https://support.rstudio.com. If you have a Free account, please post to the RStudio Community with the shinyappsio tag: https://community.rstudio.com/tags/shinyappsio.

I'm closing this issue since it's related to the shinyapps.io service and not to the shiny package itself, but please don't hesitate to comment further.
