### ISSUE TITLE
SSL Handshake Issue Causing WebSocket Timeout

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/shiny#2426]
I have deployed my Shiny application via Cloud Foundry and the R Buildpack and I have noticed at times that a websocket connection is not established (JS console error: Websocket connection to 'url' failed: WebSocket opening handshake timed out) when I navigate to the https URL. I believe there is an issue with the SSL handshake yet I am unsure how to mitigate. I began researching and found articles such as these, yet I am unsure if this is correct for Shiny. Is this a known issue? Thank you

https://stackoverflow.com/questions/30732269/websocket-connection-failed-websocket-opening-handshake-was-canceled
https://stackoverflow.com/questions/23404160/why-does-my-wss-websockets-over-ssl-tls-connection-immediately-disconnect-w

**Comment by alandipert** [comment]
Hi, thank you for the report, but this sounds like an issue particular to your app or Cloud Foundry and not necessarily to Shiny itself.

Generally, this kind of thing can happen when an application server is under-powered. I'm not familiar with Cloud Foundry, but is it possible to allocate more compute resources to your application?

I'm closing this because it's most likely not a problem with Shiny, but please don't hesitate to continue commenting here. You may also consider posting a new topic to [Community](https://community.rstudio.com/), where there might be other Cloud Foundry users.
