### ISSUE TITLE
New command to run remote Shiny apps

### ISSUE THREAD

**Issue by helgasoft** [rstudio/shiny#2444]
It all started with our second Shiny app in a gist. The first one was showing fine since it was named **app.R**:
```
runGist('https://gist.github.com/helgasoft/0353c54a3b50deceeb18afc1b0a7f460')
#  ye-ye!
```
The second one could not have the same name in Github, so when we tried to run it, that did not work.
```
runGist('https://gist.github.com/helgasoft/7d702d52d827dd20c460ca4ba664011e')
# bummer, error "App dir must contain either app.R or server.R."
```
Turns out _runGist_ is calling _runUrl_ which expects a zip file with _app.R_ inside.
So the available, but restricted R commands to run remote Shiny apps currently are:
1) runGist() - works only with Github gists named 'app.R'
2) runUrl() - accepts only zip/tar files with 'app.R' inside
3) runGitHub() - the app is in a repo

How about **executing apps directly from single remote source files**?  
With **any name**, like 'app1.R', 'my.app' or 'shiny.pride' ?
Here is a custom function to do that
```
shiny_url_run <- function(url) {
  require(shiny)
  file <- tempfile(fileext='.R')
  download.file(url, file, cacheOK=F)
  obj <- shiny:::shinyAppDir_appR(basename(file), dirname(file))
  runApp(obj, quiet=T)
}
# glitch: after termination it ends up in the debugger and needs Stop to be pressed
```
You can try it in Rstudio. That's how we did run our second (third,etc) Shiny app gist.
```
source('https://helgasoft.com/code/shrun.R')
shiny_url_run('https://gist.github.com/helgasoft/7d702d52d827dd20c460ca4ba664011e/raw/39b83d78a9d63ab609f691927ef65a60dddb4111/dygaps.R')
```
Now, wouldn't it be nice to have a **new command** called 'runShiny' or 'runNoZip' or 'runFrom' doing the same thing in the next version of Shiny ?
Any thoughts from the core team ?
Hope to get the ball rolling...

**Comment by alandipert** [comment]
Hi, thanks for the report and idea, but I'm not sure you're correct that gists can't have the same filename. For example, here are two different gists, each named `app.R`:

* https://gist.github.com/alandipert/b7924d80aed3a6d3b90107cb3167d5bf
* https://gist.github.com/alandipert/4794de3ac75879ce4efadec50489e6cc

I'm able to run them both:
* `runGist("b7924d80aed3a6d3b90107cb3167d5bf")`
* `runGist("4794de3ac75879ce4efadec50489e6cc")`

When I want to run an arbitrary URL as a Shiny app, I can do this:

`print(source("https://gist.github.com/helgasoft/7d702d52d827dd20c460ca4ba664011e/raw/39b83d78a9d63ab609f691927ef65a60dddb4111/dygaps.R"))`

`print()` is necessary because `source()` returns [invisibly](https://www.rdocumentation.org/packages/base/versions/3.6.0/topics/invisible).

Unless I misunderstand your request &mdash; which is entirely possible! &mdash; it seems like what you hope to achieve is already quite expedient. I'm also not sure it would be a good idea for us to condone Shiny app sources named anything other than `app.R`/`server.R`+`ui.R`, since many of our tools depend on that convention.

Anyway, let me know if this was helpful, or if I'm missing something.

**Comment by helgasoft** [comment]
@alandipert, thank you - spot on !  
Two gists with filename ```app.R``` now works. I tried couple of months ago and it did not allow me to save. Or my memory is leaking again...
_print(source())_ is a neat command trick and indeed accomplishes what I wanted to do.  So let ```app.R``` live forever.
