### ISSUE TITLE
Top level reactivity simulation

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2518]
I think it would be useful to have some exported API to make it easy to simulate reactivity at the console:

```R
simulation <- new.env(parent = emptyenv())
simulation$id <- NULL

simulation_on <- function() {
  if (!is.null(simulation$id)) {
    stop("Simulation already active", call. = FALSE)
  }
  
  options(shiny.suppressMissingContextError = TRUE)
  simulation$id <- addTaskCallback(function(...) {
    shiny:::flushReact()
    TRUE
  })
  invisible()
}

simulation_off <- function() {
  if (is.null(simulation$id)) {
    stop("Simulation not active", call. = FALSE)
  }
  
  options(shiny.suppressMissingContextError = FALSE)
  removeTaskCallback(simulation$id)
  invisible()
}
```

Obviously this is only an approximation because it will only flush after a top level event, but this seems like

**Comment by hadley** [comment]
I can't see how to make this approach work inside of knitr, which is the case that I mostly care about. The top level handlers are only ever called from [`Rf_ReplIteration`](https://github.com/wch/r-source/blob/d9eb4f536b0b820ae10545ac513d804bf41800f8/src/main/main.c#L267), and there are no R level hooks to retrieve them (+ evaluate is already complex enough with adding this as well).

Instead, what if `reactiveValues$set` (and the equivalent for `reactiveVal`) automatically called `flushReact` when some global option was set?

**Comment by jcheng5** [comment]
For console use, there's a version of this at `shiny:::setAutoflush(TRUE)` already. Besides calling `flushReact` it also executes elapsed timers (based on `invalidateLater`, `reactiveTimer`) but only at the moment when `addTaskCallback`'s callback is invoked. To support timers properly, `later` probably needs to get involved.

Here's an inefficient version that works by polling:

```r
options(shiny.suppressMissingContextError = TRUE) # setAutoflush(TRUE) doesn't do this for you
shiny:::setAutoflush(TRUE)
local({
  POLL_INTERVAL <- 0.1
  stopped <- FALSE
  periodic_flush <- function() {
    if (stopped) return()
    shiny:::timerCallbacks$executeElapsed()
    shiny:::flushReact()
    later::later(periodic_flush, POLL_INTERVAL)
  }
  periodic_flush()
  # Returns a function you can call to terminate the loop
  function() { stopped <<- TRUE }
})
```

**Comment by jcheng5** [comment]
Could the knitr case be handled by injecting a knitr output hook? Our hook would delegate to the original output hook, but also do a `shiny:::flushReact` and capture/format that output?

One question I'd have is whether a knitr output hook is called for every top-level expression, even if that expression returns an invisible result.

**Comment by hadley** [comment]
I got reasonably deep into the evaluate code, and I'm fairly certain there's no easy way to get it to work from the knitr side.

**Comment by jcheng5** [comment]
> Instead, what if `reactiveValues$set` (and the equivalent for `reactiveVal`) automatically called `flushReact` when some global option was set?

There are a couple of things that make me uncomfortable about this:

1. Reactive values can mutated inside of reactive expressions and observers. Until now, the fact that `flushReact` is only ever called from the event loop (think of `addTaskCallback` and `later` as counting as event loops), i.e. while no user code is executing, saves us from worrying about re-entering `flushReact` in the middle of an observer. With this proposed change, `rv$x <- ...` in the middle of an observer would cause arbitrary code to run, which is just fundamentally unsafe.
2. Much less of a big deal than number 1, but, setting multiple reactive values before returning control to the top-level usually results in a single flush; this will cause individual flushes. I think individual flushes is defensible behavior in isolation (actually _I_ don't believe it's defensible but reasonable people disagree with that), but it is different than what will happen in Shiny.

So that's why I don't think it's a good idea to add this to Shiny, even as an option; you'd have to be so careful to use it within very specific boundaries that we don't have the ability to enforce. However, if you want to do it for your own purposes, in your own knitr documents, you could just do that by overwriting the `reactiveValues` and `reactiveVal` functions with your own versions that do call `flushReact` right after write.

```r
reactiveVal <- function(value = NULL, label = NULL) {
  if (missing(label)) {
    call <- sys.call()
    label <- shiny:::rvalSrcrefToLabel(attr(call, "srcref", exact = TRUE))
  }
  
  rv <- shiny::reactiveVal(value, label)
  function(x) {
    if (missing(x)) {
      rv()
    } else {
      on.exit(shiny:::flushReact(), add = TRUE, after = FALSE)
      rv(x)
    }
  }
}

reactiveValues <- function(...) {
  rv <- shiny::reactiveValues(...)
  class(rv) <- c("rv_flush_on_write", class(rv))
  rv
}

`$<-.rv_flush_on_write` <- function(x, name, value) {
  on.exit(shiny:::flushReact(), add = TRUE, after = FALSE)
  NextMethod()
}
```

This doesn't even begin to address `invalidateLater` inside knitr, but I'm not sure what behavior we'd even want for timers within knitr rendering--my mental model of static knitr documents is that conceptually they're rendered within a single tick of the event loop.

**Comment by hadley** [comment]
Yeah, totally fair. 

What if shiny had 

```R
simulation_on <- function() {
  options(shiny.suppressMissingContextError = TRUE)
  shiny:::setAutoflush(TRUE)

  invisible()
}

simulation_off <- function() {
  options(shiny.suppressMissingContextError = FALSE)
  shiny:::setAutoflush(FALSE)
  invisible()
}
```

Then I could pretend to call those functions in the book, while behind the scenes actually using the hack with `reactiveValues()` etc.?

**Comment by jcheng5** [comment]
Yeah, something like that would be just fine with me. I think the function name should have something to do with "console" or "interactive", and maybe it would make sense to allow flipping of these two settings (missing context error, and auto flush) separately.

**Comment by hadley** [comment]
How about something like `consoleReactive(TRUE, TRUE)` and `consoleReactive(FALSE, FALSE)`?

**Comment by hadley** [comment]
Is there some way to set a default reactive context so that I can shut that context down when the reactive console is turned off?
