### ISSUE TITLE
How to run shinyApp even in a web browser after closing the session in R-studio ?

### ISSUE THREAD

**Issue by smitpate08** [rstudio/shiny#2532]
Hi,

I have basic data entry shiny app that takes few inputs from user and display it in main panel,similar to [this app](https://daattali.com/shiny/mimic-google-form/). My issue is I can run the app in a browser and also in current R-session, but whenever I exit out from my R-session. My browser session also gets killed.Is there a way to still have browser session running,so user can input the data in shinyapp when R-session is killed ?

Thanks in advance,

**Comment by shrektan** [comment]
Run it in a separate session.  You can use the RStudio terminal to do that easily.

**Comment by cpsievert** [comment]
Shiny needs a R process running *somewhere* in order to serve the app. As @shrektan suggests, you could use a terminal window and serve the app with a command like this: `Rscript -e "shiny::runApp('/your/shiny/app/path')"`

If you don't want this command to block the console, you could use something like [`nohup` to run the process in the background](https://unix.stackexchange.com/questions/103731/run-a-command-without-making-me-wait).
