### ISSUE TITLE
[issue] reactive expression gets stuck for no apparent reason

### ISSUE THREAD

**Issue by vttrifonov** [rstudio/shiny#2546]
I have the following simple setup
 
    x1<-reactiveVal()
    x2<-reactiveVal()
    x3<-reactive({
       message("a")
       req(isolate(x1()))
       message("b")
       x2()
    })
    observe(x3())

The following sequence of interactions cause the `x3` expression to become stuck and not to respond to changes in `x2`.

First I flush the initialization events

    shiny:::flushReact()

This prints out "a" as expected. `x1` is `NULL` so the `req` fails silently and no "b" is printed out.

Then I change the value of `x2`

    x2(1)
    shiny:::flushReact()

This does not produce an output although I was expecting to see "a" printed out. This is very suspicious, but`x1` is `NULL` at this point, so in some sense it might be correct: besides the side effect of printing, executing `x3` will again fail silently.

Change the value of `x1`

    x1(2)
    shiny:::flushReact()

No output produced which is expected as `x3` does not depend on `x1`.

Again change the value of `x2`

    x2(3)
    shiny:::flushReact()

No output produced. At this point `x1` is not `NULL` and `x2` has changed, so I was expecting to see "a" and "b" printed out. The `x3` expression has become non-reactive.

Notice that rewriting the above to use `eventReactive` instead of `isolate`, makes the example work as intended and all output is as expected. 

It seems that the particular usage of `req` and `isolate` creates a situation in which `x3` is non-reactive. Either there is something particular about that usage that makes the example "quirky" (this has to be documented) or it seems that there is a bug.

**Comment by schloerke** [comment]
This is expected behavior.

`req` is a very invasive function that will stop all execution of a reactive function body.  If code has not been reached and the `req` fails, the remaining code will not be executed.  This has pros and cons.  Pro: the dynamic set up of dependencies can be dynamically changed from execution to execution.  Con: If a dependency has not been established by the time a `req` fails, it will not be established.

In your example above... Once the `req` fails the very first time `x3` is executed, there have been no reactive components registered as a dependency.  Therefore, `x3` will never update due to a change in `x2`.

-----------------------------

I propose a code flow change for your example.  This will cause `x3` to always recalculate when `x2` updates, but will not display `message("b")` unless `x1` has a `TRUE`-thy value at execution time.

```r
x1<-reactiveVal()
x2<-reactiveVal()
x3<-reactive({
  message("a")
  x2_val <- x2()
  req(isolate(x1()))
  message("b")
  x2_val
})
observe(x3())
```

**Comment by vttrifonov** [comment]
Thanks. This makes sense. I played with this and it seems that this actually is true for all exceptions (no dependencies established past the exception), not just `req`. In any case, it might be good to make this more explicit in the documentation for `req`: we better have all dependencies established by the time it throws or otherwise expression will get stuck. It took me a bit to find out what is going in my real world situation with a decent size reactive network.

**Comment by schloerke** [comment]
If you're ever stuck on the reactivity... check out [`reactlog`](https://rstudio.github.io/reactlog/).

```r
options(shiny.reactlog = TRUE)

# run app
shiny::runExample("01_hello")
# click around
# cmd + F3  or ctrl + F3
```

It will help display what shiny is thinking and will show you when dependencies are captured.
