### ISSUE TITLE
observeEvent strange behavior with reactivity.

### ISSUE THREAD

**Issue by sada1993** [rstudio/shiny#2589]
Unsure if this is the intended behavior or a bug. But when we run the code below with `c(input$load.Rdat)` in the `observeEvent()` call, the app loads data on startup. Instead, if we simply put `input$load.Rdat` in the `observeEvent()` call, the app does not load the data on startup. 

The expected/logical behavior is the app should **not** load the data in either case on start up because the button has not been pressed.

Also noticed the same behaviour can be replicated if we replace `ovserveEvent(c(input$load.Rdat),{...})` with `observe({req(c(input$load.Rdat))...})`.

### System details

Output of `sessionInfo()`:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       packrat_0.5.0    digest_0.6.19    later_0.8.0      mime_0.7         R6_2.4.0         xtable_1.8-4     magrittr_1.5    
 [9] evaluate_0.14    promises_1.0.1   rmarkdown_1.13   tools_3.5.3      httpuv_1.5.1     xfun_0.7         yaml_2.2.0       rsconnect_0.8.13
[17] compiler_3.5.3   htmltools_0.3.6  knitr_1.23 
```

### Example of App loading Data on start up

 

```R
library(shiny)

ui <- fluidPage(
  inputPanel(
    actionButton('load.Rdat','Load all from Rdat file')
  ),
  tabsetPanel(type = "tabs",
              tabPanel("table A", dataTableOutput("toA"))
  )
)

server <- function(input, output, session) {
  rv <- reactiveValues(df.A = NULL)
  
  output$toA  <- renderDataTable({
    req(rv$df.A)
    rv$df.A
  })
  
  observeEvent(c(input$load.Rdat), {
    rv$df.A <- mtcars
  })
}

shinyApp(ui, server)
```
### Example of App not loading Data on start up

```
library(shiny)

ui <- fluidPage(
  inputPanel(
    actionButton('load.Rdat','Load all from Rdat file')
  ),
  tabsetPanel(type = "tabs",
              tabPanel("table A", dataTableOutput("toA"))
  )
)

server <- function(input, output, session) {
  rv <- reactiveValues(df.A = NULL)
  
  output$toA  <- renderDataTable({
    req(rv$df.A)
    rv$df.A
  })
  
  observeEvent(input$load.Rdat, {
    rv$df.A <- mtcars
  })
}

shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
This is expected behavior. Consider this minimal example:

```r
library(shiny)

ui <- fluidPage(
  actionButton("btn", "Click me")
)

server <- function(input, output, session) {
  
  observeEvent(input$btn, {
    message("observeEvent")
    print(input$btn)
  })
  
  observe({
    message("observe")
    print(input$btn)
  })

}

shinyApp(ui, server)
```

```r
#>  Listening on http://127.0.0.1:7976
#>  observe
#>  [1] 0
#>  attr(,"class")
#>  [1] "integer"                "shinyActionButtonValue"
```

First, notice that `input$btn` has a class of `"shinyActionButtonValue"`. [This isn't yet well documented](https://github.com/rstudio/shiny/pull/2551), but a `"shinyActionButtonValue"` is different from an ordinary integer in that Shiny considers a value of 0 to be 'falsy', and thus, `observeEvent()` won't trigger when `input$btn` is 0 (on the other hand, `observe()` will trigger because it doesn't care about truthiness). This is `"shinyActionButtonValue"` behavior by design, so that when you provide `input$btn` to an `observeEvent()` it only invalidates when the button is clicked. 

By replacing `input$btn` with `c(input$btn)` you're destroying the `"shinyActionButtonValue"` class so `observeEvent()` will treat like any other integer value.


In terms of a takeaway with regards to your example, if possible, when you initiate `rv`, populate it with the dataset that you want to show on initial load. If you can't do that, I'd use `observe()` instead of `observeEvent()` (this approach would be less efficient than the former)
