### ISSUE TITLE
plotOutput()'s double-click input value isn't set in Firefox

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2620]
To reproduce: Try double-clicking in Firefox with 093-plot-interaction-basic. The input value tied to double-click events is not set.

This issue is a regression from shiny CRAN (v.1.3.2) and the problem was introduced by upgrading jQuery in https://github.com/rstudio/shiny/commit/9a1f7cba6877230dbeb758f32c490f986103cea6. It looks as though the `pending_e.offsetX/Y` values here no longer contain the correct information

https://github.com/rstudio/shiny/blob/02f7a4fdc9976b27e4a522c88c9d483421c46fec/srcjs/output_binding_image.js#L706-L711

Fortunately, I think we can fix the problem by using the more official `pageX`/`pageY` instead to determine if the second click is "too far away"

**Comment by jcheng5** [comment]
I'm not sure I follow. If offsetX/Y have not worked since jQuery 1.5, how was this working with our previous jQuery 1.12?

**Comment by wch** [comment]
@jcheng5 The issue seems to be that `offsetX` and `offsetY` aren't part of each jQuery Event object -- they're inherited from the prototype.

When the first `mousedown` event happens (and when the plot is listening for double-clicks), we save the event object as `pending_e`; if another click happens within some amount of time, and within a certain pixel distance from the first click, then we trigger a `dblclick2` event. The problem is that when the second `mousedown` event occurs, `pending_e` has its `offsetX/Y` values changed to 0. The `pending_e` object itself is unaltered but the prototype somehow gets changed. This happens in Firefox, but not in Chrome or Safari. I think we still need to understand why it's different in Firefox, though, and what exactly changed in the jQuery upgrade.

**Comment by wch** [comment]
We save the first `mousedown` event, and for some reason, its `offsetX/Y` values get zeroed out when the second `mousedown` occurs. Not sure why this is happening just in Firefox with the new version of jQuery.

**Comment by cpsievert** [comment]
FWIW, this doesn't seem to be a problem for jQuery 2.2.4, so I have feeling this came about in jQuery 3.0.0 (maybe with this commit https://github.com/jquery/jquery/commit/e61fccb9d736235b4b011f89cba6866bc0b8997d)
