### ISSUE TITLE
In some cases user-code may not have access to initShiny methods

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2630]
As of jQuery 3.0, [document-ready handlers are now asynchronous](https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous), which means it's possible for the methods in `initShiny` to not be available to downstream user-code because of this:

https://github.com/rstudio/shiny/blob/02f7a4fdc9976b27e4a522c88c9d483421c46fec/srcjs/init_shiny.js#L511-L515

For a minimal example of where this becomes of problem:

```r
library(shiny)
library(leaflet)
shinyApp(
  ui = leaflet() %>% addTiles(),
  server = function(input, output, session) {}
)
```

Before jQuery 3.0, `initShiny` would be called before leaflet's javascript executes; however, after jQuery 3.0, `initShiny` is called after leaflet's javascript, so not all of Shiny's methods (e.g., `onInputChange`) is not available to leaflet

**Comment by cpsievert** [comment]
And also, to help clarify when this becomes an issue, I believe this problem surfaces whenever you have a statically rendered object in the UI that's expecting to be able to use the `initShiny` methods. Here's a plotly minimal example as well:

```r
library(shiny)
shinyApp(
  ui = plotly::plot_ly(x = 1, y = 1),
  server = function(input, output, session) {}
)
```

**Comment by jcheng5** [comment]
After investigation with @cpsievert @schloerke @alandipert, the crux of the issue is that `$(fn)` used to invoke `fn` synchronously from a `DOMContentLoaded` handler, but now, a `setTimeout` is inserted between `DOMContentLoaded` and `fn`.

In other words, jQuery 1.x was like:

```javascript
function $(callback) {
  document.addEventListener("DOMContentLoaded", callback);
}
```

but jQuery 3.x is like:

```javascript
function $(callback) {
  document.addEventListener("DOMContentLoaded", () => {
    setTimeout(callback);
  }
}
```

Meanwhile, Shiny (both 1.3.2 and 1.4.0) has code like this:

```javascript
$(function() {
  setTimeout(init_shiny, 1);
});
```

While htmlwidgets+leaflet has code that is (effectively) like this:

```javascript
document.addEventListener("DOMContentLoaded", function() {
  setTimeout(updateBounds, 1);
});
```

where it's important for `init_shiny` to be called before `updateBounds`.

Three options we discussed for fixing this:

1. Shiny could stop using `$()` and switch to listening for the `DOMContentLoaded` event directly. The downside is that 3rd party code that calls `$()` and expects Shiny to init after that, will break.
2. HTMLWidgets could start using `$()` instead of a `DOMContentLoaded` event listener. However, HTMLWidgets doesn't currently take a jQuery dependency, and it'd be nice to continue not to.
3. HTMLWidgets could use `$()` if _someone else_ loaded `window.jQuery` first; and fall back to `DOMContentLoaded` otherwise.

**Comment by jcheng5** [comment]
I forgot, someone also suggested adding a feature to shiny.js where you could be notified after `init_shiny` completes, which could then be used by htmlwidgets/leaflet.

**Comment by schloerke** [comment]
It seems like option 3 and 4 are similar in approach.

I like the idea of a `shiny_is_ready` method as it is more explicit to what
is happening and when it is happening.

**Comment by cpsievert** [comment]
FWIW, https://github.com/ramnathv/htmlwidgets/pull/345 does appear to fix the issue, at least for htmlwidgets. At the moment, I think I'm in favor of the following:

* Do an htmlwidgets release along with the other releases (we've already been testing with master)
* Default to jQuery 1.x and provide an opt-in to 3.x

I'm not sure if we need to create a new event. I think third-party JS could use the existing `shiny:bound`, which triggers when `initShiny` executes:

https://github.com/rstudio/shiny/blob/02f7a4fdc9976b27e4a522c88c9d483421c46fec/srcjs/init_shiny.js#L38-L42

**Comment by wch** [comment]
Can you also bump the htmlwidgets version? That will allow shiny to detect the version on load, and if htmlwidgets is the old version, we can emit a message telling people they should upgrade.

I just had a quick discussion with @jcheng5 and we were thinking of making jQuery 3 the default, but also providing an option to use jQuery 1 . That way we'll still move most people forward, but if there are any other unforeseen consequences, they'll have the ability to use the old version. This will also be more effective in finding any remaining issues with the upgrade.

**Comment by cpsievert** [comment]
Closing in favor of #2635 (the jQuery 3.x regression has been addressed)
