### ISSUE TITLE
Updating Websocket library to follow HTTP REDIRECT

### ISSUE THREAD

**Issue by falaki** [rstudio/shiny#2687]
Hi Shiny development team. First, thanks for the awesome work.

Shiny uses [websocket-driver](https://github.com/rstudio/shiny/blob/f85479ba11e49dc21b2f06f2e84e0a228b5639f7/tools/yarn.lock#L2369) node module for Websocket functionality. This library does not seem to support HTTP REDIRECTs (301 or 302). Is it possible to switch to a different websocket library that does support following HTTP REDIRECTs? For example https://github.com/websockets/ws recently [added support](https://github.com/websockets/ws/pull/1490/files) for this. This library seems to be more active and better maintained compared to websocket-driver. 

If maintainers think this is an option, and don't see any major blockers, we would be happy to submit a patch. Also if you have alternative suggestions, we would love to hear.

**Use case**
We are working to enabling developing and viewing Shiny applications on a remote instance that is being accessed using a Jetty HTTP proxy. The Jetty handler for websocket proxying is under a different end-point than the HTTP proxy. So the proxy will send a redirect response (302) to upgrade request that Shiny sends. We were hoping Shiny would follow the redirect.

**Comment by falaki** [comment]
It seems https://github.com/websockets/ws  does not work inside the browser, so I am wondering if there is any options?

**Comment by wch** [comment]
The [websocket-driver](https://github.com/rstudio/shiny/blob/f85479ba11e49dc21b2f06f2e84e0a228b5639f7/tools/yarn.lock#L2369) you linked to is not used directly by Shiny; the stuff in the tools/ subdirectory is only used for building and minifying the Javascript artifacts. It happens to be brought in as a dependency of some of the other build tools.

Are you trying to change the websocket behavior on the client side?

On the client, we use the browser's `WebSocket` implementation when running Shiny directly. If the hosted environment is  one of our hosted products (Shiny Server or Connect), then it uses SockJS instead of a WebSocket.

**Comment by falaki** [comment]
Thanks for clarifying.
