### ISSUE TITLE
Using `testModule` breaks when module calls another

### ISSUE THREAD

**Issue by akgold** [rstudio/shiny#2712]
```R
module <- function(input, output, session) {
  callModule(module2, "module2")
}
module2 <- function(input, output, session) {
}
testModule(module)
```
Error output
```
Error in session$makeScope(id) : attempt to apply non-function
```

**Comment by alandipert** [comment]
Thank you for the report. Like #2708 I think this could be because `MockShinySession` is missing a method, in this case `makeScope()`.

**Comment by alandipert** [comment]
@akgold with @wch's guidance I think I was able to fix this, and the fix is on the `test-nested-modules` branch if you have a moment to try it out.

I'd also be curious to know how you ran into this problem, and if nested modules are something you've worked with before. I'd like to add a test for this, and ideally the test would be based on a usage or pattern that exists in the wild.

Thanks again for the report, and in advance for the additional context.

**Comment by akgold** [comment]
Hi @alandipert , 

Getting a different error now: 

```r
remotes::install_github("rstudio/shiny", "test-nested-modules")
library(shiny)

module <- function(input, output, session) {
  
  output$var <- 3
  callModule(module2, "module2")
}

module2 <- function(input, output, session) {
  output$var2 <- 2
}

testModule(module, {
  print(output$var)
})
```
```
Error in func(self, name) : could not find function "func"
```

This is a use pattern from a real app. In this case, the use pattern was having users submit a form. I have a module that houses the form itself, which calls a nested module when the form is submitted. In this case the submit logic is complicated enough that I wanted to be able to separate it out from the form.

I have another nested module (in a different app) that's conceptually similar. The app displays information about a class, and I house the logic for the various updates that are allowed in a separate module.

**Comment by alandipert** [comment]
@akgold thanks for that example. I think the error you saw is because a statement like `output$var <- 3` would need to be something like `output$var <- renderText(3)` to work, generally. 

In a regular old Shiny module, doing that would normally produce an error message like this:
```
 Error in .subset2(x, "impl")$defineOutput(name, value, label) : 
  Unexpected numeric output for var 
```

However, since `testModule()` and various new code paths are involved, you're seeing a lame error message. I pushed a commit that should improve the error message.

**Comment by akgold** [comment]
Beautiful! This works nicely on my toy example now. Will be working on a real implementation after the holiday.
