### ISSUE TITLE
We should be able to overwrite the bootstrap stylesheet

### ISSUE THREAD

**Issue by Chrisjb** [rstudio/shiny#2794]
Quite often when using a bootstrap theme css and reading it into shiny with `theme = boostrap.css`, I find styles being overwritten by the default bootstrap stylesheet. It would be great if we could avoid conflicts between the stylesheets altogether by allowing an option to replace the default stylesheet with the stylesheet set in `theme`. 

It might go something like:
```
ui <- fluidPage(class='p-0',  theme = "cosmo-bootstrap.min.css",
                           replace = TRUE
```

**Comment by cpsievert** [comment]
You may want to start looking into the new bootstraplib package, which will be our official way of customizing Bootstrap CSS.

> I find styles being overwritten by the default bootstrap stylesheet.

I'm guessing that might be happening because, in some cases, Bootstrap wants to set `!important` flags. If you need to overwrite those for whatever reason than you probably need to also put an `!important` in your css
