### ISSUE TITLE
Input binding for <input type="datetime-local">

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#290]

**Comment by wch** [comment]
I think the `<input type="datetime-local">` in particular isn't going to be very useful, since it's apparently not supported in IE or Firefox.

Do we still need this now that we have date inputs? I suppose it would nice to have *date-time* inputs. There are a couple of those out there, though none of them seem to have built-in support for ranges.

* http://tarruda.github.io/bootstrap-datetimepicker/
* http://eonasdan.github.io/bootstrap-datetimepicker/
* http://www.malot.fr/bootstrap-datetimepicker/

**Comment by bcorwin** [comment]
Any update on this?

**Comment by alandipert** [comment]
Closing because duplicate of #897
