### ISSUE TITLE
Would that be possible to load data based on navigation

### ISSUE THREAD

**Issue by Lobbii** [rstudio/shiny#2903]
Hi, I want to visualize several large datasets, but there would be a memory usage issue if I want to load them at the same time. Would that be possible to load data separately based on navigation panel?

**Comment by wch** [comment]
Outputs in a `tabPanel` are executed only when the panel is visible. Keep in mind, though, that you will have to structure your code so that large objects aren't stored as persistent variables.

For future reference, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

**Comment by Lobbii** [comment]
> Outputs in a `tabPanel` are executed only when the panel is visible. Keep in mind, though, that you will have to structure your code so that large objects aren't stored as persistent variables.
> 
> For future reference, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

Is there a tutorial for loading data based on panel?
