### ISSUE TITLE
Reactivity dependency not working

### ISSUE THREAD

**Issue by lijian007** [rstudio/shiny#3120]
The reactivity invalidation/update failed in the following example.  In the example code, output$plot is dependent on the reactive value net() which in turn is dependent on input$submit. However, in certain situations, (change the price value to 10, click submit,  then change back to 100, and click submit), the dependency does not work (the plot is not recalculated).
 

### System details

Browser Version: recent google chrome, but this is not browser specific

Output of `sessionInfo()`:
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5          withr_2.3.0         digest_0.6.25      
 [4] later_1.1.0.1       mime_0.9            R6_2.4.1           
 [7] xtable_1.8-4        jsonlite_1.7.1      magrittr_1.5       
[10] rlang_0.4.7         promises_1.1.1      tools_4.0.2        
[13] tinytex_0.26        fastmap_1.0.1       httpuv_1.5.4       
[16] xfun_0.18           compiler_4.0.2      htmltools_0.5.0    
[19] shinyFeedback_0.3.0

```
# sessionInfo() output goes here
```

### Example application *or* steps to reproduce the problem
1. run the example code. 
2. change the value of price to 10, click submit. 
3. change the value of price to 100, click submit

```R
#example use of isolate: update only on submit

library(shiny)
options(shiny.reactlog = TRUE)
ui <- fluidPage(
  shinyFeedback::useShinyFeedback(),
  numericInput("price", "price", value = 100),
  actionButton('submit','submit'),
  plotOutput("plot")
)
server <- function(input, output, session) {
  observe({
    input$submit
    shinyFeedback::feedbackWarning(
    "price", 
    isolate(input$price<20),
    "input cannot be lower than 20"
  )})
  
  net=reactive({
    input$submit
     isolate(input$price)-20
  })
  output$plot=renderPlot({
    #input$submit  #***this line shouldn't be necessary, as net() is dependent on input$submit
    #however, without this line, if the price is changed to 10 and back to 100, the plot will not show
    req(isolate(input$price>=20))
    barplot(c( net=net(),
               root_of_net=sqrt(net())), col='blue')
  })
  
  
}
shinyApp(ui, server)
```

### Describe the problem in detail
in the example, the plot should be recalculated whenever the submit is clicked because the reactive value net() is dependent on input$submit, however, it is not always the case as explained.

**Comment by lijian007** [comment]
![image](https://user-images.githubusercontent.com/10033619/97725643-cd85f880-1aa4-11eb-9fe2-905064e83413.png)

**Comment by daattali** [comment]
I haven't tried out your code, but from looking at it I think I might know what's happening, which isn't a bug but it certainly is confusing behaviour.

Someone from the shiny team can correct me if this isn't 100% accurate, but the way shiny knows when to re-run a render function is by running its code the first time, and any reactive value it encounters becomes a "trigger" or "reactive dependency".

So looking at your code, because you put `req(isolate(input$price>=20))` inside an isolate, this is what happens:

- As long as the price input is above 20, things work as expected
- The moment price goes below 20, shiny reaches the `req()` statement and fails/returns.
- Because the reactive value inside the `req()` call was isolated, shiny did not register any reactive dependencies here. So shiny doesn't know when to come back to this render function

If you make a reference to `input$submit` or `net()` **before** the req statement, then shiny will register a dependency on those and it will work. If you put them **after** req, then there is simply nothing to re-trigger the reactivity after the req fails. This is you should use `req()` with reactive values.

**Comment by daattali** [comment]
I haven't tried out your code, but from looking at it I think I might know what's happening, which isn't a bug but it certainly is confusing behaviour.

Someone from the shiny team can correct me if this isn't 100% accurate, but the way shiny knows when to re-run a render function is by running its code the first time, and any reactive value it encounters becomes a "trigger" or "reactive dependency".

So looking at your code, because you put `req(isolate(input$price>=20))` inside an isolate, this is what happens:

- As long as the price input is above 20, things work as expected
- The moment price goes below 20, shiny reaches the `req()` statement and fails/returns.
- Because the reactive value inside the `req()` call was isolated, shiny did not register any reactive dependencies here. So shiny doesn't know when to come back to this render function

If you make a reference to `input$submit` or `net()` **before** the req statement, then shiny will register a dependency on those and it will work. If you put them **after** req, then there is simply nothing to re-trigger the reactivity after the req fails. This is you should use `req()` with reactive values.

**Comment by jcheng5** [comment]
@daattali is correct. In this case I'd probably replace that `req(isolate(input$price >= 20))` with `req(net() > 0)`.

**Comment by daattali** [comment]
The way I would handle the reactivity here while still maintaining the behaviour you want is changing the `net` variable to

```
net <- reactive({
    req(input$price >= 20)
    input$price - 20
  })
```

and isolating `net()` in the renderPlot

**Comment by lijian007** [comment]
Thanks that really helped me think through. Actually I revisited the react graphs generated from reactlog, and the dependency of the plot on net() grayed out when input$price is less than 20. This is not a bug.

**Comment by daattali** [comment]
@lijian007 feel free to close this issue (and #3121) if you don't think they are not bugs in shiny

**Comment by lijian007** [comment]
Thanks Dean, I am closing it.
