### ISSUE TITLE
dplyr errors in Shiny should show line numbers

### ISSUE THREAD

**Issue by mutahiwachira** [rstudio/shiny#3250]
(This was originally posted as an issue in tidyverse/dplyr#5636)

**Summary**
Compared to the default behaviour for error messages, `dplyr` error messages are incredible difficult to debug. In multifile Shiny apps, normal error messages (from `[`) will often print the exact file and line where the issue is. `dplyr` doesn't tell you where the error is. In apps with large server files or even multiple sourced server files, this can be a problem and make it very difficult to debug Shiny as you have to go hunting to find the error.

@romainfrancois [mentioned ](https://github.com/tidyverse/dplyr/issues/5636#issuecomment-737294344)that it is the way `vctrs::abort()` is used because when using `base::stop()` the errors are more informative. @hadley said that Shiny needs to make better use of the error handling features in `rlang` and [recommended ](https://github.com/tidyverse/dplyr/issues/5636#issuecomment-758056739)I raise this issue here in the Shiny repo.

Is there any way to change this behaviour in vctrs/dplyr/Shiny so that it prints out some kind of context (file and line) for errors in Shiny? I would be happy to make these changes myself given some guidance - I've never contributed a technical change on a project before but maybe if someone points me in the right direction it could help.

-----

When using dplyr in Shiny, it is quite difficult to debug due to rather opaque messages as compared to `base` and other packages.

Here is an error message in Shiny.
```r
library(shiny)
library(dplyr)

options(shiny.error = NULL)

ui <- fluidPage(
  verbatimTextOutput("example")
)

server <- function(input, output, session) {
  output$example <- renderPrint({
    mtcars[,"wrong_col"]
    
    # mtcars %>% 
    #   select(wrong_col)
    
  })
}

shinyApp(ui, server)
```

```r
# Listening on http://127.0.0.1:7436
# Warning: Error in [.data.frame: undefined columns selected
#  102: stop
#  101: [.data.frame
#   99: renderPrint [C:/Users/<My_Name>/Desktop/testShiny.R#12]
#   98: func
#   82: origRenderFunc
#   81: output$example
#    1: runApp
```

The name of the reactive is printed with the line item in the exact file where the error occured.

Here is the error message when dplyr is used instead.

```r
library(shiny)
library(dplyr)

options(shiny.error = NULL)

ui <- fluidPage(
  verbatimTextOutput("example")
)

server <- function(input, output, session) {
  output$example <- renderPrint({
    #mtcars[,"wrong_col"]
    
     mtcars %>% 
       select(wrong_col)
    
  })
}

shinyApp(ui, server)
```

```r
# Listening on http://127.0.0.1:7436
# Warning: Error in : Can't subset columns that don't exist.
# x Column `wrong_col` doesn't exist.
#   120: <Anonymous>
```

Normally you have to use `rlang::last_error` and look through the summarised trace to find the error. This doesn't work in Shiny because you first have to stop the app and all context disappears so `rlang::last_error()` doesn't work. You might then think to use `options(shiny.error = browser)` and call `rlang::last_error()` from there but that still doesn't work. Instead, if you set the option you have to call the object `e` which contains a `vctrs` object containing the error. The output below is the error above with `options(shiny.error = browser)` set and includes commands called from the console session exploring the `browser()` environment. The `rlang` functions don't work, so you have to call `e`.

```r

Browse[1]> rlang::last_error()
# Error: Can't show last error because no error was recorded yet
Browse[1]> rlang::last_trace()
# Error: Can't show last error because no error was recorded yet
Browse[1]> e
# <error/vctrs_error_subscript_oob>
#   Can't subset columns that don't exist.
# x Column `wrong_col` doesn't exist.
# Backtrace:
#    1. shiny::runApp("C:/Users/<My_Name>/Desktop/testShiny.R")
#    8. shiny:::serviceApp()
#    9. shiny:::flushReact()
#   10. .getReactiveEnvironment()$flush()
#   11. ctx$executeFlushCallbacks()
#   12. base::lapply(...)
#   13. shiny:::FUN(X[[i]], ...)
#   14. shiny:::flushCallback()
#   33. shiny:::run()
#   34. ctx$run(.func)
#   41. env$runWith(self, func)
#   42. shiny:::contextFunc()
#   43. shiny:::`<observer:output$example>`(...)
#   78. shiny:::func()
#   79. shiny:::orig(name = name, shinysession = self)
#   81. shiny:::`output$example`(...)
#   82. shiny:::origRenderFunc(...)
#   98. shiny:::func()
#   99. renderPrint(...)
#   28. dplyr::select(., wrong_col)
#  110. tidyselect::eval_select(expr(c(...)), .data)
#  111. tidyselect:::eval_select_impl(...)
#  119. tidyselect:::vars_select_eval(...)
#  120. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
#  121. tidyselect:::eval_c(expr, data_mask, context_mask)
#  122. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
#  123. tidyselect:::walk_data_tree(new, data_mask, context_mask)
#  124. tidyselect:::as_indices_sel_impl(...)
#  125. tidyselect:::as_indices_impl(x, vars, strict = strict)
#  126. tidyselect:::chr_as_locations(x, vars)
#  127. vctrs::vec_as_location(x, n = length(vars), names = vars)
#  129. vctrs:::stop_subscript_oob(...)
#  130. vctrs:::stop_subscript(...)
```

<details>
-------------
My `sessionInfo()`:
```r
# R version 3.6.2 (2019-12-12)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19041)
# 
# Matrix products: default
# 
# locale:
# [1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252   
# [3] LC_MONETARY=English_South Africa.1252 LC_NUMERIC=C                         
# [5] LC_TIME=English_South Africa.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] dplyr_1.0.2   shiny_1.4.0.2 reprex_0.3.0 
# 
# loaded via a namespace (and not attached):
#   [1] Rcpp_1.0.3       pillar_1.4.3     compiler_3.6.2   later_1.0.0      tools_3.6.2     
# [6] digest_0.6.23    jsonlite_1.6.1   evaluate_0.14    lifecycle_0.2.0  tibble_3.0.3    
# [11] pkgconfig_2.0.3  rlang_0.4.7      cli_2.0.2        rstudioapi_0.11  xfun_0.12       
# [16] fastmap_1.0.1    knitr_1.28       generics_0.0.2   fs_1.5.0         vctrs_0.3.2     
# [21] tidyselect_1.1.0 glue_1.4.1       R6_2.4.1         processx_3.4.1   fansi_0.4.1     
# [26] rmarkdown_2.1    callr_3.4.1      purrr_0.3.3      clipr_0.7.0      magrittr_1.5    
# [31] whisker_0.4      ps_1.3.0         promises_1.1.0   ellipsis_0.3.0   htmltools_0.4.0 
# [36] assertthat_0.2.1 rsconnect_0.8.16 mime_0.8         xtable_1.8-4     httpuv_1.5.2    
# [41] crayon_1.3.4 
```
</details>

**Comment by hadley** [comment]
Minimal reprex:

```R
library(shiny)
library(dplyr)

ui <- verbatimTextOutput("example")
server <- function(input, output, session) {
  output$example <- renderPrint(mtcars %>% select(wrong_col))
}

shinyApp(ui, server)
#> Warning: Error in : Can't subset columns that don't exist.
#> x Column `wrong_col` doesn't exist.
#>   115: <Anonymous>
```

I suspect the problem is an interaction between the post-processing that both shiny and rlang do to the backtrace.

**Comment by nir4most** [comment]
I'm not aware of a formal facility to 'upvote' an issue,... so I'm writing here to promote this as a big deal , that would help immensely in taking the pain out of debugging tidyverse heavy shiny apps.

**Comment by romainfrancois** [comment]
Can `shiny` signal reactivity issues with conditions that don't inherit from `error` ? This way they would not be handled/promoted by the calling handlers in `dplyr`? 

Otherrwise, perhaps `shiny` could use something like `cnd_inherits()` from https://github.com/r-lib/rlang/issues/1293 to identify if a condition originally was caused by a reactivity problem.

**Comment by Steviey** [comment]
+1

**Comment by jcheng5** [comment]
@hadley If you modify your example slightly, so that `renderPrint(mtcars %>% select(wrong_col))` becomes `renderPrint({mtcars %>% select(wrong_col)})` (added curly braces), and set `options(shiny.fullstacktrace=TRUE)` (turning off Shiny's stack trace post-processing), then you do at least get a `renderPrint [app.R#6]`. So I think your suspicion is probably correct.

**Comment by lionel-** [comment]
Since they are currently not integrated I don't think there could be any post-processing interaction between rlang and shiny? My working hypothesis is that Shiny's backtrace handling has trouble with some call stack structures, such as created by `withCallingHandlers(expr, error = function(cnd) stop(cnd))`.

I'm trying to create reprexes but I'm stuck finding a minimal _working_ example. Does anyone know why shiny completely trims the backtrace away here?

```r
library(shiny)

f <- function() g()
g <- function() h()
h <- function() stop("foo")

ui <- verbatimTextOutput("example")
server <- function(input, output, session) {
  output$example <- renderPrint(f())
}

shinyApp(ui, server)
#> Warning: Error in h: foo
#>   [No stack trace available]
```

Is this a bug in `pruneStackTrace()`?

```r
f <- function() g()
g <- function() h()
h <- function() capture()

(res <- f())
#> $calls
#> $calls[[1]]
#> f()
#>
#> $calls[[2]]
#> function() g()
#>
#> $calls[[3]]
#> function() h()
#>
#> $calls[[4]]
#> function() capture()
#>
#>
#> $parents
#> [1] 0 1 2 3

pruneStackTrace(res$parents)
#> [1] TRUE TRUE TRUE TRUE
```

**Comment by Steviey** [comment]
Nothing happens over one year. Very strange for such a big issue. 
How is this possible? What is going on with RStudio and Shiny?

**Comment by jcheng5** [comment]
@Steviey you've shamed me into action :(

---

@lionel- there appears to be a separate issue where pasting an app into the console causes `pruneStackTrace` to kill the whole trace. (Note that your `pruneStackTrace(res$parents)` example is correct--confusingly, `pruneStackTrace` returns `TRUE` to indicate calls that should be _kept_.)

When a Shiny app is launched by letting a `shinyApp()` be printed by the REPL, the stack trace comes back weird. (Mostly investigated using R 4.1.2 and the latest RStudio/Mac daily, but I saw the same problem on R 4.0.5 on an RStudio/Win 1.4 build as well.)

<img width="396" alt="image" src="https://user-images.githubusercontent.com/129551/159074889-41d5650c-7a52-4798-89fc-cfdbad6ba6ad.png">

1. The first item on the stack is `<Anonymous>` with parent `1`. The logic of `pruneStackTrace()` assumes that someone in the stack has parent `0` (see [here](https://github.com/rstudio/shiny/blob/313ae9044d84a27e1fa5b0a708666cd8aeca77e9/R/conditions.R#L419)).
2. To fix that problem, I tried changing that line to `current_node <- min(parents)`, but that just leads to a single frame of `<Anonymous>`, because the second row is parented by itself(!?).

I don't see these symptoms if I launch your code by pasting it into a source document and hitting Cmd+Shift+Enter, nor if I change your code's last line to be `print(shinyApp(ui, server))` and paste that into the console.

Here's a minimal repro of that behavior:

```r
obj <- structure(list(), class = "badprint")

print.badprint <- function(x, ...) {
  withCallingHandlers(
    stop("boom"),
    error = function(e) {
      parents <- sys.parents()
      call_names <- shiny:::getCallNames(sys.calls())
      print(tibble::tibble(parents, call_names))
    }
  )
}

# Now type `obj` in the console
```

```
> obj
# A tibble: 6 × 2
  parents call_names         
    <int> <chr>              
1       1 <Anonymous>        
2       2 print.badprint     
3       2 withCallingHandlers
4       2 stop               
5       0 .handleSimpleError 
6       5 h                  
```

---

Back to the original problem: the problem again is in `pruneStackTrace`. In the dplyr cases, there are some stack frames at the end that have a `0` parent, which makes all of the actually interesting parts of the tree be considered an "older sibling" branch which is safe to throw away.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/129551/159077562-6d0824d6-660d-4e90-9511-c366dd1fc09a.png">

There's a function that runs before `pruneStackTrace` that removes frames from the end of the list that seem noisy/unhelpful. I wonder if some rlang-awareness in there is the right way to tackle this problem? i.e. drop these problematic frames before pruning?

**Comment by jcheng5** [comment]
Indeed, adding `"<Anonymous>", "cnd_signal", "signal_abort", "signalCondition"` to the list of callnames to drop in `dropTrivialFrames` makes the original repro that started this thread return a helpful stack trace:

```
Warning: Error in select: Can't subset columns that don't exist.
x Column `wrong_col` doesn't exist.
  101: %>%
  100: renderText [~/.active-rstudio-document#14]
   99: func [/Users/jcheng/Development/shiny/R/utils.R#1451]
   86: renderFunc [/Users/jcheng/Development/shiny/R/shinywrappers.R#263]
   85: output$example [/Users/jcheng/Development/shiny/R/shinywrappers.R#133]
    4: runApp [/Users/jcheng/Development/shiny/R/runapp.R#388]
    3: print.shiny.appobj [/Users/jcheng/Development/shiny/R/shinyapp.R#553]
    1: source
```

**Comment by jcheng5** [comment]
This minimal repro displays both problems (1: printing objects at the console results in the stack trace starting with the first two frames pointing to themselves as parents, 2: `rlang::abort` results in frames at the end of the stack with parent `0`):

```r
obj <- structure(list(), class = "badprint")

print.badprint <- function(x, ...) {
  withCallingHandlers(
    rlang::abort("boom"),
    error = function(e) {
      parents <- sys.parents()
      call_names <- shiny:::getCallNames(sys.calls())
      print(tibble::tibble(parents, call_names))
    }
  )
}

# Now type `obj` in the console
```

<img width="216" alt="image" src="https://user-images.githubusercontent.com/129551/159078885-65c226e9-6d4a-41ae-8259-f6f519e0a48e.png">

**Comment by lionel-** [comment]
> I wonder if some rlang-awareness in there is the right way to tackle this problem? i.e. drop these problematic frames before pruning?

Could you perhaps transform the backtrace embedded in the `rlang_error` in the `trace` field? This is structured as a data frame with a `visible` column that indicates frames to hide. After subsetting out the hidden frames, you could attempt simplification on the `call` and `parent` columns. See https://github.com/r-lib/rlang/blob/22fe9e9d729d562fcfd580c7a350f56d7a864639/R/trace.R#L1016 for more info.

Note that as we move to chained errors, more backtraces will include parasite handling frames, possibly with some trailing user frames. There are many possibilities (see https://github.com/r-lib/rlang/blob/main/man/notes/handling-introspection.R) so it would be simpler and more robust to let rlang figure out which frames to hide.

Regarding backtrace simplification (removal of sibling branches), rlang could also export a function to do it so Shiny doesn't have to reimplement the logic.

**Comment by jcheng5** [comment]
@lionel- That's super helpful, thanks. I'll see if I can use that data frame to replace the logic in `pruneStackTrace` while leaving the rest of the logic intact.

**Comment by jcheng5** [comment]
@lionel- What I was able to gather was that the `trace` data frame can be simplified with `rlang:::trace_simplify_branch`. I actually found that I was not happy with that simplification logic. There were parts of the branch that were simplified away that I don't think should have been. Specifically, certain dplyr operations seem to introduce an `0` into the parents, I believe via [this code](https://github.com/r-lib/rlang/blob/22fe9e9d729d562fcfd580c7a350f56d7a864639/R/trace.R#L258-L263), and almost everything before that is pruned. That seems like a minor bug for rlang in general, but a more major one for Shiny since the calling context tends to be less obvious and often more important.

To summarize the problem as I understand it now: For various reasons, `sys.parents()` can be self-referential or have the value of `0` (the latter being expected for the first frame but not for frames nearer the bottom). `shiny:::pruneStackTrace()` did not deal with either situation, but naively expected a well-formed tree, which led to the entire stack trace being pruned. `rlang:::trace_simplify_branch` deals with the self-referential entries by changing them to `0`, but then did not have any special handling for `0`, leading to all but the bottom branch being pruned. (In this specific case, it's more correct not to prune the other `0` branches since their sibling-ness was induced artificially.)

For now, I have created https://github.com/rstudio/shiny/pull/3602 which does appear to fix the problem, though it's still a bit unsatisfying to me. I think there must be a more intelligent way to deal with self-referential and `0` branches than simply never pruning them; I really hope we can do something like repair the tree and then prune as usual.

**Comment by lionel-** [comment]
> Specifically, certain dplyr operations seem to introduce an 0 into the parents

Do you have a reprex handy? This may be because of an R callback that doesn't evaluate in the current environment. I've been fixing these instances in vctrs to preserve backtrace ancestry but this is a WIP.

The 0-parent frames occur when a closure is evaluated in an environment that doesn't belong to a frame currently on the stack. These can occur through `do.call()` or the C-level `eval()` function. There is no way to fix these 0-parent to something else. Patching the parent to point to the previous frame would produce incorrect backtraces for users working in the global env, e.g.:

```r
f <- function(expr) tryCatch(expr)
g <- function() rlang::trace_back()

f(g())
#>     ▆
#>  1. ├─global f(g())
#>  2. │ └─base::tryCatch(expr)
#>  3. │   └─base tryCatchList(expr, classes, parentenv, handlers)
#>  4. └─global g()
```

Would become

```r
#>     ▆
#>  1. └─global f(g())
#>  2.   └─base::tryCatch(expr)
#>  3.     └─base tryCatchList(expr, classes, parentenv, handlers)
#>  4.       └─global g()
```

So developers have to fix incorrect 0-parent frames, either by using the base-level `eval()` function (which never creates a sibling node, but the `eval()` call must be evaluated in the bottom env), or by evaluating in the bottom env directly. This is not always entirely trivial but workarounds exist for the more complex cases.

Regarding self-referential frames, I seem to recall that this is a bug in R that I was planning to fix, but I can't find my notes :(

**Comment by jcheng5** [comment]
@lionel- I think I'm wrong about this being about dplyr introducing these frames. It seems more like it's the way I'm intercepting the errors that's causing them (or that the way rlang captures traces does better initial cleanup than I know how to do). Look at this one:

```r
withCallingHandlers(mtcars |> dplyr::select(foo),
  error = function(e) {
    print(e$trace$parent)
    print(sys.parents())
  }
)
```
```
 [1]  0  0  0  3  4  3  6  7  8  9 10 11  8 13  7 15 16 17 18 19 20 21 22 23 24 25 26
 [1]  0  0  0  3  4  3  6  7  8  9 10 11 12 13 14  0 16 17 18  0
```

Note the `sys.parents()` version contains the two `0` entries near the end--that's exactly what I'm seeing in Shiny. If you look at the corresponding `sys.calls()`, one is [this anonymous function from dplyr](https://github.com/tidyverse/dplyr/blob/19bb248f8c5a7d284219281bcd30a9a0d3a010d6/R/utils.r#L116) and the other one is the error handling anonymous function in the reprex itself.

I think you have the concept of a trace "bottom" for filtering out these frames, and that's why `e$trace$parent` doesn't have them? Maybe I need to study that more?

**Comment by lionel-** [comment]
hmm which versions of rlang, dplyr, and tidyselect do you have? I'm seeing this locally:

```r
#>  [1]  0  0  0  3  4  3  6  7  8  9 10 11  8 13 14  7 16 17 18 19 20
#> [22] 21 22 23 24 25 26 27
```

**Comment by jcheng5** [comment]
@lionel- If you don't mind I might just merge https://github.com/rstudio/shiny/commit/c3b0dcb8a65edf990ede0738747153fd2434abb7, we're trying to put a Shiny release out in the next couple of weeks and this is the last question mark. I don't think it will make the problem worse, and the current state is so bad.

**Comment by lionel-** [comment]
That sounds good.

**Comment by Steviey** [comment]
Seems to be the best choice for debugging a backend...

`options(shiny.fullstacktrace=TRUE)`
