### ISSUE TITLE
Do not restrict memoryCache keys to digits and numbers 

### ISSUE THREAD

**Issue by vspinu** [rstudio/shiny#3306]
```
Error in validate_key(key) : 
Invalid key: aa-bb-589decf3e87dd14d7cb14f665a5959f2. Only lowercase letters and numbers are allowed.
```

It looks to me that this restriction is not reasonable nor necessary for memory cache. Or is it?

**Comment by wch** [comment]
This is actually now implemented in the cachem package, with `cachem::cache_mem()`.

What is the use case that you want to use other keys? The `cache_mem()` package is designed to provide an interface that is consistent with `cache_disk()` as well as other caching backends that may be implemented in the future. Other caching backends may not support various characters in the keys. For example, with `cache_disk()`, some filesystems are not case-sensitive, so they cannot represent both `x` and `X` as separate keys; that's why we allow only lowercase letters. To make it possible for users to easily swap out caching backends, we want to impose consistent restrictions on the keys -- it would be bad if someone got their code working with a `cache_mem()` and then when they try to switch to a `cache_disk()`, it stopped working.

As for why these specific restrictions: the lowercase letters and numbers are sufficient for what the caches are designed for, which is to use a hexadecimal number (from hashing an object) as a key.

If you want a simple memory-based key-value store, you can use an environment object, or [fastmap](https://github.com/r-lib/fastmap), which has some advantages over environments. These don't do automatic pruning, though.

**Comment by wch** [comment]
I should add that I'm not necessarily opposed to adding more allowable characters in keys. In order to do that, though, we would want to be sure that any likely storage backends would work with those characters.

**Comment by vspinu** [comment]
> In order to do that, though, we would want to be sure that any likely storage backends would work with those characters.

My primary concern are the separators `_` and `-`. I think those are generally safe. In an very unlikely case that some storage backend would not accept those, the characters can be automatically replaced with a fallback character on those backends. 

> Another possibility is to add an option to cache_mem() that tells it to not pass the key to validate_key() at all. 

That would work, also for the disk_cache. 

Maybe more generically the user can provide a validation function. 

My use case is a disk + memory layered with custom access with the requirement that objects should be accessed directly. This is why I want to prefix the hash with a user-readable label. Also this is the reason why I don't use disk_cache as I want to store objects in RDS format in order to be able to access them directly. The serialization format of disk_cache is currently undocumented.

**Comment by wch** [comment]
In r-lib/cachem#9 I've allowed `_` and `-` for both `cache_mem` and `cache_disk`.

I think it could make sense to allow users to disable the key validation for `cache_mem`. I don't think that it makes sense to allow users to provide their own validation functions for the various cache backends, since there's no guarantee that the provided validation function is actually compatible with the storage backend.

Regarding storage format, `cache_disk` stores objects as RDS.

I'm going to close this issue; conversation can continue in the cachem repo, either in the PR or in a new issue.
