### ISSUE TITLE
Deployment shinny app.

### ISSUE THREAD

**Issue by IndoLexi** [rstudio/shiny#3308]
Hello everyone. 
When I try to publish my shiny app this error ocurred : 

The application failed to start: exited unexpectedly with code 1: 
Error in value[[3L]](cond) : 
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

My app works  well on local. 
It's called app.R and it's in a file with a data.csv that it needs. I read the data.csv with this command : 
read.csv2(file = "data.csv", header = T, encoding = 'UTF-8')

I have made this data.csv from Excel. 

I have also put :
library(ggplot2)
library(shiny)
It's the only library that I need.

Sorry if my english is not the best I am french. Thank you for your time and I am looking for any suggestion.

**Comment by maxheld83** [comment]
I don't think this is the right venue for your question, since it's not clear that your problem is due to a bug in shiny.
I think you'd be better served on [Stack Overflow](http://stackoverflow.com) or [RStudio Community](https://community.rstudio.com).

In both cases, you should post a [reproducible example](https://reprex.tidyverse.org), so that people can really help you.

Perhaps you can close this issue yourself; we should all try and reduce the noise for the maintainers here ☺️.
