### ISSUE TITLE
Error in library(shinyjs) : there is no package called ‘shinyjs’

### ISSUE THREAD

**Issue by KULDEEPDYODHI** [rstudio/shiny#3703]
Error in library(shinyjs) : there is no package called ‘shinyjs’

**Comment by philibe** [comment]
Hello

>Joined 6 hours ago

For this sort of question, it's better to ask on Stackoverflow because it's not a bug.

And you have to give more informations and reprex (reproducible example).

But in your case you've probably forgotten
- To install the stable CRAN version:
  + `install.packages("shinyjs")`
- To install the latest development version from GitHub:
  +  `install.packages("devtools")`
  + `library(devtools)`
  + `devtools::install_github("daattali/shinyjs")`
