### ISSUE TITLE
Run in window doesn't work after shiny crashes

### ISSUE THREAD

**Issue by ifoxfoot** [rstudio/shiny#3761]
### System details

Browser Version: Chrome

Output of `sessionInfo()`:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.7

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9       digest_0.6.31    later_1.3.0      mime_0.12        R6_2.5.1         lifecycle_1.0.3  xtable_1.8-4    
 [8] magrittr_2.0.3   rlang_1.0.6      cli_3.5.0        rstudioapi_0.14  promises_1.2.0.1 ellipsis_0.3.2   tools_4.1.2     
[15] shiny_1.7.4      httpuv_1.6.7     fastmap_1.1.0    compiler_4.1.2   htmltools_0.5.4 
```

### Example application *or* steps to reproduce the problem

```R
# Minimal, self-contained example app code goes here

#write a small shiny app
library(shiny)

ui <- fluidPage(
  actionButton("btn", "click me")
)

server <- function(input, output)
{
  observeEvent(input$btn, {
#change this line to x <- tryCatch(1+A, warning=function(w){ w}) to break app
    x <- tryCatch(1:3 * 1:2, warning=function(w) { w })
#run it, crash it, fix code and run again to see problem
    if (inherits(x, "simpleWarning")) {
      mess <- x$message
      showNotification(mess)
      x <- 1:3 * 1:2
    }
    print(x)
  })
}

shinyApp(ui, server)
```

### Describe the problem in detail

Rstudio version 2022.12.0.353 

If the shiny app crashes once, the "Run in Window" feature in Rstudio stops working. It pops up but it just remains blank. Like this:

<img width="1407" alt="Screen Shot 2022-12-23 at 9 33 14 AM" src="https://user-images.githubusercontent.com/72639615/209377581-b8578159-e48f-4c10-bb34-85c8334c0ca5.png">

It does print `Listening on http://127.0.0.1:6835` in the console. And pressing the stop sign closes the window. 

The "Run in Viewer" feature does work, and I am able to view the shiny app in the browser.

**Comment by cpsievert** [comment]
Thanks for the report! I've transferred this issue to https://github.com/rstudio/rstudio/issues/12569 (since a fix will likely need to be made in RStudio). Please subscribe to that issue for updates.

In the meantime, I'd recommend checking the "Run in External" option:

<img width="174" alt="Screenshot 2023-01-13 at 10 41 55 AM" src="https://user-images.githubusercontent.com/1365941/212373016-9bbfa52c-5c16-466f-9c3b-8e4d252b644d.png">

(You could also put something like `options(shiny.launch.browser = .rs.invokeShinyWindowExternal)` in your `.Rprofile` to make this the default behavior)

Also, as a side note, when developing Shiny apps, consider also running `shiny::devmode()` to get a bunch of other "smart defaults" for development.
