### ISSUE TITLE
Add `session$click()` to `testServer()` 

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3764]
Currently, it's very awkward to test action buttons using `testServer()`, because there is no dedicated function to clicking on them. They are treated as regular inputs, so if I want to simulate a click, I need to manually set its input value to the right integer with `session$setInputs()`.

It would be very useful to have a `session$click()` that would work for buttons

**Comment by daattali** [comment]
I just noticed the related issue https://github.com/rstudio/shiny/issues/2745

**Comment by Shelmith-Kariuki** [comment]
Hi @daattali , 

If I have `shiny::actionButton(ns("go_button"), "Go")` in my UI and `shiny::observeEvent(input$go_button, {"some code goes here"})`, how do I simulate a button click while running tests? `session$setInputs(go_button = 1)` doesn't work for me.

**Comment by Shelmith-Kariuki** [comment]
I am building an app with many observeEvents and I need a way to simulate button clicks while running tests. adding `session$click()` to `testServer()` would really come in handy.

**Comment by gadenbuie** [comment]
Thanks @Shelmith-Kariuki for writing in this issue and to @daattali for opening it. I wrote an answer in [the related issue here](https://github.com/rstudio/shiny/issues/2745#issuecomment-1610051838) with an example of how I'd approach this problem. Shel – please let me know if you're still having issues testing your module with that approach.

I'm going to close this issue since #2745 provides a complete description of the problem. I will say that I think that it's unlikely that we'd add a specific `$click()` helper function. `testServer()` and Shiny modules are advanced enough that it's reasonable to expect users to have to understand how action buttons operate. If I'm missing a detail that makes it trickier to work with, please let me know.
