### ISSUE TITLE
downloadHandler's filename not updating reactively

### ISSUE THREAD

**Issue by kennedymwavu** [rstudio/shiny#3803]
### What I did

```r
library(shiny)

ui <- fluidPage(
  selectInput(
    inputId = "filename",
    label = "Filename",
    choices = c("iris", "mtcars")
  ),
  downloadButton(outputId = "dnld")
)

server <- function(input, output, session) {
  output$dnld <- downloadHandler(
    filename = paste0(input$filename, ".csv"),
    content = function(file) {
      write.csv(x = get(input$filename), file = file)
    },
    contentType = "text/csv"
  )
}

shinyApp(ui, server)
```

### What happened

When I change the selectInput value to 'mtcars' and click on the download button, the downloaded file is named 'iris.csv' but the content is that of 'mtcars'.

### What I expected to happen

I expected the name of the downloaded file to correspond to the value of the selectInput. eg. If the selected value is 'mtcars', the name of the file should be 'mtcars.csv'

I expected `downloadHandler()` to pick the filename reactively as it does with the content (Note that I've used `input$filename` in both the filename and the content)

### A "hack" to solve the issue

Putting `downloadHandler()` inside an observer works well:

```r
library(shiny)

ui <- fluidPage(
  selectInput(
    inputId = "filename",
    label = "Filename",
    choices = c("iris", "mtcars")
  ),
  downloadButton(outputId = "dnld")
)

server <- function(input, output, session) {
  observeEvent(input$filename, {
    output$dnld <- downloadHandler(
      filename = paste0(input$filename, ".csv"),
      content = function(file) {
        write.csv(x = get(input$filename), file = file)
      },
      contentType = "text/csv"
    )
  })
}

shinyApp(ui, server)
```

### Final remarks

Is this a bug or is an observer required for the `downloadHandler()`'s filename to pick up (subsequent) values of an input?

**Comment by gadenbuie** [comment]
Thanks for the question @kennedymwavu! The documentation for `downloadHandler()` say that `filename` is...

> A string of the filename, including extension, that the user's web browser should default to when downloading the file; or a function that returns such a string. (Reactive values and functions may be used from this function.)

In other words, `filename` can either be

1. a static character string that's is always the name of the file
2. a function that returns a character string that will be used as the name of the file.

Because you're using `filename = paste0(...)` in your example, the name of the downloaded file will be the same for all downloads.

For the file name to change, you have to provide a function to `filename`. Inside that function you can use inputs and other reactive values from your app.

So if you change

```r
filename = paste0(input$filename, ".csv")
```

to use a function

```r
filename = function() {
  paste0(input$filename, ".csv")
}
```

your app should work as expected.

**Comment by kennedymwavu** [comment]
Thank you @gadenbuie for your informative response! I totally missed that part of the docs. Closing this now.
