### ISSUE TITLE
Update Google Analytics article - the current article will become obsolete on 2023-07-01

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3814]
The current article on using Google Analytics https://shiny.rstudio.com/articles/google-analytics.html is recommending using Universal Analytics. That way of using GA is going to stop working on July 1, and instead Google Analytics 4 must be used. See here for details https://support.google.com/analytics/answer/10759417

**Comment by daattali** [comment]
Related to https://github.com/rstudio/shiny-server/issues/554

**Comment by gadenbuie** [comment]
Thanks @daattali! I think that anyone who follows the instructions in this article will arrive at the right place, although I haven't walked through the end-to-end process to know if any of the screenshots are out of date.

Thankfully, the article doesn't explicitly recommend UA or a UA-specific workflow, it just happens to use a UA tag ID. I'm fairly certain the process outlined is still current and the only difference will be the use of `G-` prefixed tags in the code Google will provide to the user to copy and paste.

For now, I think we could add a note at the top of the article pointing out the difference in tag ID and linking to some of Google's pages around the change. (See rstudio/shiny-server#555 for more links and context.)

**Comment by daattali** [comment]
I'm not 100% on this but I think some of the code in that article is outdated as well. For example `ga('send', 'event', 'widget', 'select data', $(e.currentTarget).val());` -- I think `ga('send', 'event', ../)` is the old syntax and not how the new google analytics works.

**Comment by gadenbuie** [comment]
Thanks again @daattali. You're right, it looks like [the docs now recommend](https://developers.google.com/tag-platform/gtagjs/routing) `gtag('send', 'event', ...)`. This [page also provides a nice comparison](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs) between `ga()` and `gtag()`.

I'm surprised because the code in the article mixes `gtag()` and `ga()`; which might have been an oversight from the last update? I was mostly checking the new boilerplate and that looked okay to me.
