### ISSUE TITLE
Slider handle is in wrong location when used with Quarto

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#3905]
When using the `sliderInput` with a different build of Bootstrap (compared to the bootstrap.css in bslib), the slider looks like this:

![slider](https://github.com/rstudio/shiny/assets/86978/d6ed08a9-5e48-44e2-b193-fb696210c63e)

This is because the CSS for the handle position is in bslib's copy of bootstrap.css:

![slider css](https://github.com/rstudio/shiny/assets/86978/df1c2f3b-deb5-47bb-9f35-8883ebe7af95)

This happens when using the slider in a Quarto document.

To fix this, I think the [slider styling in bslib](https://github.com/rstudio/bslib/blob/46ec27ecd11de8e3f286351474fb1009beb13bb7/inst/builtin/bs5/shiny/ionrangeslider/_rules.scss) somehow needs to be put into Shiny.

**Comment by cpsievert** [comment]
Are you bringing the slider in via PyShiny (a reprex would be great)?

**Comment by wch** [comment]
Right, the slider is coming in from Shiny for Python. Sorry, I don't have a simple reprex at this point, since generating the output currently involves some things that are experimental. 

I also tried reproducing with Quarto and Shiny for R, but I couldn't figure out how to get it to display sliders with the updated look (with no tick marks). If you can get Quarto and Shiny for R to display the new sliders, I suspect they will look the same.

**Comment by wch** [comment]
I'm not sure if this is exactly the same issue, but it seems like it's probably related: https://github.com/rstudio/bslib/issues/813

**Comment by gadenbuie** [comment]
@wch I suspect the issue is fundamentally the same for Python and R -- the static, precompiled CSS for ionrangeslider not using the Sass variables of the new shiny preset -- but the fix will likely be different. In the case of Shiny for Python, I'm not sure how ionrangeslider's CSS dependency is handled, but I suspect the fix will be to re-compile that CSS in the shiny preset context.

**Comment by gadenbuie** [comment]
I think we should move this issue into the py-shiny repo (or close it in favor of a new issue); on the R side the work needed is covered by the bslib issue.

**Comment by wch** [comment]
Just to make sure we're on the same page: The slider looks fine in a regular Shiny for Python app, but _not_ when the slider from py-shiny is used in a Quarto doc.

Shiny for Python has a build of bootstrap.min.css which includes the CSS in the screenshot above, for `.irs.irs--shiny .irs-handle`.

In the Quarto case, the problem is that Quarto's build of bootstrap.min.css is taken from an older version of bslib, and does not have that CSS. As far as I know, there's not a way to cleanly override Quarto's version of Bootstrap. Note that Quarto _will_ load the ion.RangeSlider HTML dependency, so the resulting document uses Shiny's version of ion.RangeSlider.css, with Quarto's version of bootstrap.min.css.

I think Shiny for Python currently simply copies over the CSS files from Shiny for R. If I run a simple example app in R, the browser inspector shows that there is some slider styling is in bootstrap.min.css.

<img width="843" alt="image" src="https://github.com/rstudio/shiny/assets/86978/a0c17e5d-9f3c-41aa-a1a8-1ccdd1f7829d">

And here it is with the `.irs.irs--shiny .irs-handle` rule in bootstrap.min.css disabled:

<img width="835" alt="image" src="https://github.com/rstudio/shiny/assets/86978/60a9e109-9e60-40ac-96d8-e34500b3b093">

App code:

```R
library(shiny)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(preset = "shiny"),
  sliderInput("n", "N:", min = 0, max = 1000, value = 500)
)

shinyApp(ui, function(input, output) {})
```

**Comment by gadenbuie** [comment]
> In the Quarto case, the problem is that Quarto's build of bootstrap.min.css is taken from an older version of bslib, and does not have that CSS. As far as I know, there's not a way to cleanly override Quarto's version of Bootstrap.

What's additionally confusing is that these `bootstrap.min.css` files are not equivalent. It's not that Quarto takes an older `bootstrap.min.css` from bslib, but rather they took the base Bootstrap layers that contain some direct patches that bslib applies to the Bootstrap source. As a result, Quarto's version doesn't include any of the rules that might get layered on top in R via a Sass compilation step.

In Shiny for Python, the `bootstrap.min.css` is compiled via bslib and may include even more than bslib would include in "bootstrap" because in bslib and R we can compile the Sass on the fly, whereas in Python these rules need to ship as compiled.

At this point, I think it'd be worth the effort to put together a reprex.

**Comment by jcheng5** [comment]
I'd really really like us to move away from this model (that I invented) where the sass rules are layered in, and instead have everything that builds on top of Bootstrap use CSS variables exclusively. How far do you think we are from that reality?

Until we do that, we'll never having theming in Shiny for Python, and Quarto will always act weird like this when we put our components in it.

**Comment by cpsievert** [comment]
> How far do you think we are from that reality?

We're not that far off, and we've made significant strides recently with the bslib components. 

> instead have everything that builds on top of Bootstrap use CSS variables exclusively. 

I doubt this alone would be sufficient for solving the core issue here, which as @wch pointed out, seems to be related to how Quarto is managing Bootstrap. After discussing with Charles today, we talked about some of these issues, and at least for now, I'll be sending them a PR so that Quarto can better simulate bslib, which may end up fixing this issue. 

Longer term, it would be great to eliminate Quarto's build-time step of copying over bslib's Sass code. I don't know if this is realistic, but I'm thinking Quarto could maybe do something like `library(bslib); bs_theme() |> bs_bundle(user_sass) |> bs_theme_dependencies()` via webR (and maybe, for py-shiny, could have a web service to do this?)

**Comment by gadenbuie** [comment]
After researching how py-shiny handles the ionRangSlider dependency, I have a much clearer understanding of this issue. py-shiny pre-renders the static `ionRangeSlider.css` using the `preset = "shiny"` theme ([see here](https://github.com/posit-dev/py-shiny/blob/15bd9b82680fc2934fad3b588fc2a2a1db973c46/scripts/htmlDependencies.R#L133-L136)). That compiled CSS file isn't fully stand-alone, as we have [additional rules in the shiny preset](https://github.com/rstudio/bslib/blob/main/inst/builtin/bs5/shiny/ionrangeslider/_rules.scss) that end up in `bootstrap.min.css`. 

So one possibility, for py-shiny at least, would be to include those rules in the pre-compiled `ionRangSlider.css` file. Alternatively, it might be better for py-shiny to serve the standard Bootstrap styles for the ionRangeSlider when in a Quarto doc or when paired with an unknown Bootstrap.

Unfortunately, CSS variables wouldn't completely save us from this problem (even though I agree we should move in that direction with our existing components too), because we're missing an entire small stylesheet.

I do think we should at least open a py-shiny specific issue since the dynamics of the situation are different in Python and R and will need different fixes (unless we decide to make Bootstrap 5 and the Shiny preset the _de facto_ default Shiny app look).

**Comment by wch** [comment]
Closing in favor of https://github.com/posit-dev/py-shiny/issues/748
