### ISSUE TITLE
use of `reactive()` inside loops?

### ISSUE THREAD

**Issue by r2evans** [rstudio/shiny#532]
BLUF: `reactive({...})` is working for me on individual uses, but I cannot get them to work in a loop.

Situation: I have a session-specific variable called `models` that contains one or more sub-lists, each of which I'll refer to as a `model`. Each `model` is a list of multiple various things (data.frame, matrices, etc), and each of `model` have the identical structure of subcomponents. A severely truncated example of this:

``` r
str(models)
##  List of 2
##   $ :List of 8
##    ..$ name       : chr "model"
##    ..$ description: chr ""
##    ..$ config     :List of 10
##    .. ..$ subelem1    : num 0.2
##    .. ..$ subelem2    :'data.frame': 9 obs. of  3 variables:
##    .. .. .. <snip>
##    .. ..$ <more stuff here>
##    ..$ objs       :List of 2
##    .. ..$ obj1:List of 7
##    .. .. ..$ defn     :'data.frame': 9 obs. of  9 variables:
##    .. .. .. .. <snip>
##    .. .. ..$ curves   : num [1:9, 1:9] 0 0 0 0 -1 1 1 1 -1 1 ...
##    .. .. ..$ <more stuff here>
##    .. ..$ obj2:List of 7
##    .. .. .. <snip>
##    ..$ scens      :List of 2
##    .. .. <lots of stuff>
##   $ :List of 8
##    .. <repeat all of the above>
```

The user selects which `model` to use based on a dynamically-created and -maintained pulldown. My intent is to be able to track dependencies among numerous other regions in the shiny app. Currently, when the pulldown is changed, another session-specific variable `this` has a copy of that model.

If an html output is reactive to `this` then the chaining works fine. However, I want a little finer-grained dependency so that an html element will react to changes to a specific component of the model.

I can manually create numerous variables that track individual components, but since there are more than just a few I thought I'd automate the process in a loop. Here's some close-enough code to demonstrate. The following works:

``` r
this <- reactive({
    names <- sapply(models, `[[`, 'name')
    idx <- which(input$modelSelect == names)
    if (length(idx)) models[[idx]] else NULL
})
```

The reacting output elements check for `NULL`.

The following does not produce the intended reactions (also no errors):

``` r
this <- list()
for (el in c('name', 'description', 'objs', <more stuff>))
    this[[el]] <- reactive({
        names <- sapply(models, `[[`, 'name')
        idx <- which(input$modelSelect == names)
        if (length(idx)) models[[idx]][[el]] else NULL
    })
```

It is safe to assume that the `model` "always" contains the specific elements. I also tried (with equally unsuccessful luck) using `assign(el, reactive({ ... }))` inside the `for` loop.

In addition to helping me route out the problem, can you think of a better way to handle this (admittedly non-trivial) dependency?

Thanks! (BTW: I had a great time talking with you today about this at the useR conference, Joe and Jeff, thanks for the help!)

**Comment by msuprun** [comment]
Hi all, 
I am stuck with a similar problem. I am trying to create a simple app for plate randomization. It takes some parameters as input from users (like number of subjects, visits, replicates). 

In server.R I need to have a loop that created plates with random subject ID numbers. I can't get this function to work in Shiny. It works well otherwise. Code doesn't work starting with plates.w.subjects <- list()

Here is the server.R code: 

```

n.subjects    <- reactive({ as.numeric(input$n.subjects) })
n.visits      <- reactive({ as.numeric(input$n.visits) })     
n.replicates  <- reactive({ as.numeric(input$n.replicates) }) 
n.buffers     <- reactive({ as.numeric(input$n.buffers) })    
n.ipc         <- reactive({ as.numeric(input$n.ipc) })
n.plates      <- reactive({ ceiling((n.subjects()*n.visits()*n.replicates())/(n.wells-sum(n.buffers(),n.ipc()))) })
subject.ids   <- reactive({ seq(1, n.subjects()) })

## other calculations here 

plates.w.subjects <- list()
plates.data <- reactive({

  for(i in 1:n.plates()) {
    local({
      if (i == 1) {
        used.samples <- NA
        left.samples <- subject.ids()
      } else {
        used.samples <- melt(plates.w.subjects)[,1]
        left.samples <- setdiff(subject.ids(), used.samples)
      }

      if(length(left.samples) > max.subjects.plate()) {
        c <- sample(left.samples, max.subjects.plate(), replace=FALSE, prob=NULL)
      } else {
        c <- sample(left.samples, length(left.samples), replace=FALSE, prob=NULL)
      }

      name <- paste0('Plate.', i)
      tmp <- list(subj.ids = c)
      plates.w.subjects[[name]] <- tmp

      #rm(tmp,name,c,used.samples,left.samples)
    })
  }
 })

output$result <- renderPrint({
    plates.data()$plates.w.subjects[[1]]
  })
```


Ideally the result should be:
$Plate.1
$Plate.1$subj.ids
 [1] 23 16 13 20 24 10 19 25  3 21  4 12  9
$Plate.2
$Plate.2$subj.ids
 [1] 14 22  8 18  2 17  6 11  1 15  5  7

I saw from the answers above that you can use 'local' or 'lapply' but I cant get  either one to work..
Would really appreciate any help! 
Thanks!
Maria

**Comment by jcheng5** [comment]
The line

plates.w.subjects <- list()

must go into the body of the plates.data reactive expression (make it the
first line). Then the last line of the plates.data reactive should be

plates.w.subjects

And finally, the renderPrint() should just use plates.data()[[1]] (drop the
$plates.w.subject part).

The point of a reactive() expression is to *return* the value you're
interested in. What you were doing was changing some other variable (and
actually not even that was working) and then returning nothing. The changes
above cause the correct data to be returned from the plates.data reactive
expression.

I highly recommend taking the time to watch my "Effective reactive
programming" tutorial here:
https://www.rstudio.com/resources/webinars/shiny-developer-conference/

Hope that helps!

**Comment by jcheng5** [comment]
The line

`plates.w.subjects <- list()`

must go into the body of the plates.data reactive expression (make it the
first line). Then the last line of the `plates.data` reactive should be

`plates.w.subjects`

And finally, the `renderPrint()` should just use `plates.data()[[1]]` (drop the
`$plates.w.subject` part).

The point of a `reactive()` expression is to *return* the value you're
interested in. What you were doing was changing some other variable (and
actually not even that was working) and then returning nothing. The changes
above cause the correct data to be returned from the `plates.data` reactive
expression.

I highly recommend taking the time to watch my "Effective reactive
programming" tutorial here:
https://www.rstudio.com/resources/webinars/shiny-developer-conference/

Hope that helps!

**Comment by msuprun** [comment]
Thanks Joe!
The videos are really helpful. 
I had to break the code into more pieces to get it do what i need (and of course incorporate your suggestions). I ended up separating if i == 1 into a separate chunk. Here is what works. Not sure how efficient it is in term of programming though..

```
  plates.w.subjects.1 <- reactive({
    sample(subject.ids(), max.subjects.plate(), replace=FALSE, prob=NULL) 
    })
  
  
  plates.w.subjects <- reactive({
    
    plates.data <- list()
    plates.data$Plate.1 <- list(subj.ids = plates.w.subjects.1())
    
       for(i in 2:n.plates()) {

         used.samples <- melt(plates.data)[,1]
         left.samples <- setdiff(subject.ids(), used.samples)

         if(length(left.samples) > max.subjects.plate()) {
           z <- sample(left.samples, max.subjects.plate(), replace=FALSE, prob=NULL)
           } else {
           z <- sample(left.samples, length(left.samples), replace=FALSE, prob=NULL)
          }
      
         tmp <- list(subj.ids = z)
         plates.data[[paste0('Plate.', i)]] <- tmp
       } 
      plates.data
    })
  
 
  output$result <- renderPrint({
    plates.w.subjects()
  })
```
Many thanks!
Maria

**Comment by jeremyjoslove** [comment]
Hi all,

I seem to be having a similar issue to that of r2evans (which I see was over 3 years ago), but I can't seem to figure out how to correct my code so it works.
I use the portion of code beneath to later plot all the variables contained in the list, but it only takes into the account the last element of this list. 
I confirmed this was the issue by changing the for loop to go from 1 to length(list_mod_Variables)-1, and I only got the before last element.
I'm not sure if the issue is coming from the x, or from the i of the for loop.
At first, I tried with x a variable that was supposed to change at every iteration, but I understand from your comments above that this will not work since x will be written over every time. This is why I now have created x as a list, but despite the x[[i]] that I thought should deal with this issue, the problem persists.

I would be very grateful if someone could help me out on this !

Many thanks

```

list_graphVarPlot <- list()
  x <- list(x1=0,x2=0,x3=0,x4=0)
  for (i in 1:(length(list_mod_Variables))){
      list_graphVarPlot[[i]] <- reactive({
        t <- table_input()
        if(!is.null(t)){
            x[[i]] <- as.vector(t[,list_mod_Variables[[i]]$varSelected()])
            x[[i]] <- eki_lag(x[[i]], list_mod_Variables[[i]]$graphLag())
            x[[i]] <- eki_adstock(x[[i]], list_mod_Variables[[i]]$graphAsInt(), list_mod_Variables[[i]]$graphAsLen())
            name <-paste("dataexpGraphVarPlot",i,sep = "")
            assign(name,x)
          } 
      })
    names(list_graphVarPlot)[i] = paste("graphVarPlot",i,sep = "")
  }
```

**Comment by Walshiny** [comment]
I have a similar problem for a matrix multiplication.
I try to propose a generalization of the problem here below
If I have an array a (3,4,2) and a matrix b (3,4) and I want to multiply each element of the array  for the corresponding element of the matrix (like as I had two matrix instead of 1 arrays; in my real case I have an array (101,2,51) so I cannot simply split the array in 2 matrix) I can do in two ways:
`a<-array(1:24, dim=c(3,4,2)) 
b<-matrix(c(110,120,130,210,220,230,310,320,330,410,420,430),nrow=3, ncol=4)
c1<-array(NA, dim=c(3,4,2))c2<-array(NA, dim=c(3,4,2))
#Two ways 
for (h in 1:2) {c1[,,h]<-a[,,h]*b}
c2[]<-apply(a, 3, function(x) x*b)
#test
c1==c2`

If the matrix a  is generated by an input statement of a shiny dashboard, it is necessary to create a reactive expression. First I tried two statements like above but they doesn't work,  as highlighted in yours previous posts
`for (h in 1:2) {c1[,,h]← reactive({a[,,h]*b})}
c2[]<-reactive({apply(a, 3, function(x) x*b)})`
 The output matrix is not an array (3,4,2) but a matrix (3,4). 
After reading this topic I tried to introduce a local variable in a for loop but it doesn't work again and I use already “apply” . 

Any help will be  appreciated

Thank you
Walter

**Comment by r2evans** [comment]
@Walshiny, I suggest you read [jcheng5's comment from 2014](https://github.com/rstudio/shiny/issues/532#issuecomment-48008956) that explained the use of `local` inside the loop in order to distinguish the looping variable in each iteration. whc's follow-on comment provided more context with both `lapply` and `for` examples. (Side note: you're not likely to get much response from the "main actors" here, since they tend to not pay attention to closed issues.)
