### ISSUE TITLE
Bug (?) in version 0.10.2.9006 - odd alignment of checkboxGroupInput

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#675]
My UI.r has the following:
        fluidRow(
          checkboxGroupInput("monthIdppu", "Spread value(s) over the following months:", month.abb[1:12]
                             , selected = c("Jan","Apr") , inline = TRUE)
          ),
Normally as it is a fluidRow the checkboxGroupInput presents itself as a one single line of tick boxes.

With 0.10.2.9006 the checkboxGroupInput extends only to the extent of the label ("Spread value(s) over the following months:"), then breaks in 3 other lines, as in
Column(x, checkboxGroupInput
With x = length("Spread value(s) over the following months:").

**Comment by gjoneski** [comment]
Hi Winston.

One issue we've come across is: due to this hard-coded container width, selectInput, for example, no longer behaves the same with respect to its `width` parameter.  In particular, passing width='100%', expands the input to the limits of the hard-coded container width.  This is a change in behavior against bootstrap 2, when this would have been expanded within the limits of the next enclosing element - often something like:

column(width=x,selectInput(,...width='100%'))

At any rate, just wanted to give you a heads up about this - if nothing can be done within shiny >=0.11, we are aware of the shinybootstrap2 alternative.

Thanks.

**Comment by wch** [comment]
@gjoneski, I just pushed a fix in the dev version. Could you try it out and let me know if it behaves as expected?

**Comment by gjoneski** [comment]
Thanks for looking into this Winston.

That does work for sliderInput.  Hopefully all of [these guys](https://github.com/rstudio/shiny/commit/7b3e9ab0315353ab8e25ec83319d5399941cc46e)  will get that facelift as well.

Thanks again.

**Comment by wch** [comment]
It's a little tricky since most of those don't offer a `width` option to begin with. Perhaps it would be better to add some custom css to your app?

**Comment by gjoneski** [comment]
Sure - makes sense, we've already done this.

I do think select(ize)Input, as widely used as it is, should probably respect its `width` parameter.

At any rate, thanks for looking into this.
