### ISSUE TITLE
Unicode in error messages

### ISSUE THREAD

**Issue by trufanov-nok** [rstudio/shiny#736]
Hi,
I'm using shiny 3.1.2 with RStudio 0.98.1102 under Kubuntu. The system locale is russian.

Whenever I'm trying to run shiny app which contains errors I'm getting error message that impossible to read due to broken character encoding. That's because error message is written in local language and in Unicode, but webpage is rendered in one of local Russian encodings (KOI8-R for example). AS it do by default if it can't determine encoding automatically. To bypass that I need to press "open in browser" button and switch encoding to Unicode in browser. (I'm using FF).
That's great that errors are written in russian, but could you please add the right encoding tag to generated error webpage ?

**Comment by yihui** [comment]
Can you post your `library(shiny);sessionInfo()` and a minimal reproducible example? Obviously there is no shiny 3.1.2... Thanks!

**Comment by trufanov-nok** [comment]
Oops. It seems to be 0.11
The output is http://pastebin.com/mW3M0Jck
To reproduce the problem just delete a comma after sidebarPanel() in ui.R in default generated project:
 http://pastebin.com/WiNQdZ2k
and press Run button. You'll get a grey window with 
```
ERROR: /home/truf/ml/temp/ui.R:26:5: Ð½ÐµÐ¾Ð¶Ð¸Ð´Ð°Ð½Ð½Ñ‹Ð¹ ÑÐ¸Ð¼Ð²Ð¾Ð»
25:     # Show a plot of the generated distribution
26:     mainPanel
        ^
```
The symbols after */home/truf/ml/temp/ui.R:26:5:* are incorrect
If you press Open in browser and switch to unicode you'll get a right message
```
ERROR: /home/truf/ml/temp/ui.R:26:5: неожиданный символ
25:     # Show a plot of the generated distribution
26:     mainPanel
```

**Comment by wch** [comment]
I've attempted to set my locale to Russian and run the same app, but I don't think I'm doing it successfully, since the error messages are still in English for me. This is with R 3.1.2 and RStudio 0.99.315.

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=ru_RU.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8       
 [4] LC_COLLATE=ru_RU.UTF-8     LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=ru_RU.UTF-8   
 [7] LC_PAPER=ru_RU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.11.1.9002

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.8 httpuv_1.3.2    mime_0.2        R6_2.0.1        Rcpp_0.11.4    
[7] tools_3.1.2     xtable_1.7-4   
```

I did this by running:

```bash
sudo locale-gen ru_RU.UTF-8
export LC_ALL=ru_RU.UTF-8
rstudio
```

It's possible I'm missing an important step.

**Comment by wch** [comment]
OK, I'm able to reproduce the error on my Mac with:

```R
Sys.setenv(LANG="RU")
library(shiny)
runApp()
```

**Comment by wch** [comment]
It looks like the source of the problem is in httpuv:
https://github.com/rstudio/httpuv/blob/0a6413cc099ea8118b709ae329745c3eb813e8c4/R/httpuv.R#L129-L137

It should be `'Content-Type'='text/plain; charset=UTF-8'` -- at least if server is running on a machine with a UTF-8 locale. If running on Windows, I'm not sure exactly how the `charset` should be specified. Maybe it should still be `UTF-8` and the error message should be converted to UTF-8.

It looks like there are many places in Shiny that also specify a HTTP response without specifying the encoding. For example: https://github.com/rstudio/shiny/blob/8b3ca1265805035079e8d431ef20363bfed76a7c/R/shiny.R#L731-L732

**Comment by yihui** [comment]
I think you are right that we need to convert the error messages to UTF8 and add `charset=UTF-8` to the content type. I did the explicit conversion in DataTables (https://github.com/rstudio/shiny/blob/8b3ca/R/utils.R#L715), and I did not use `charset=UTF-8` but it still works on Windows. Not quite sure why. We will need more testing.

**Comment by wch** [comment]
Interesting - it looks like that it works in your case with `application/json`, because JSON is always encoded in either UTF-8, UTF-16 (big- or little-endian), or UTF-32 (big or little-endian), and you can always tell which one of them it is by looking at the first four bytes: http://stackoverflow.com/a/14955491/412655

**Comment by wch** [comment]
I've submitted a PR for httpuv that fixes this issue. I'll make the same fix in Shiny, unless there are any objections.
