### ISSUE TITLE
Using as.Date on shinyapps.io

### ISSUE THREAD

**Issue by jalapic** [rstudio/shiny#744]
When using `as.Date()` to convert full month names (e.g. January, February) ,  there is no issue whatsoever when running a shinyapp locally on one's own machine.   However, after uploading to shinyapps.io, this fails to work correctly.  No error messages appear in the log.   By circumnavigating this date conversion by other methods, the app works fine both locally and on shinyapps.io

Others appear to have had the same issue: e.g.

https://stackoverflow.com/questions/28656683/r-script-working-locally-not-working-on-shinyapp-io

**Comment by alandipert** [comment]
A belated thank-you for the report. Your issue was reported on an internal repo behind shinyapps.io, but I'm not sure whether or not it was eventually resolved.

I bumped that thread and will report back here with any update.

**Comment by alandipert** [comment]
I did a quick test, and this appears to have been fixed, so I'm closing.

I deployed https://alandipert.shinyapps.io/example/ and its title is as.Date("21 January 1981", format = "%d %B %Y") which seems to convert correctly to 1981-01-21.

If I misunderstood or this is otherwise still a problem for you, please don't hesitate to create another issue.
