### ISSUE TITLE
problem with 1.11.1.9003 (maybe due to json conv.?)

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#774]
When I run the shiny example in my htmlwidgets package rdatamaps with v1.11.1.9003 I have problems.
You can install the package with
```
devtools::install_github("smartinsightsfromdata/rdatamaps")
```
You can run the code with:
```R
runGitHub(repo= "rdatamaps",username= "smartinsightsfromdata",subdir="inst/examples")
```
- it works fine with the current shiny version on CRAN
- it has problems with 1.11.1.9003: you can see that the legend is not what it should be and as a result the map colours are all black
 
Could it be a json comp. issue?

**Comment by wch** [comment]
It looks like this is in part because of the switch to jsonlite. If you install the latest version of jsonlite, the problem should go away:

```R
devtools::install_github('jeroenooms/jsonlite'
```

However, you'll see some messages on your console, telling you to switch from using named vectors to named lists. For more information about why that is, see jeroenooms/jsonlite#76 and jeroenooms/jsonlite#82.

**Comment by smartinsightsfromdata** [comment]
@wch thanks for this: loading the newer ```jsonlite``` fixed it.  On the other hand I'm not sure if I should do anything else: the package is developed using ```htmlwidgets```, so I assume when it will switch to ```jsonlite``` the issue will be fixed once and for all (and all be well)?

**Comment by wch** [comment]
I don't think you need to do anything else. I've bumped the version dependency of jsonlite in Shiny, and I assume that will happen in htmlwidgets also. Once the new versions of these packages are on CRAN, everything should just work.
