### ISSUE TITLE
Unicode app does not work on Windows 7

### ISSUE THREAD

**Issue by vzemlys** [rstudio/shiny#785]
The following app with unicode symbols does not work on Windows 7. 

ui.R:
```
library(shiny)
shinyUI(
    fluidPage(                    
              titlePanel(
                  h4("Unicode testing"), "Unicode_test"
              ),
              sidebarLayout(
                  sidebarPanel(
                      selectInput("sel",label="Unicode test",setNames(c("ą", "ū", "ų","š"),c("ž", "į", "ė", "ę")),multiple=TRUE)
                      ),
                  mainPanel(
                      tableOutput("table")
                  )
              )
    )
)
```

server.R:
```
library(shiny)

shinyServer(function(input, output,session) {
       output$table <- renderTable(data.frame(selected=input$sel))
})
```

Furthermore when selecting some of the options, the app crashes with the following message:

```
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input
```

Here is the ```sessionInfo()``` output:
```
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.11.1

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.6 httpuv_1.3.2    mime_0.2        R6_2.0.1        Rcpp_0.11.5     RJSONIO_1.3-0   tools_3.1.3    
[9] xtable_1.7-4   
```

**Comment by wch** [comment]
I'm not entirely sure that we'll be able to make all of this work in Windows. For example, when I run this in Windows (with the same locale settings), I get:

```R
setNames(c("ą", "ū", "ų","š"),c("ž", "į", "ė", "ę"))
#   ž   i   e   e 
# "a" "u" "u" "š" 
```

Looking at the raw values, most (but not all) are represented as ASCII characters.

```R
sapply(c("ą", "ū", "ų", "š"), charToRaw)
#  a  u  u  š 
# 61 75 75 9a 

sapply(c("ž", "į", "ė", "ę"), charToRaw)
#  ž  i  e  e 
# 9e 69 65 65 
```

Even if I put the code in a UTF-8-encoded .R file and try to source it, it still converts some of the chars to ASCII:

```R
# Contents of unicode-test.R. Run with:
#   source('unicode-test.R', encoding='UTF-8', echo = TRUE)

x <- setNames(c("ą", "ū", "ų","š"),c("ž", "į", "ė", "ę"))
x

sapply(c("ą", "ū", "ų","š"), charToRaw)

sapply(c("ž", "į", "ė", "ę"), charToRaw)
```


That said, the crashing is obviously undesirable, and we should have a way to make special chars like these work.

Using the latest development version of Shiny, I don't get the crashes, possibly because it now uses jsonlite instead of RJSONIO. Can you try with the dev version? It also requires installing the latest version of jsonlite.

**Comment by wch** [comment]
FWIW, this produces the correct characters in Windows:

```R
y <- setNames(c("\u0105", "\u016b", "\u0173","\u0161"), c("\u017E", "\u012F", "\u0117", "\u0119"))
y
#   ž   į   ė   ę 
# "ą" "ū" "ų" "š" 
```

The strings are also marked as UTF-8, which is good. However, if you use this in a `selectInput`, it still doesn't provide the expected options.

**Comment by yihui** [comment]
For the `\uxxxx` case, I'm not sure if https://github.com/rstudio/htmltools/pull/21 helps. Perhaps not, because we are using `paste()` in shiny, which might fail to preserve encoding info. The characters in a shiny app have to go through quite a few layers between R and the web browser, and we need to make sure the characters and their encoding info are well preserved in each layer, which makes this problem quite tricky ( plus [the possible bug you reported](http://r.789695.n4.nabble.com/Errors-on-Windows-with-grep-fixed-TRUE-on-UTF-8-strings-td4704073.html)).

What is the language for these characters? `Sys.setlocale()` might help. Or change the system locale in the control panel.

**Comment by vzemlys** [comment]
The language is Lithuanian, but the characters are Unicode, I double-checked, that the ui.R and server.R are in Unicode and tested the same app in Mac OS X, and on Linux.

**Comment by vzemlys** [comment]
I've tested the app with development version of shiny, the letters are still not displayed correctly, but the app does not crash now.

**Comment by yihui** [comment]
Does it work if you change your system locale to Lithuanian in the control panel? Or just do `Sys.setlocale(, 'Lithuanian')` in R, then `runApp()`.

**Comment by vzemlys** [comment]
Yes, with `Sys.setlocale("Lithuanian")` it is working as expected. Sorry to waste your time, I already have stumbled on this some time ago when trying to get the same letters to show in the plots correctly. Prof. Brian Ripley kindly pointed out, that if I want to get locale specific characters I should set locale accordingly. But as with all good advices you tend to forget them.

**Comment by yihui** [comment]
@vzemlys No worries. For R plots, yes, you probably need to set the system locale. For shiny, I think this problem is fixable without changing the system locale, although the ultimate fix can be time-consuming...
