### ISSUE TITLE
Sessions and session@user regression in 0.11.1.9004?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#800]
I'm using shiny server pro, but I develop on shiny server.

In order to bypass the problem, I've developed a simple function:
```R
fGetCurrentUser <- function(session){
  user <- reactive({
    session$user
  })
  if(is.null(user() )){
    user <- "foo"
    return(user)
  }
  return( user() )
}
```
The function has worked well till the installation of 0.11.1.9004.  Now the reactive does not seem to work anymore?
From now on should I just test for:  ``` is.null(session$user)``` ?

**Comment by jcheng5** [comment]
I don't know why the reactive wouldn't work anymore, but it also doesn't
need to be reactive--session$user will never change (and isn't a reactive
value).

Is session$user is always null with 0.11.1.9004?

**Comment by smartinsightsfromdata** [comment]
As mentioned, the function -maybe not exactly right - was working before and this is why I logged it as an issue here.  

Now I changed the function testing for 
```R
length(session$user)==0
```
And this works (outside of shiny server pro). And is also in line what you are saying, i.e. not needing a reactive.

**Comment by jcheng5** [comment]
UGggghh. That's a new bug. Must be because jsonlite is unpacking null
differently.

**Comment by jcheng5** [comment]
This line: https://github.com/rstudio/shiny/blob/master/R/shiny.R#L349 needs to not use the jsonlite default args.

**Comment by jcheng5** [comment]
Enzo, can you print `request$HTTP_SHINY_SERVER_CREDENTIALS` from in there and tell us what the value is, in the case where `is.null()` doesn't give the right answer but `length() == 0` does?

**Comment by smartinsightsfromdata** [comment]
In the app I get
```R
Browse[1]> request$HTTP_SHINY_SERVER_CREDENTIALS
Error: object 'request' not found
```
And
```
Browse[1]> is.null(session$user)
[1] FALSE
```
But I haven't tried in Pro yet. Do you want me to try?

**Comment by yihui** [comment]
Can you just print out the value of `session$user`? I'm curious what it really is, since it is not NULL but has length 0 (could be `list()`).

To print out `websocket$request$HTTP_SHINY_SERVER_CREDENTIALS`, I'm afraid you will have to insert `browser()` here: https://github.com/rstudio/shiny/blob/master/R/shiny.R#L346 and reinstall shiny. I'm not sure if there is a better way to do it.

**Comment by smartinsightsfromdata** [comment]
As requested
```
Browse[1]> print(session$user)
character(0)
```

**Comment by yihui** [comment]
Thanks a lot. That is really odd. Can you `debug(jsonlite::fromJSON)` instead, and see what the values passed to jsonlite::fromJSON are?

**Comment by yihui** [comment]
Okay, I think I have found the smoking gun: https://github.com/rstudio/shiny/commit/b9cef228d99002564eff7df411d9e16802abd6d7 Now the initial value of session$user will be `character(0)` instead of `NULL`. So yes, you need to check `length(session$user) == 0` instead of `is.NULL()`, unless we want to revert the lines 307/308 in that commit.

**Comment by wch** [comment]
Thanks for finding that! I have no particular commitment to using `character(0)` there. Using `NULL` seems like a reasonable default.

**Comment by yihui** [comment]
@wch Okay, let's still use `NULL` then. Thanks!

**Comment by wch** [comment]
OK, I've made the change in 55621b7. @smartinsightsfromdata could you test it out?

**Comment by smartinsightsfromdata** [comment]
@wch it works.  You guys rock!
```R
Browse[2]> is.null(session$user)
[1] TRUE
```

**Comment by wch** [comment]
Great!
