### ISSUE TITLE
validUTF8() in R > 3.2.1

### ISSUE THREAD

**Issue by yihui** [rstudio/shiny#810]
`shiny:::checkEncoding()` is not rigorous. We should use `validUTF8()` in the future.

https://github.com/wch/r-source/commit/1c5b9d61abc0344e5580dbed940bb71f582fde2a

**Comment by suimong** [comment]
The problem I have with checkEncoding() is that, when setting `options(encoding="UTF-8")`, `readLines(file, encoding="UTF-8")` yields errorneous result given that `file` is indeed UTF-8 encoded and contains non-ASCII characters; In this case, `readLines(file)` gives the correct result. I tested this on Windows 7 Pro & Windows 8.1, with locale set to "chinese" & `options(encoding="UTF-8")`.
However, if I left the `encoding` option where it is(that is `"native.enc"`), there seemed to be a whole lot more encoding errors.
Hope you fix this soon!

**Comment by yihui** [comment]
@suimong Sorry, but I cannot fix a problem that I'm unable to reproduce. Can you provide a minimal reproducible example and your sessionInfo()? You may email it to `yihui@rstudio.com`.

**Comment by suimong** [comment]
@yihui I sent you an email. Thank you for looking into it.

**Comment by yihui** [comment]
Okay, your test.txt is encoded in UTF-8:

```
123abc一二三
```

Your R script is:

```r
Sys.setlocale("LC_ALL","chinese")

options(encoding = "")
x1<-readLines("test.txt",encoding = "UTF-8")
options(encoding = "UTF-8")
x2 <- readLines("test.txt",encoding = "UTF-8")
identical(x1,x2)
```

`options(encoding = "")` works for me (which is equivalent to `"native.enc"`). Unless you are an expert knowing well what it means, I'd strongly recommend against setting `options(encoding)` to anything other than `""` or `"native.enc"`. If you mess up with this option, you may open a can of worms when dealing with multibyte characters.

You said you had "a whole lot more encoding errors" if you just leave this alone. What I was asking was a reproducible example for these "whole lot more encoding errors."

BTW, I guess your issue is different with what I meant when I opened this Github issue, but that is fine.

**Comment by suimong** [comment]
@yihui The encoding error I was refering to happens when I was dealing with json files in a shiny app. Back then I was using RJSONIO of which the `fromJSON` function comes with `encoding` argument in  and I have to fiddle around all sorts of options to get Chinese characters properly read in. But you are right about not setting `options(encoding)`. I just did a more thorough test with `RJSONIO`, `rjson` & `jsonlite` and I have found a way to deal with Chinese characters without setting `options(encoding)`.

Another reason I set `options(encoding)` is because I thought that way I don't have to change codes written on Mac or Linux platform. As far as I know, setting `options(encoding="UTF-8")` won't affect Chinese character encoding on Mac, so most people won't bother to add `encoding="UTF-8"` argument to various functions. But on Windows this argument is necessary to ensure correct encoding of Chinese characters.

So it seems that there's no perfect solution here, I'll stick to your advice and leave `options(encoding)` alone. Thank you for your time.

**Comment by yihui** [comment]
jsonlite assumes the JSON file is always UTF8 encoded (it also writes JSON in UTF8). That saves us at least one `encoding` argument :) I see your point of making the code for file I/O portable across Windows and *nix, and `options(encoding)` sounds like an easy solution. Personally I'd rather take the trouble of setting the `encoding` argument explicitly in every single I/O functions.
