### ISSUE TITLE
Should have option to use shiny.js instead of shiny.min.js

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#826]
This would help for debugging.

**Comment by yihui** [comment]
Have you checked the option `Enable JavaScript source maps` in the settings of JavaScript console? Then you can set breakpoints in individual scripts under `srcjs/` and debug them because of the .js.map files. This probably does not work if you install the package because the source js files are not installed -- it works if you `Load All` (which is what I do when I need debugging). Or perhaps we can move `srcjs/` to `inst/www/shared`.

**Comment by wch** [comment]
I have, and it does work when you install and load the package the normal way (ie., with `library(shiny)`, not `load_all()`). The drawback is that, because the JS has been minified, all the variables have mangled names and it's hard to inspect and modify them in the console.

**Comment by yihui** [comment]
Oh yes, that is right.
