### ISSUE TITLE
Print method of plot not called anymore in v0.12.0

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#841]
I'm not sure how `renderPlot` works under the hood, but I was under the impression that `print` is called on the plot object returned from `renderPlot`.

I noticed that upgrading to shiny 0.12.0 broke plots in my shiny app. From my initial investigation it looks like the problem is that `print` isn't being called on my plot object, maybe it's because it's a custom plot object? Here is a simplified reproducible example:

```
library(ggplot2)

myplot <- function(x) {
  plot <- gridExtra::arrangeGrob(x)
  class(plot) <- c("myplot", class(plot))
  plot
}
print.myplot <- function(x, ...) {
  cat("printing")
  grid::grid.draw(x)
}

runApp(list(
  ui = fluidPage(
    plotOutput("plot1"),
    plotOutput("plot2")
  ),
  
  server = function(input, output, session) {
    plot <- reactive({
      p <-
        ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) +
        ggplot2::geom_point()
      myplot(p)
    })
    
    output$plot1 <- renderPlot({
      plot()
    })
    
    output$plot2 <- renderPlot({
      print(plot())
    })
  }
))
```

You'll notice that plot1 has a "no layers in plot" error because the `print` method isn't being called on the plot object. I fixed my shiny app by manually calling print, but I wanted to point it out because I'm not sure if feature or bug :)

**Comment by wch** [comment]
That's definitely possible - the `plotOutput` code was changed for 0.12.0 so that it only tries to `print` certain types of objects. I'll take a look.

**Comment by daattali** [comment]
I figured it's probably looking for a specific class type, so I tried manually prepending "gg" to the classlist, but was disappointed that didn't work. Thanks Winston

**Comment by wch** [comment]
I think I see the problem. If an object has class `ggplot`, it'll try to use this customized version of `print.ggplot` on it:
  https://github.com/rstudio/shiny/blob/master/R/render-plot.R#L283-L295

But in your case, since there is another class that takes precedence, you want the print method for that class to be used. I think this shouldn't be too hard to fix.

**Comment by daattali** [comment]
I love how fast you guys respond to bugs :+1:   I'll keep an eye out for when this issue is closed and test it again on my more complicated real app, thanks

**Comment by wch** [comment]
I've fixed the issue. It will now print out a warning message, though, because it's trying to extract coordmap information from the resulting object:

```
Warning in seq_len(nrow(layout)) :
  first element used of 'length.out' argument
```

That occurs in a `tryCatch` block, so it shouldn't cause any problems. However, it just occurred to me how to avoid this error, so I'll add that fix as well.
