### ISSUE TITLE
Weird behavior if first child of navbarPage is navbarMenu

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#855]
http://stackoverflow.com/questions/22429601/r-shiny-navbarmenu

In this condition, `tab-pane active` shows up as text on the page, and no tab is selected. I'm not 100% sure what should be done here--should we do a depth-first search for a tab, and select the first one we find?

**Comment by daattali** [comment]
I don't know how the code works internally and how weird it would be to implement that, but I think your suggestion would be the desired behaviour in most cases. It's what I'd assume and expect to happen, so I vote for that solution

**Comment by smartinsightsfromdata** [comment]
@jcheng5  Any new on a solution / fix?

**Comment by jsramos** [comment]
Sorry to barge in, but not only that. When I reproduce the example, the selected tabPanel inside the navbaMenu remains selected, but does not show in the app, so that if you traverse all your panels anchored by every one of your navbarMenu items, you'll end up with all your panels selected, but none of them showing. Do you see this same behaviour?

**Comment by sherlock38** [comment]
I have same bug today with shinyapps.io or my server...
the first item in navbarPage can't be a navbarMenu.
if it is a navbarMenu, the focus on sub tabselect don't work and a text "tab-pane active " appear between the first tabselect and the second one.
If ther is a first place in navbarPage a tabselect, all work fine...

Good luck

**Comment by wch** [comment]
This has now been fixed by #1150.

**Comment by guybrettrobertson** [comment]
This issue is still manifesting for me on Shiny v1.7.1!!
