### ISSUE TITLE
shiny-server.pid location stopping server running as shiny user

### ISSUE THREAD

**Issue by dbciar** [rstudio/shiny#917]
Hello,

I'm running shiny-server (version: shiny-server-1.4.0.718-amd64.deb) on Ubuntu 15.04 server, and I have been trying to get it to run as the shiny user rather than root, but I'm having problems with the PID file permissions.  I couldn't see any open/closed tickets on the issue searching for pid || security || root. 

First I ran the following commands to give blanket permissions to the shiny user:
```
sudo chown -R shiny:shiny /var/log/shiny-server
sudo chown -R shiny:shiny /var/log/shiny-server.log
sudo chown -R shiny:shiny /srv/shiny-server
sudo chown -R shiny:shiny /opt/shiny-server
sudo chown -R shiny:shiny /etc/shiny-server
sudo chown -R shiny:shiny /tmp/shiny-server
```
And then I added the line:
```
User=shiny
```
to the systemd service file at: /etc/systemd/system/shiny-server.service under the [Service] area.  I also modified the PID command in the systemd service file to: 
```
PIDFile=/var/run/shiny-server/shiny-server.pid
```
And created the corresponding folder with permissions below followed by the daemon-reload command.
```
sudo mkdir /var/run/shiny-server
sudo chown shiny:shiny /var/run/shiny-server/
sudo systemctl daemon-reload
```
When I try and start the server using 'sudo shiny-server start', the log file displays this error:
```
^[[32m[2015-08-03 22:27:32.830] [INFO] shiny-server - ^[[39mShiny Server v1.4.0.718 (Node.js v0.10.21)
^[[32m[2015-08-03 22:27:32.833] [INFO] shiny-server - ^[[39mUsing pidfile /var/run/shiny-server.pid

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/var/run/shiny-server.pid'
    at Object.fs.openSync (fs.js:427:18)
    at Object.createPidFile (/opt/shiny-server/lib/core/fsutil.js:121:15)
    at Object.<anonymous> (/opt/shiny-server/lib/main.js:82:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

I think I must have missed another place to change the PID location, but not sure where just now.  Any pointers on what/where to change would be great, thanks,
David

**Comment by jcheng5** [comment]
In `/etc/systemd/system/shiny-server.service` there's also a path to the pid file in the ExecStart line, hopefully that will do it.

**Comment by dbciar** [comment]
Yep - thanks for that, that got it working.  I apparently can't see the wood for the trees. :)
Cheers

**Comment by stumari** [comment]
Service won't start on boot. I am getting the same error on Debian Jessie. Paths to the pid file are set correctly in both blocks,  [Service] and [ExecStart].

systemctl status -l shiny-server
● shiny-server.service - ShinyServer
   Loaded: loaded (/etc/systemd/system/shiny-server.service; enabled)
   Active: failed (Result: timeout) since Thu 2016-01-21 20:41:39 ***; 3min 31s ago
  Process: 778 ExecStopPost=/bin/sleep 5 (code=exited, status=0/SUCCESS)
  Process: 603 ExecStartPost=/bin/sleep 3 (code=exited, status=0/SUCCESS)
  Process: 602 ExecStart=/bin/bash -c /opt/shiny-server/bin/shiny-server --pidfile=/var/run/shiny-server/shiny-server.pid >> /var/log/shiny-server.log 2>&1 (code=killed, signal=TERM)
 Main PID: 602 (code=killed, signal=TERM)

Jan 21 20:41:34 debian systemd[1]: shiny-server.service start-post operation timed out. Stopping.
Jan 21 20:41:39 debian systemd[1]: Failed to start ShinyServer.
Jan 21 20:41:39 debian systemd[1]: Unit shiny-server.service entered failed state.

**Comment by jcheng5** [comment]
Can you try this command:

journalctl -u shiny-server.service

(Might have to run as root/sudo)

**Comment by stumari** [comment]
Thanks for a reply, JCheng.
As I wrote before, I am running shiny-server on Debian Jessie (8.3). It is running as a charm now and this is what I did

1. (Unrelated) Earlier, I followed zhilongjia's comment on a separate issue here
https://github.com/rstudio/shiny-server/issues/156
and recompiled shiny-server for libssl-dev (the version that comes with Debian Jessie).
2. I had to dig a bit in systemd man... and changed 'shiny-server.service' file, which now looks as follows (pay attention  to change in TimeoutStartSec=100, otherwise process dies at the startup while waiting for another process, idk who):

[Unit]
Description=ShinyServer

[Service]
TimeoutStartSec=100
PrivateTmp=yes
User=shiny
Group=shiny
RuntimeDirectory=shiny-server

ExecStart=/bin/bash -c '/opt/shiny-server/bin/shiny-server --pidfile=/var/run/shiny-server/shiny-server.pid >> /var/log/shiny-server/shiny-server.log 2>&1'
# ExecStart=/usr/sbin/shiny-server -P /var/run/shiny-server/shiny-server.pid

# Needed to give SS a chance to write out to the PID file.
ExecStartPost=/bin/sleep 5
PIDFile=/var/run/shiny-server/shiny-server.pid
Type=simple

Environment="LANG=en_US.UTF-8"
ExecReload=/bin/kill -HUP $MAINPID
ExecStopPost=/bin/sleep 5
RestartSec=1

[Install]
WantedBy=multi-user.target
