### ISSUE TITLE
Progress bar spanning multiple observers and reactive expressions 

### ISSUE THREAD

**Issue by efh0888** [rstudio/shiny#925]
For apps with many observers and reactive expressions, e.g. http://shiny.rstudio.com/gallery/progress-bar-example.html, it would be great if there was a relatively simple way to set a top level progress bar that spans the whole app and increments based on how many of them are getting run.

**Comment by efh0888** [comment]
For now, I'm using the recommendation by Winston in #609.

**Comment by alandipert** [comment]
Hello, thank you for the suggestion, and sorry to take so long respond to this 😄 

I'm closing this because I find it close enough to #609 to be considered a duplicate. However, if you wished to elaborate on #609 about how your suggestion would differ from Winston's proof of concept, that effort would be much appreciated.
