### ISSUE TITLE
renderImage - class attribute

### ISSUE THREAD

**Issue by tinyheero** [rstudio/shiny#936]
According to the [renderImage](http://shiny.rstudio.com/reference/shiny/latest/renderImage.html) page, there should be a way to specify the "class" element in the list:

Other elements such as width, height, class, and alt, can also be added to the list, and they will be used as attributes in the img object.

I would like to assign the img a class so that I can use css to float it. But doesn't seem to work. Also the [Shiny - Render images in a Shiny app](http://shiny.rstudio.com/articles/images.html) reference page, doesn't list the class element under the section "Structure of the returned list". Has this option been removed?

Thanks,

Fong

**Comment by wch** [comment]
Hm, this is a little tricky. The Javascript code loops over all the elements of the list and sets the properties of the img element here: https://github.com/rstudio/shiny/blob/be1081a/srcjs/output_binding_image.js#L66-L69

The reason that `class` doesn't work is because, in Javascript, you actually need to set `className` instead of `class`. For example, this code works:

```R

shinyApp(
  ui = fluidPage(
    sliderInput("n", "N", 10, 200, 50),
    plotOutput("plot1")
  ),
  
  server = function(input, output) {
    output$plot1 <- renderImage({
      outfile <- tempfile(fileext='.png')
      
      png(outfile, width=400, height=400)
      hist(rnorm(input$n))
      dev.off()
      
      list(
        src = outfile,
        alt = "This is alternate text",
        className = paste0("foo", input$n)
      )
    }, deleteFile = TRUE)
  }
)
```
