### ISSUE TITLE
plot: window resize forces reevaluation

### ISSUE THREAD

**Issue by bdhoyer** [rstudio/shiny#937]
Issue based on:
http://stackoverflow.com/questions/32010773/r-shiny-plot-window-resize-forces-reevaluation
(Bug report suggested by Hadley.)

I have a plot where I can click on the point to bring up a line in a data table below the plot. Depending on the window size, clicking and making a line in the data table may cause scroll bars to be generated in the window. This causes the plot to re-draw, and the "click" is forgotten, the data table line is removed, the scroll bar is removed, and I am back to square one.

See this video for a demo. (Note: the cursor is placed incorrectly by my screen capture software. This is not the issue.)
https://www.youtube.com/watch?v=TsM1WppTQi8

MWE:

    library(shiny)
    library(ggplot2)
    
    UI <- fluidPage(mainPanel(
      plotOutput("plot", click = "plot_click"),
      tableOutput("info_click")
    ))
    
    SERVER <- function(input, output) {
    # make simple plot
    output$plot <- renderPlot({
        ggplot(mtcars, aes(mpg,cyl)) + geom_point()
    })
    # read local point from click
    output$info_click <- renderTable({
    	 nearPoints(mtcars, input$plot_click, threshold = 10, maxpoints = 1)
    })
    }

    runApp(shinyApp(UI,SERVER))

You will need to play around with the window size for the bug to come up. Occurs on any browser that I have checked. (Opera, Firefox, Chrome)

**Comment by martinjhnhadley** [comment]
I have a very similar problem, both yours and mine are "fixed" by adding 

```tags$style(type="text/css", "body { overflow-y: scroll; }")``` 

to the `fluidPage`. 

It is a hack solution as far as I'm concerned, because the "click data" will not survive a resize of the application window.

**Comment by jcheng5** [comment]
If you don't want the plot to redraw on resize, you can also fix the size
of the plotOutput by giving it an absolute width argument, like width =
600. Does that help?

**Comment by skipperhoyer** [comment]
@martinjhnhadley The tags solution does indeed work, although on window-resize, click events are lost anyway.
@jcheng5 Fixing the width would work, but I need to be flexible with regards to plot size, since my users will be on a variety of devices / screen sizes.
Is there some way / hack to implement the following:
1) Window resize.
2) Plot needs to be redrawn, but plot is not redrawn. Click events saved.
3) User presses "redraw plot"/"resize plot" button, which triggers re-drawing of plot (and loss of click data).
So essentially redrawing is delayed until user triggers it. Perhaps setting absolute height/width in plotOutput() but where this is actually based on something read from the user's session info? (I assume this bit of code already exists, since it is what the native fluidPage() does anyway.) Then it might be easier to add a "redraw" action button, which then re-reads window dimensions on demand.

**Comment by jcheng5** [comment]
(Going through old bugs)

Or save the user-coordinates of the click in a reactiveValues object?

```r
rv <- reactiveValues(click = NULL)

observeEvent(input$plot_click, { rv$click <- input$plot_click })
```

Then everywhere you reference `input$plot_click`, reference `rv$click` instead?

**Comment by kramerrs** [comment]
I am having a similar issue.  It appears to be related flex dashboard and bootstrap themes.  I can't save the click data, because resizing the window causes the entire app to relaunch.  All state is lost.

**Comment by gadenbuie** [comment]
Hi @kramerrs, flexdashboard does something quite different from Shiny in this regard; in particular it triggers a full app restart when the browser is resized from a mobile screen width to a wider screen site. If you want to discuss further, I recommend opening an issue in [the flexdashboard repo](https://github.com/rstudio/flexdashboard/issues).
