### ISSUE TITLE
Interactive no longer works on ggplots with facetting.

### ISSUE THREAD

**Issue by coolbutuseless** [rstudio/shiny#962]
ggplots with facetting no longer work with interactive elements.

The ggplot commit which broke this appears to be: https://github.com/hadley/ggplot2/commit/47fc3d69ebdc6f1894e711b92460c0d9f2f1347d

This is most likely a shiny issue - with how it is fetching plot coords - but hopefully @hadley can shed some light on why the changes may have broken interactivity.

**Comment by jcheng5** [comment]
Confirmed, thanks!

**Comment by coolbutuseless** [comment]
Thanks for confirming. It took me a while to track this down - bisected shiny commits, rstudio installs, R versions and finally ggplot commits to isolate the "bad" commit.

**Comment by wch** [comment]
@coolbutuseless Thanks for the very helpful bisect! I just pushed a fix. The root cause is that vectors of units can actually be represented in two ways. One way is as a list of unit objects (a `unit.list`), where each unit object has its own set of attributes. The other way is as an atomic vector, with one set of attributes shared across all of the units. The commit you found contained a switch from the first type to the other. The fix was to make Shiny recognize and handle both types.

**Comment by coolbutuseless** [comment]
Excellent! thanks!

**Comment by frajuegies** [comment]
Hi,
as ggplot2 2.0 is on CRAN and I am observing the same issue with shiny 12.2 I would like to ask, when shiny will be updated on CRAN? Do you have already a timeline?

Wishing you all a very nice X-mas and a happy new year.

Jürgen

**Comment by wch** [comment]
We will definitely have a new version of Shiny on CRAN by the end of January, In the meantime you can install the development version with `devtools::install_github`.

**Comment by frajuegies** [comment]
Thank you very much for this update....

Wishing you and the team all the best in 2016

Jürgen
