### ISSUE TITLE
R6 object reactivity doesnt work

### ISSUE THREAD

**Issue by FrissESC** [rstudio/shiny#963]
Hi,

In my app i have an R6 object which i assign to a reactiveValues object. When i update the R6 object the reactivity doesnt seem to work. 
I created a gist with a minimal example: https://gist.github.com/FrissESC/4080e35fefdbdb6da63d

In the example you can see both objects are initialized with value 50, but after the button press only the lower number is changed (which also has a dependency on the button) . While the value of the first one is also changed but not updated.
From the cat statement from the R code you can see that both values are changed.

Can you help me out?

Kind regards,
Erwin

**Comment by wch** [comment]
Interesting... This is because of the an optimization in `reactiveValues` -- when you call `$<-.reactiveValues`, if the new value is the same as the existing one, then it simply returns without triggering any reactivity:
  https://github.com/rstudio/shiny/blob/99295f0/R/reactives.R#L87-L90

The purpose of this is to reduce work: usually there's no need to invalidate downstream reactives when a value is unchanged -- but in the case of R6 objects, environments, and Reference Class objects, the `identical()` check doesn't really tell us if the object was unchanged.

This is something we'll have to discuss and figure out how best to approach.

**Comment by jcheng5** [comment]
Unfortunately this is "as designed". No frameworks of this kind in any language ever treat mutations of reference objects (in R, that means environments, ref classes, R6 classes, and external pointers) as detectable modifications. I would consider carefully whether you really need to use an R6 object to model your application's state in this case. Sorry I don't have better news to offer.

**Comment by jcheng5** [comment]
That was probably a little too definitive--let me qualify that by saying, no framework that I have ever heard of :)

**Comment by FrissESC** [comment]
Thanks for the clear answers. 
What i am trying to achieve is to make a shiny app with a Model View Control design pattern in mind, the R6 class(es) would hold my model. I could achieve the reactivity by assigning results from my model class to a reactiveValues object to achieve what i want, then the app state and model would be separate.

**Comment by shrektan** [comment]
I've done a similar project recently(R6 as modeling and shiny for control panel). I would say it should not be a problem  to achieve what you want without assigning R6 as reactiveValue directly. 

发自我的 iPhone

**Comment by jcheng5** [comment]
Frankly I am quite skeptical of any value you'll get by using R6 here--if you have to go OO I'd suggest using S3 and its value semantics.

Perhaps this approach at modularization might resonate with you. It's not precisely the way I would do it myself, but it is a quite reasonable approach.
https://github.com/ijlyttle/shinychord
