### ISSUE TITLE
Maximum column width Is 12

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#974]
The documentation explains that `width` is `The grid width of the column (must be between 1 and 12)`. It seems restrictive to enforce a total width of 12. Why can't the total width be a variable which is specified by the user ? Also, the documentation should explain that `width` must be an integer.

**Comment by jcheng5** [comment]
This limitation may seem arbitrary but it comes from Bootstrap. That being said I think 12 columns is a reasonable choice as many common layouts can be expressed as factors of 12, and a fixed number had to be chosen by Bootstrap because all of the size rules are in pure CSS. 

If you need something more flexible you are probably better served by writing your own CSS rules for now.
