### ISSUE TITLE
runGist is broken

### ISSUE THREAD

**Issue by pranasblk** [rstudio/shiny#996]
```
> library(shiny)
> shiny::runGist("c4db11d81f3c46a7c4a5")
Downloading https://gist.github.com/c4db11d81f3c46a7c4a5/download
wget: invalid option -- 'f'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Error in runUrl(gistUrl, filetype = ".zip", destdir = destdir, ...) : 
  Failed to download URL https://gist.github.com/c4db11d81f3c46a7c4a5/download
In addition: Warning message:
In utils::download.file(url, method = method, ...) :
  download had nonzero exit status
> library(shiny); sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.2

loaded via a namespace (and not attached):
[1] R6_2.1.1        htmltools_0.2.6 tools_3.2.2     Rcpp_0.12.1     digest_0.6.8    xtable_1.7-4    httpuv_1.3.3   
[8] mime_0.4  
```

**Comment by wch** [comment]
I suspect there's a problem when `shiny:::download` calls R's `download.file` function. What do you get if you run `getOption("download.file.extra")`?

**Comment by wch** [comment]
I'm not on my Mac now, but @hadley tells me that the the default value of `getOption("download.file.extra")` is `-L -f` on his Mac running R 3.2.2. These are options for curl, but `shiny:::download` is trying to use `wget` first. The problem is that it's not possible to tell whether the `download.file.extra` options are for curl or wget.

I think the best solution is to simply update `shiny:::download` to have the same code as [`downloader::download`](https://github.com/wch/downloader/blob/ad23b1881ab928b9bba8e47181062d530a30b894/R/download.r#L39-L109). For R 3.2.2 and higher, it'll try to use `libcurl` first (not `curl`), which should avoid using the `download.file.extra` options. And I assume for older versions of R, the `download.file.extra` options won't be set, so `wget` should continue to work.

**Comment by jcheng5** [comment]
Yes, definitely.

**Comment by kevinushey** [comment]
Note that `libcurl` is broken with R <= 3.2. It treats 404s as successes and downloads the 404 as though it were the intended response.

**Comment by pranasblk** [comment]
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> getOption("download.file.extra")
[1] "-L -f"

**Comment by zippeurfou** [comment]
getting the same issue here.
